### ISSUE TITLE
Android Studio "Bazel sync succeed but there were sync errors"

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/intellij#1088]
Following the official [Bazel Android Tutorial](https://docs.bazel.build/versions/master/tutorial/android-app.html) I can successfully build on command-line but it fails when I try to import the project into Android Studio

Bazel Plugin version: `2019.07.23.0.3`

```
ERROR: /private/var/tmp/_bazel_n.korostelev/a585bca567d74f96e9093b839c52abb5/external/androidsdk/BUILD.bazel:8:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on android_sdk rule @androidsdk//:sdk-28: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_n.korostelev/a585bca567d74f96e9093b839c52abb5/external/androidsdk/BUILD.bazel", line 8
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/private/var/tmp/_bazel_n.korostelev/a585bca567d74f96e9093b839c52abb5/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/private/var/tmp/_bazel_n.korostelev/a585bca567d74f96e9093b839c52abb5/external/intellij_aspect/intellij_info_impl.bzl", line 896, in intellij_info_aspect_impl
		collect_android_sdk_info(ctx, ide_info, ide_info_file, output_g...)
	File "/private/var/tmp/_bazel_n.korostelev/a585bca567d74f96e9093b839c52abb5/external/intellij_aspect/intellij_info_impl.bzl", line 743, in collect_android_sdk_info
		list(ctx.rule.attr.android_jar.files)
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

```
Android Studio 3.5 RC 3
Build #AI-191.8026.42.35.5781497, built on August 5, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
```

**Comment by jin** [comment]
Can you add `--incompatible_depset_is_not_iterable=false` to your project's `.bazelrc` file for now? I'm submitting a fix.
