### ISSUE TITLE
MissingResourceException when trying to make a module

### ISSUE THREAD

**Issue by ctsimmonds** [bazelbuild/intellij#118]
When I try to build a module with this plugin, it always immediately fails with the following exception:

> Error:Android Source Generator: Error: Can't find bundle for base name messages.AndroidJpsBundle, locale en_CA
java.util.MissingResourceException: Can't find bundle for base name messages.AndroidJpsBundle, locale en_CA
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.jetbrains.jps.android.AndroidJpsBundle.getBundle(AndroidJpsBundle.java:22)
	at org.jetbrains.jps.android.AndroidJpsBundle.message(AndroidJpsBundle.java:32)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.computeModuleDatas(AndroidSourceGeneratingBuilder.java:1276)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.doBuild(AndroidSourceGeneratingBuilder.java:130)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.build(AndroidSourceGeneratingBuilder.java:114)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1263)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:940)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1012)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:903)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:736)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:384)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:192)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:236)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by brendandouglas** [comment]
Which version of Android Studio / IntelliJ and the Bazel plugin are you using?

We don't support building/compiling modules natively with Android Studio / IntelliJ -- the plugin delegates those actions to Bazel.

Which action did you run to produce this error?

**Comment by ctsimmonds** [comment]
I was using Android Studio 3.0 Canary 8 with version 2017.07.05.0.2 of the plugin, on macOS 10.12.6.

I got the error after going to the Build menu and selecting the Make Module menu item.

If building in the IDE is not supported, how do I get it to index the Java code for searching? I primarily want to be able to navigate around in code and find usages of identifiers.

**Comment by brendandouglas** [comment]
We don't yet support AS 3.0 (the latest Bazel plugin is built against AS 2.3, and I'd expect many plugin features to be currently broken in 3.0).

That 'Make Module' item is normally suppressed for Bazel projects -- it might have regressed in 3.0, or perhaps your project isn't registering as a Bazel project.

You can build your project with Bazel using the 'Bazel > Sync > Sync project with BUILD files' action (the red 'B' button in the toolbar).

That action is only present for Bazel projects though -- if it's not there, you'll first need to import a Bazel project (File > Import Bazel Project).

**Comment by ctsimmonds** [comment]
That was the problem - it wasn't detected as a Bazel project, and I was able to build from the Bazel menu once it was.

**Comment by JackzrLiu** [comment]
when I update my Android Studio form 2.3 to 3.0 stable, I get the same problem!

Error:Android Source Generator: Error: Can't find bundle for base name messages.AndroidJpsBundle, locale zh_CN
java.util.MissingResourceException: Can't find bundle for base name messages.AndroidJpsBundle, locale zh_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.jetbrains.jps.android.AndroidJpsBundle.getBundle(AndroidJpsBundle.java:22)
	at org.jetbrains.jps.android.AndroidJpsBundle.message(AndroidJpsBundle.java:32)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.runAidlCompiler(AndroidSourceGeneratingBuilder.java:688)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.doBuild(AndroidSourceGeneratingBuilder.java:198)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.build(AndroidSourceGeneratingBuilder.java:114)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1263)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:940)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1012)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:903)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:736)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:384)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:192)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:236)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by miyuehu** [comment]
when I update my Android Studio form 2.3 to 3.0 stable, I get the same problem!

**Comment by MailKZ** [comment]
Error:Android Source Generator: Error: Can't find bundle for base name messages.AndroidJpsBundle, locale ru_RU
java.util.MissingResourceException: Can't find bundle for base name messages.AndroidJpsBundle, locale ru_RU
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.jetbrains.jps.android.AndroidJpsBundle.getBundle(AndroidJpsBundle.java:22)
	at org.jetbrains.jps.android.AndroidJpsBundle.message(AndroidJpsBundle.java:32)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.runAidlCompiler(AndroidSourceGeneratingBuilder.java:688)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.doBuild(AndroidSourceGeneratingBuilder.java:198)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.build(AndroidSourceGeneratingBuilder.java:114)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1263)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:940)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1012)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:903)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:736)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:384)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:192)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:236)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lenovo123** [comment]
when I update my Android Studio form 2.3 to 3.0 stable, I get the same problem!
Google, can you please fix this issue.

**Comment by GarvitaBajaj** [comment]
I am getting the same problem after updating Android Studio from 2.3 to 3.0.

**Comment by brendandouglas** [comment]
How are you importing your Bazel project? Can you try recreating it from scratch, via 'File > Import Bazel Project'?

**Comment by f839903061** [comment]
I have the same problem ,android studio 3.0
![Android Studio Version](https://imgur.com/Dvcjodx)

**Comment by brendandouglas** [comment]
We don't yet support AS 3.0.1. You can see which versions the plugin has been built for [here](https://plugins.jetbrains.com/plugin/9185-bazel).

I'd recommend downgrading to 171.4249 or earlier.

The next version, scheduled for release Friday December 15th, is built against 171.4408382. It will also likely not work with 3.0.1, but is at least built against a stable version of 3.0.0.
