### ISSUE TITLE
IDE error on sync fail

### ISSUE THREAD

**Issue by cromefire** [bazelbuild/intellij#1272]
```
java.util.concurrent.ExecutionException: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 2
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:526)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:507)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:96)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:86)
	at com.google.idea.blaze.base.sync.ProjectStateSyncTask.getProjectState(ProjectStateSyncTask.java:123)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:89)
	at com.google.idea.blaze.base.sync.ProjectStateSyncTask.collectProjectState(ProjectStateSyncTask.java:67)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:328)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:196)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:33)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:188)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:78)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:185)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:126)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 2
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.runBlazeInfo(BlazeInfoRunnerImpl.java:102)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:72)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	... 3 more
```

I guess this should be catched instead of getting an IDE error

**Comment by jin** [comment]
IDE and Bazel versions? (Menu -> Bazel -> File an Issue on GitHub)

**Comment by cromefire** [comment]
Webstorm 2019.2.3 & 2019.10.01.1.1 (both latest of course)

**Comment by MikhailTymchukFT** [comment]
I have similar error. Then my terminal refuses to execute any bazel command, even if I point directly to `/usr/local/bin/bazel`.
Instead, it shows Unhandled Control sequence:
```
2020-07-17 00:05:50,451 [1077398]   INFO - BridgeProjectLifecycleListener - Using legacy project model to open project 
2020-07-17 00:05:50,466 [1077413]   INFO - rojectCodeStyleSettingsManager - Initialized from default code style settings. 
2020-07-17 00:05:52,488 [1079435]   INFO - tch.PrefetchProjectInitializer - Couldn't load project data for prefetcher 
2020-07-17 00:05:52,518 [1079465]   INFO - ge.ExternalProjectsDataStorage - Load external projects data in 0 millis (read time: 0) 
2020-07-17 00:05:52,524 [1079471]   INFO - ProjectRootPostStartUpActivity - /Users/mikhailtymchuk/repos/java4/.ijwb/.idea case-sensitivity: expected=false actual=false 
2020-07-17 00:05:52,526 [1079473]   INFO - .diagnostic.PerformanceWatcher - Post-startup activities under progress took 10ms; general responsiveness: ok; EDT responsiveness: ok 
2020-07-17 00:05:52,593 [1079540]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Problems View) or icon jar:file:/Applications/IntelliJ%20IDEA%20CE.app/Contents/lib/icons.jar!/general/warning.svg 
2020-07-17 00:05:52,606 [1079553]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 2160 ms 
2020-07-17 00:05:52,607 [1079554]   INFO - .prefetch.PrefetchIndexingTask - Reading local caches took: 70 ms 
2020-07-17 00:05:52,652 [1079599]   INFO - .prefetch.PrefetchIndexingTask - Initial Prefetching took: 113 ms 
2020-07-17 00:05:52,654 [1079601]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 1ms; general responsiveness: ok; EDT responsiveness: ok 
2020-07-17 00:05:52,656 [1079603]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 2ms; general responsiveness: ok; EDT responsiveness: ok 
2020-07-17 00:05:52,695 [1079642]   INFO - base.scope.scopes.IdeaLogScope - Syncing project: Initial directory update (no_build)... 
2020-07-17 00:05:52,812 [1079759]   INFO - base.scope.scopes.IdeaLogScope - Updating VCS... 
2020-07-17 00:05:52,814 [1079761]   INFO - base.scope.scopes.IdeaLogScope - Running Bazel info... 
2020-07-17 00:05:52,815 [1079762]   INFO - base.scope.scopes.IdeaLogScope - Command: /usr/local/bin/bazel info --tool_tag=ijwb:IDEA:community --curses=no --color=yes --progress_in_terminal_title=no --
 
2020-07-17 00:05:52,869 [1079816]   INFO - base.scope.scopes.IdeaLogScope - Command: git diff --name-status --no-renames ae5c87a568f69dabe499e6187fdaa97f3dbf620b
 
2020-07-17 00:05:52,873 [1079820]  ERROR - ea.blaze.base.async.FutureUtil - com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 1 
java.util.concurrent.ExecutionException: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 1
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:553)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:534)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:98)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:88)
	at com.google.idea.blaze.base.sync.ProjectStateSyncTask.getProjectState(ProjectStateSyncTask.java:126)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:89)
	at com.google.idea.blaze.base.sync.ProjectStateSyncTask.collectProjectState(ProjectStateSyncTask.java:68)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:379)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:225)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:33)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:217)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:54)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 1
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.runBlazeInfo(BlazeInfoRunnerImpl.java:102)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:72)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	... 3 more
2020-07-17 00:05:52,874 [1079821]  ERROR - ea.blaze.base.async.FutureUtil - IntelliJ IDEA 2020.1.3  Build #IC-201.8538.31 
2020-07-17 00:05:52,874 [1079821]  ERROR - ea.blaze.base.async.FutureUtil - JDK: 1.8.0_202; VM: Java HotSpot(TM) 64-Bit Server VM; Vendor: Oracle Corporation 
2020-07-17 00:05:52,874 [1079821]  ERROR - ea.blaze.base.async.FutureUtil - OS: Mac OS X 
2020-07-17 00:05:52,874 [1079821]  ERROR - ea.blaze.base.async.FutureUtil - Plugin to blame: Bazel version: 2020.06.25.0.3 
2020-07-17 00:05:52,874 [1079821]  ERROR - ea.blaze.base.async.FutureUtil - Last Action: Blaze.ImportProject2 
2020-07-17 00:05:52,875 [1079822]   WARN - base.scope.scopes.IdeaLogScope - Could not run Bazel info 
2020-07-17 00:05:52,875 [1079822]   INFO - base.scope.scopes.IdeaLogScope - Sync finished 
2020-07-17 00:05:52,910 [1079857]   INFO - rationStore.ComponentStoreImpl - Saving appVcs.Log.App.Settings took 11 ms 
2020-07-17 00:05:52,918 [1079865]   INFO - base.scope.scopes.IdeaLogScope - Syncing project: Sync (full)... 
2020-07-17 00:05:52,991 [1079938]   INFO - base.scope.scopes.IdeaLogScope - Updating VCS... 
2020-07-17 00:05:52,993 [1079940]   INFO - base.scope.scopes.IdeaLogScope - Running Bazel info... 
2020-07-17 00:05:52,993 [1079940]   INFO - base.scope.scopes.IdeaLogScope - Command: /usr/local/bin/bazel info --tool_tag=ijwb:IDEA:community --curses=no --color=yes --progress_in_terminal_title=no --
 
2020-07-17 00:05:53,025 [1079972]  ERROR - ea.blaze.base.async.FutureUtil - com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 1 
java.util.concurrent.ExecutionException: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 1
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:553)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:534)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:98)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:88)
	at com.google.idea.blaze.base.sync.ProjectStateSyncTask.getProjectState(ProjectStateSyncTask.java:126)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:89)
	at com.google.idea.blaze.base.sync.ProjectStateSyncTask.collectProjectState(ProjectStateSyncTask.java:68)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:379)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:225)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:33)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:217)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:54)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 1
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.runBlazeInfo(BlazeInfoRunnerImpl.java:102)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:72)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	... 3 more
2020-07-17 00:05:53,026 [1079973]  ERROR - ea.blaze.base.async.FutureUtil - IntelliJ IDEA 2020.1.3  Build #IC-201.8538.31 
2020-07-17 00:05:53,027 [1079974]  ERROR - ea.blaze.base.async.FutureUtil - JDK: 1.8.0_202; VM: Java HotSpot(TM) 64-Bit Server VM; Vendor: Oracle Corporation 
2020-07-17 00:05:53,027 [1079974]  ERROR - ea.blaze.base.async.FutureUtil - OS: Mac OS X 
2020-07-17 00:05:53,027 [1079974]  ERROR - ea.blaze.base.async.FutureUtil - Plugin to blame: Bazel version: 2020.06.25.0.3 
2020-07-17 00:05:53,027 [1079974]  ERROR - ea.blaze.base.async.FutureUtil - Last Action: Blaze.ImportProject2 
2020-07-17 00:05:53,027 [1079974]   WARN - base.scope.scopes.IdeaLogScope - Could not run Bazel info 
2020-07-17 00:05:53,027 [1079974]   INFO - base.scope.scopes.IdeaLogScope - Sync finished 
2020-07-17 00:05:53,028 [1079975]   INFO - base.scope.scopes.IdeaLogScope - Command: git diff --name-status --no-renames ae5c87a568f69dabe499e6187fdaa97f3dbf620b
 
2020-07-17 00:05:53,028 [1079975]   WARN - base.scope.scopes.IdeaLogScope - Sync failed 
2020-07-17 00:06:09,563 [1096510]  ERROR - terminal.emulator.JediEmulator - Error processing OSC 1;~/repos/java4 
2020-07-17 00:06:09,598 [1096545]  ERROR - terminal.emulator.JediEmulator - Unhandled Control sequence
parsed                        :ESC[?2004h
bytes read                    :ESC[ 
```

IdeaCommunity: 2020.1.3
Platform: Mac OS X 10.15.5
Bazel plugin: 2020.06.25.0.3

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
