### ISSUE TITLE
ClassNotFoundException: MissingDependencyTargetProviderImpl

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/intellij#1300]
```
java.lang.ClassNotFoundException: com.google.idea.blaze.base.dependencies.MissingDependencyTargetProviderImpl PluginClassLoader[com.google.idea.bazel.ijwb, 2029.10.22.0.0] com.intellij.ide.plugins.cl.PluginClassLoader@7b003cf2
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:398)
    at com.intellij.openapi.components.impl.ServiceManagerImpl.processAllImplementationClasses(ServiceManagerImpl.java:127)
    at com.intellij.configurationStore.DefaultProjectElementNormalizerKt.moveComponentConfiguration(defaultProjectElementNormalizer.kt:114)
    at com.intellij.configurationStore.DefaultProjectElementNormalizerKt.normalizeDefaultProjectElement(defaultProjectElementNormalizer.kt:52)
    at com.intellij.configurationStore.ProjectStoreBase.loadProjectFromTemplate(ProjectStoreBase.kt:81)
    at com.intellij.configurationStore.ProjectStoreBase.setPath(ProjectStoreBase.kt:150)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:284)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.newProject(ProjectManagerImpl.java:192)
    at com.intellij.openapi.project.ex.ProjectManagerEx.createProject(ProjectManagerEx.java:96)
    at com.intellij.ide.util.projectWizard.ProjectBuilder.createProject(ProjectBuilder.java:76)
```

Looks like the first commit wasn't properly backed out by the second:

https://github.com/bazelbuild/intellij/commit/a0c251832eb8bfe33b048b83d2e9749061616553
https://github.com/bazelbuild/intellij/commit/cb64475c86980fc590c839fb0bb6f47b0bdc7b72

**Comment by brendandouglas** [comment]
Thanks, we'll fix this upstream.
