### ISSUE TITLE
Gerrit Build Fails using intellij-CE-2019.1 plugin.

### ISSUE THREAD

**Issue by trevorgetty** [bazelbuild/intellij#1309]
I have installed default IJ-2019.1 CE edition.
Install the Bazel plugin latest supported version for this IJ, which was: v2019.08.05 from the official Bazel Jetbrains repository.
Bazel build works fine for the project.
But when you try to import the project / sync it with the workspace it always fails with this error:

```
ERROR: /home/trevor/development/vanilla/gerrit/gerrit-2.16/tools/BUILD:11:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on py_binary rule //tools:merge_jars: 
Traceback (most recent call last):
	File "/home/trevor/development/vanilla/gerrit/gerrit-2.16/tools/BUILD", line 11
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/home/trevor/.cache/bazel/_bazel_trevor/d727a15682ad095c2677225881c6eee5/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/home/trevor/.cache/bazel/_bazel_trevor/d727a15682ad095c2677225881c6eee5/external/intellij_aspect/intellij_info_impl.bzl", line 889, in intellij_info_aspect_impl
		collect_py_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File "/home/trevor/.cache/bazel/_bazel_trevor/d727a15682ad095c2677225881c6eee5/external/intellij_aspect/intellij_info_impl.bzl", line 294, in collect_py_info
		struct_omit_none(sources = sources, launcher = py_l..., <2 more arguments>)
	File "/home/trevor/.cache/bazel/_bazel_trevor/d727a15682ad095c2677225881c6eee5/external/intellij_aspect/intellij_info_impl.bzl", line 298, in struct_omit_none
		_get_python_srcs_version(ctx)
	File "/home/trevor/.cache/bazel/_bazel_trevor/d727a15682ad095c2677225881c6eee5/external/intellij_aspect/intellij_info_impl.bzl", line 270, in _get_python_srcs_version
		getattr(ctx.rule.attr, "srcs_version", defau...")
unexpected keyword 'default', for call to function getattr(x, name, default = unbound)
```

This appears to be because the getattr, version in the official release, has removed "default" from being a named parameter, to being purely a positional param.

Now I can see that you have indeed fixed this issue in later versions of the IJ plugin for 2019.2 / .3, by this PR change. https://github.com/bazelbuild/intellij/commit/3b0fcdd90f42922c8deab01c0d5666e30fac5504#diff-3a3a2e2292228746349df940a4d3d83b

Would it please be possible to pull this back into earlier code stream and publish another update for CE2019.1 if possible.   thanks.

**Comment by jin** [comment]
> Would it please be possible to pull this back into earlier code stream and publish another update for CE2019.1 if possible. thanks.

The team isn't shipping any more updates for 2019.1. Please update to 2019.2, or manually build the plugin with the aforementioned cherrypick.
