### ISSUE TITLE
Cannot use with Java 9 Installed

### ISSUE THREAD

**Issue by deontologic** [bazelbuild/intellij#133]
With JAVA_HOME pointing to the Java 8 JDK (and bazel working fine in the terminal), the Intellij Plugin fails to sync, giving the error `cannot find rt.jar in <jdk9 path>`. 

I also have the Intellij project settings at java 8.

The issue was solved with `rm -rf /Library/Java/JavaVirtualMachines/jdk-9`, but I would like to have java 9 installed.

**Comment by brendandouglas** [comment]
Do you have a stack trace in your logs which might give a clue where that error is coming from?

It doesn't sound like a problem with the bazel plugin specifically; more likely a problem with IntelliJ itself.

**Comment by deontologic** [comment]
I reinstalled Java 9, and had no problem running the project (without any file changes). "Bazel > Sync > Sync Project with Build Files" throws the exceptions:
```
Syncing project...
Updating VCS...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:IDEA:community --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --


Running Bazel info...
Command: git diff --name-status --no-renames 145b8351a321ddaf8454f4356033f644057786ad


Problem with java installation: couldn't find/access rt.jar in /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Sync failed

==== TIMING REPORT ====

Sync: 555ms (270ms)
    BazelInfo: 239ms
    GitDiff: 46ms

```



```
com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 1
java.util.concurrent.ExecutionException: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 1
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:93)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:83)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:266)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:197)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:164)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:141)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:108)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:105)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 1
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.runBlazeInfo(BlazeInfoRunnerImpl.java:105)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:75)
	... 6 more
```

**Comment by brendandouglas** [comment]
Thanks, it's 'bazel info' that's failing (specifically, in [startup_options.cc](https://github.com/bazelbuild/bazel/blob/aa0093be3800911f6d0f1ff4564d9eebd24fbeae/src/main/cpp/startup_options.cc)).

Bazel-side issue is here: https://github.com/bazelbuild/bazel/issues/3410

**Comment by deontologic** [comment]
Unlike [bazelbuild/bazel#3410](https://github.com/bazelbuild/bazel/issues/3410), I can't run use the IDE with Java 9 **even installed**. I understand that Java 9 support will take some time, but this issue occurs in the IDE plugin. `bazel info` runs fine in the terminal, but fails in Intellij. JavaHome is set to Java 8 in both cases.

**Comment by brendandouglas** [comment]
It sounds like, when invoked from IntelliJ, Bazel is using Java 9. That suggests there's an environment variable set somewhere, either when IntelliJ is lauched, or when the the external process is spawned from IJ.

The plugin doesn't currently set any environment variables, so this is either coming from IJ itself, or was set when lauching IJ.

Can you confirm that this still happens when re-launching IJ from the same terminal in which bazel info works?

**Comment by deontologic** [comment]
Resolved with `launchctl setenv JAVA_HOME "/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home"` 👍

**Comment by fantasticfears** [comment]
@deontologic This changes the system env which may not be desired. At least, I would like to use JDK 9 for others.

@brendandouglas I suppose your guess are right. I put JDK_HOME=<jdk8> in the settings of the plugin. It doesn't work. But in the terminal, my alias works perfectly.

**Comment by 4cm4k1** [comment]
Here's something you all might find helpful in the meantime: https://github.com/gcuisinier/jenv

It's just like `rbenv` in that it allows you to manage multiple Java versions, switch between them, and even export/expose `JAVA_HOME` and other environment variables to the shell or gradle, etc. 😄

**Comment by thundergolfer** [comment]
I think this issue should be re-opened, because this behaviour still seems to be present in the plugin. With Java 10/11 installed, they are used when running Bazel tests from Intellij, even if they're not the selected JDK.
