### ISSUE TITLE
Bazel build causes NullPointerException in plugin

### ISSUE THREAD

**Issue by konste** [bazelbuild/intellij#1339]
Open attached minimalistic project and select Bazel->Compile project. As the result we get ```java.lang.NullPointerException
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:260)
	at com.google.idea.blaze.base.sync.sharding.BlazeBuildTargetSharder.expandAndShardTargets(BlazeBuildTargetSharder.java:133)
	at com.google.idea.blaze.base.actions.BlazeBuildService$1.execute(BlazeBuildService.java:181)
	at com.google.idea.blaze.base.actions.BlazeBuildService$1.execute(BlazeBuildService.java:155)
	at com.google.idea.blaze.base.scope.ScopedTask.lambda$compute$0(ScopedTask.java:42)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
	at com.google.idea.blaze.base.scope.ScopedTask.compute(ScopedTask.java:38)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:185)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)```
Bazel version 1.1.0
IntelliJ version 2019.2.4
Plugin version 2019.10.14
Minimalistic repro project:
[chat-app.zip](https://github.com/bazelbuild/intellij/files/3799728/chat-app.zip)

**Comment by konste** [comment]
Additional problem with the same repro: Plugin generates Bazel commands like `D:\BuildTools\bazel.exe query --tool_tag=ijwb:IDEA:ultimate --output=label_kind --keep_going "attr(\"tags\", \"^((?!manual).)*$\", //...:all - //bazel-bin/...:all - //bazel-genfiles/...:all - //bazel-out/...:all - //bazel-testlogs/...:all - //bazel-chat-app/...:all - //.ijwb/...:all)" --` which fail at execution with the errors:

**Comment by brendandouglas** [comment]
Thanks, fixing that first bug upstream.

For the second, that might be specific to Windows (which we don't support). Those errors are expected, but they are ignored if bazel returns an exit code of 3, which it does on Linux (https://docs.bazel.build/versions/master/guide.html#what-exit-code-will-i-get).

Could you check what exit code you get when you run that command on Windows?

**Comment by konste** [comment]
I have run that command from the command line and indeed exit code is 3, but still when it is run from IntelliJ it shows "Make failed" after it. Excerpt from the idea.log attached:
[idea.log](https://github.com/bazelbuild/intellij/files/3805500/idea.log)

I wonder why the command line even includes all those Bazel output folders (symlinks) into scanning. They are not supposed to have any targets, aren't they?

**Comment by brendandouglas** [comment]
I see, thanks. The 'make failed' message comes from the NPE, not the (ignored) blaze query errors.

**Comment by brendandouglas** [comment]
Actually, ignore that, the symlink folders are being explicitly excluded from the query (which they should be). The actual problem is some syntax error:

2019-11-04 10:32:40,379 [333492229]   INFO - QueryDirectoryToTargetProvider - ERROR: Error while parsing 'attr(tags, ^((?!manual).)*$, //...:all - //bazel-bin/...:all - //bazel-genfiles/...:all - //bazel-out/...:all - //bazel-testlogs/...:all - //bazel-chat-app/...:all - //.ijwb/...:all)': syntax error at '^ ( ('

**Comment by brendandouglas** [comment]
I think this is specific to Windows, since we haven't seen any similar problems with blaze query on linux. We don't have the bandwidth to support Windows or investigate issues with Windows at the moment unfortunately.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
