### ISSUE TITLE
Cannot run program "glogin" exception

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#1341]
Running a plugin built from [source](https://github.com/bazelbuild/intellij/commit/2fb993316fc7708d6a02b75f4a90d81393fc5be2) causes the following exception in the log: 
```java
java.io.IOException: Cannot run program "glogin" (in directory "/"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.google.idea.blaze.base.async.process.ExternalTask$ExternalTaskImpl.invokeCommand(ExternalTask.java:250)
	at com.google.idea.blaze.base.async.process.ExternalTask$ExternalTaskImpl.lambda$run$0(ExternalTask.java:179)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
	at com.google.idea.blaze.base.async.process.ExternalTask$ExternalTaskImpl.run(ExternalTask.java:172)
	at com.google.idea.blaze.base.actions.FileGitHubIssueAction.lambda$static$0(FileGitHubIssueAction.java:65)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:67)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at com.google.idea.blaze.base.actions.FileGitHubIssueAction.updateForBlazeProject(FileGitHubIssueAction.java:74)
	at com.google.idea.blaze.base.actions.BlazeProjectAction.update(BlazeProjectAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:378)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$null$1(ActionUpdater.java:78)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$2(ActionUpdater.java:79)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:364)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:231)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$19(ActionUpdater.java:215)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1609)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:215)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:139)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:131)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupWithTimeout$11(ActionUpdater.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.withTimeout(ProgressIndicatorUtils.java:260)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroupWithTimeout(ActionUpdater.java:147)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:66)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:312)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:270)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
	at javax.swing.JMenu.setSelected(JMenu.java:305)
	at com.apple.laf.ScreenMenu$2.run(ScreenMenu.java:135)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:301)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 65 
```

**Comment by ittaiz** [comment]
Looking through the javadoc it seems this is "ok":
```
/**
   * A rough heuristic to detect if the machine is a Google-corp machine by executing 'glogin
   * -version'. This is wrapped in a LazyValue because it's called from the action update function
   * that runs twice a second, so it cannot be an expensive computation.
   */
```
Given the code only needs the exit code maybe we can add `.redirectStderr(false)` (or give a no-op stdout/stderr) and so the log will be cleaner?
This helps us support our users when they report issues in IJ plugin.

**Comment by chaoren** [comment]
It should be using the null stream by default.

**Comment by chaoren** [comment]
redirectErrorStream should also be false by default.

**Comment by ittaiz** [comment]
You're right it should but this is what we're getting.
I'll debug it more and update.

**Comment by brt-alexei** [comment]
These messages are all over idea.log and it is confusing.

**Comment by rdesgroppes** [comment]
Same here.

**Comment by vasiliy-bout** [comment]
Exception still gets logged, plugin version `2022.08.09.0.1-api-version-221`

**Comment by odisseus** [comment]
The fact that this issue, easy to fix as it is, remains unaddressed for such a long time, makes it look as if Bazel still was a Google-only tool, which I hope isn't the case anymore.

**Comment by odisseus** [comment]
I just realized that redirecting or discarding the error stream won't fix the issue. On a machine without a `glogin` command, the exception ("No such file or directory") will be thrown before there even is an error stream, and logged by [`ExternalTaskImpl`](https://github.com/bazelbuild/intellij/blob/d5d0ea12e48052555feb23b8d1913a93802f7f5c/base/src/com/google/idea/blaze/base/async/process/ExternalTask.java#L309).

**Comment by mai93** [comment]
Fixed with https://github.com/bazelbuild/intellij/pull/4239
