### ISSUE TITLE
Sync fails to build IDE files because the `set` constructor for depsets is deprecated.

### ISSUE THREAD

**Issue by aleb** [bazelbuild/intellij#136]
Using CLion 2017.1.3 with the Bazel plugin 2017.08.01.0.1, and Bazel 0.6.0-homebrew.
I import the sample [clion-bazel](https://github.com/danieldanciu/clion-bazel) project, click Sync, and I see it fails because "The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false."

```
Syncing project...
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:CLion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --


Command: git diff --name-status --no-renames 05ea74a8f7be2ee3e1271f0019f30ee1a705f629


Extracting Bazel installation...
..........................................................................
____Loading package: @bazel_tools//tools/jdk
____Loading package: @local_config_xcode//
____Loading package: @local_jdk//
____Loading package: @local_config_cc//
Computing VCS working set...
Your working set is empty
Sync targets from project view:
  //...:all

Building IDE info files...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:CLion --keep_going --experimental_build_event_binary_file=/var/folders/yd/nc6_vq355v352hm7_q86gfmw0000gn/T/intellij-bep-991831ee-addb-40da-9115-a821077d3e35 --noexperimental_build_event_binary_file_path_conversion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@intellij_aspect//:intellij_info.bzl%intellij_info_aspect --override_repository=intellij_aspect=/Users/ab/Library/Application Support/CLion2017.1/clwb/aspect --output_groups=intellij-info-cpp,intellij-info-generic -- //...:all


____Loading package: 
____Loading complete.  Analyzing...
____Loading package: @bazel_tools//platforms
____Loading package: @intellij_aspect//
____Loading package: @bazel_tools//tools/launcher
____Loading package: @bazel_tools//third_party/java/jdk/langtools
____Loading package: @bazel_tools//src
____Loading package: @bazel_tools//src/tools/launcher/util
ERROR: /private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/local_config_cc/BUILD:33:1: in @intellij_aspect//:intellij_info.bzl%intellij_info_aspect aspect on cc_toolchain rule @local_config_cc//:cc-compiler-darwin: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/local_config_cc/BUILD", line 33
		@intellij_aspect//:intellij_info.bzl%intellij_info_aspect(...)
	File "/private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/intellij_aspect/intellij_info.bzl", line 18, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/intellij_aspect/intellij_info_impl.bzl", line 628, in intellij_info_aspect_impl
		list(set(export_deps))
	File "/private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/intellij_aspect/intellij_info_impl.bzl", line 628, in list
		set(export_deps)
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false.
____Found 1 target...
____Building...
____[0 / 1] BazelWorkspaceStatusAction stable-status.txt
Target //:hello up-to-date (nothing to build)
ERROR: command succeeded, but not all targets were analyzed.
____Elapsed time: 32.431s, Critical Path: 0.02s
____Waiting for build event protocol upload: 0s
Total rules: 0, new/changed: 0, removed: 3
Reading IDE info result...
Loaded 0 aspect files, total size 0kB
Building IDE resolve files...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:CLion --keep_going --experimental_build_event_binary_file=/var/folders/yd/nc6_vq355v352hm7_q86gfmw0000gn/T/intellij-bep-217d4d35-2777-45c7-bbba-a09dd52cbe4a --noexperimental_build_event_binary_file_path_conversion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@intellij_aspect//:intellij_info.bzl%intellij_info_aspect --override_repository=intellij_aspect=/Users/ab/Library/Application Support/CLion2017.1/clwb/aspect --output_groups=intellij-resolve-cpp -- //...:all


____Loading package: @local_config_xcode//
____Loading complete.  Analyzing...
ERROR: /private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/local_config_cc/BUILD:33:1: in @intellij_aspect//:intellij_info.bzl%intellij_info_aspect aspect on cc_toolchain rule @local_config_cc//:cc-compiler-darwin: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/local_config_cc/BUILD", line 33
		@intellij_aspect//:intellij_info.bzl%intellij_info_aspect(...)
	File "/private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/intellij_aspect/intellij_info.bzl", line 18, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/intellij_aspect/intellij_info_impl.bzl", line 628, in intellij_info_aspect_impl
		list(set(export_deps))
	File "/private/var/tmp/_bazel_ab/fc7ea4530f9bdd4f1119eb797c96880e/external/intellij_aspect/intellij_info_impl.bzl", line 628, in list
		set(export_deps)
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false.
____Found 1 target...
____Building...
Target //:hello up-to-date (nothing to build)
ERROR: command succeeded, but not all targets were analyzed.
____Elapsed time: 25.473s, Critical Path: 0.00s
Prefetching genfiles...
Prefetching files...
Computing directory structure...
Committing project structure...
Workspace has 0 libraries
Workspace has 2 modules
Sync was successful, but there were BUILD file errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Blaze > Sync > Expand Sync to Working Set' and try again.
Updating in-memory state...

[...]
```

Where can I pass the `--incompatible_disallow_set_constructor=false` to workaround the bug?

**Comment by brendandouglas** [comment]
This is fixed in the latest plugin release, though you'll need to update to CLion 2017.2 to pick it up (version compatibility listed here: https://plugins.jetbrains.com/plugin/9554-bazel)
