### ISSUE TITLE
LinkageError error "loader constraint violation"

### ISSUE THREAD

**Issue by joprice** [bazelbuild/intellij#1433]
I'm seeing the following error on Intellij 2019.2.4:

```java.lang.LinkageError: loader constraint violation: loader com.intellij.ide.plugins.cl.PluginClassLoader @555e1ef3 wants to load abstract class scala.Option. A different abstract class with the same name was previously loaded by com.intellij.ide.plugins.cl.PluginClassLoader @25ad5845. (scala.Option is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @25ad5845, parent loader 'bootstrap')
	at com.google.idea.sdkcompat.scala.TestConfigurationUtilCompat.getStaticTestName(TestConfigurationUtilCompat.java:29)
	at com.google.idea.blaze.scala.run.Specs2Utils.getSpecs2TestName(Specs2Utils.java:68)
	at com.google.idea.blaze.scala.run.Specs2Utils.getSpecs2ScopedTestName(Specs2Utils.java:74)
	at com.google.idea.blaze.scala.run.producers.BlazeScalaTestRunLineMarkerContributor.getSpecs2TestUrl(BlazeScalaTestRunLineMarkerContributor.java:129)
	at com.google.idea.blaze.scala.run.producers.BlazeScalaTestRunLineMarkerContributor.getTestUrl(BlazeScalaTestRunLineMarkerContributor.java:92)
	at com.google.idea.blaze.scala.run.producers.BlazeScalaTestRunLineMarkerContributor.getInfo(BlazeScalaTestRunLineMarkerContributor.java:79)
	at com.google.idea.blaze.scala.run.producers.BlazeScalaTestRunLineMarkerContributor.getInfo(BlazeScalaTestRunLineMarkerContributor.java:66)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:49)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:171)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)```

**Comment by joprice** [comment]
I hadn't isolated the situation that produces this originally, but I just noticed that I get it when trying to jump to the source of classes from the scala standard library. I see the error, followed by the decompiled code, whereas other dependencies show the source. I am using rules_jvm_external with `fetch_sources = True` for external dependencies, and io_bazel_rules_scala to pull in scala.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
