### ISSUE TITLE
2019.3 breaks debug ability with Scala Rules

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/intellij#1490]
#### Description of the issue. Please be specific.
Running the debugger with a scala project breaks in this exception:

```
Building debug binary
Command: /usr/local/bin/bazel build --tool_tag=ijwb:IDEA:ultimate --curses=no --color=yes --progress_in_terminal_title=no --aspects=@intellij_aspect//:java_classpath.bzl%java_classpath_aspect "--override_repository=intellij_aspect=/Users/ouch/Library/Application Support/IntelliJIdea2019.3/ijwb/aspect" --output_groups=runtime_classpath --build_event_binary_file=/var/folders/wr/_78r4nnd7xqf4ql76jckknyr0000gn/T/intellij-bep-6d719488-1100-4918-91aa-fae63f30b24b --nobuild_event_binary_file_path_conversion -- //project/server:server

INFO: Invocation ID: 46b176b6-6d83-4b37-8ec5-c21fa5b1a471
Loading: 
Loading: 0 packages loaded
Analyzing: target //project/server:server (0 packages loaded, 0 targets configured)
ERROR: /Users/ouch/code/project/BUILD.bazel:5:1: in @intellij_aspect//:java_classpath.bzl%java_classpath_aspect aspect on scala_binary rule //project/server:server:
Traceback (most recent call last):
	File "/Users/ouch/code/project/BUILD.bazel", line 5
		@intellij_aspect//:java_classpath.bzl%java_classpath_aspect(...)
	File "/private/var/tmp/_bazel_ouch/e16b5894b0f107d6a2b892b63b2486a9/external/intellij_aspect/java_classpath.bzl", line 16, in _runtime_classpath_impl
		struct(<1 more arguments>)
	File "/private/var/tmp/_bazel_ouch/e16b5894b0f107d6a2b892b63b2486a9/external/intellij_aspect/java_classpath.bzl", line 17, in struct
		_get_runtime_jars(target)
	File "/private/var/tmp/_bazel_ouch/e16b5894b0f107d6a2b892b63b2486a9/external/intellij_aspect/java_classpath.bzl", line 22, in _get_runtime_jars
		target[JavaInfo].compilation_info.runtime_classpath
object of type 'NoneType' has no field 'runtime_classpath'
ERROR: Analysis of aspect '@intellij_aspect//:java_classpath.bzl%java_classpath_aspect of //project/server:server' failed; build aborted: Analysis of target '//project/server:server' failed; build aborted
INFO: Elapsed time: 1.393s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

Run a debugger on a `scala_binary`

#### Version information
IdeaUltimate: 2019.3.1
Platform: Mac OS X 10.14.6
Bazel plugin: 2019.10.21.0.0-6823f76
Bazel: 1.2.1

**Comment by KaoruDev** [comment]
Appears to happen on `2.0.0` as well

**Comment by cromwellian** [comment]
Are you using bazelisk? I ran into this problem with bazelisk and IJ, but not with bazel 1.2.1 run directly.

**Comment by KaoruDev** [comment]
I believe this: https://github.com/bazelbuild/intellij/pull/1347 which was thought to be merged but wasn't is now merged haha so that should resolve this issue, I haven't had a chance to confirm it yet.

**Comment by KaoruDev** [comment]
fixed via: https://github.com/bazelbuild/intellij/pull/1347#issuecomment-573058451
