### ISSUE TITLE
Cannot share data context between Swing events

### ISSUE THREAD

**Issue by jlowenz** [bazelbuild/intellij#1606]
Context: Left my computer, locked the screen, and came back to this stacktrace. Working on a large Bazel project. 

**Bazel plugin version**: 2020.01.14.0.1 
**CLion 2019.2.5**
Build #CL-192.7142.39, built on October 29, 2019
Licensed to ...

Runtime version: 11.0.5+10-post-Ubuntu-0ubuntu1.118.04 amd64
VM: OpenJDK 64-Bit Server VM by Private Build
Linux 5.3.0-26-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 8179M
Cores: 24
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=382
Non-Bundled Plugins: com.jetbrains.ChooseRuntime, com.google.idea.bazel.clwb

Stacktrace:
```
java.lang.Throwable: cannot share data context between Swing events; initial event count = 17284853; current event count = 17284876
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:341)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:53)
	at com.google.idea.blaze.cpp.navigation.DelegatingSwitchToHeaderOrSourceProvider.getItems(DelegatingSwitchToHeaderOrSourceProvider.java:89)
	at com.intellij.codeInsight.navigation.NavigationUtil.collectRelatedItems(NavigationUtil.java:487)
	at com.intellij.ide.actions.GotoRelatedSymbolAction.actionPerformed(GotoRelatedSymbolAction.java:62)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:508)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:801)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
