### ISSUE TITLE
Aspect fails consuming JavaInfo without srcjar.

### ISSUE THREAD

**Issue by corbinrsmith** [bazelbuild/intellij#1616]
The Intellij aspect expects srcjar to always be populated if it exists on a provider.

**Version:** 
2019.10.21.0.0-6823f76

**Reproduce:** 
Checkout https://github.com/bazelbuild/rules_kotlin/tree/legacy-1.3.0-rc4
Import .bazelproject
Sync.

**Error:**
```
Invalid text format, expected a struct, a dict, a string, a bool, or an int but got a NoneType for list element in struct field 'source_jars'
ERROR: /private/var/tmp/_bazel_corbin/114e49ea5d3cfb003df75c89cfe9d5ed/external/com_github_jetbrains_kotlin/BUILD.bazel:39:5: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on kt_jvm_import rule @com_github_jetbrains_kotlin//:kotlin-annotation-processing: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_corbin/114e49ea5d3cfb003df75c89cfe9d5ed/external/com_github_jetbrains_kotlin/BUILD.bazel", line 39
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/private/var/tmp/_bazel_corbin/114e49ea5d3cfb003df75c89cfe9d5ed/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(<3 more arguments>)
	File "/private/var/tmp/_bazel_corbin/114e49ea5d3cfb003df75c89cfe9d5ed/external/intellij_aspect/intellij_info_impl.bzl", line 933, in intellij_info_aspect_impl
		ctx.actions.write(ide_info_file, <1 more arguments>)
	File "/private/var/tmp/_bazel_corbin/114e49ea5d3cfb003df75c89cfe9d5ed/external/intellij_aspect/intellij_info_impl.bzl", line 933, in ctx.actions.write
		info.to_proto()
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
