### ISSUE TITLE
Sync failed due to NPE on Android project structure syncer

### ISSUE THREAD

**Issue by mhadidg** [bazelbuild/intellij#1631]
I have a problem importing [android-kerberos-authenticator](https://github.com/google/android-kerberos-authenticator) in Android Studio, yet I can build the project with the bazel command-line tool without any problem.

### Environment 
Bazel v1.2.1
Bazel Plugin v2019.10.14.0.0
Android Studio v3.5.3.0

### Step to Reproduce:
- clone [android-kerberos-authenticator](https://github.com/google/android-kerberos-authenticator) project locally
- open the WORKSPACE file and search for android_sdk_repository 
  - change the **path** to where your Android SDK is installed
  - change the **build_tools_version** from 27.0.3 to 29.0.3
- import the project in Android Studio with _Import Bazel Project_

### IDE Log File
[idea.log](https://github.com/bazelbuild/intellij/files/4172649/bazel-intellij.log)

### Stack Trace
```java
java.lang.NullPointerException
	at com.google.idea.blaze.android.resources.BlazeLightResourceClassService$Builder.addStubPackages(BlazeLightResourceClassService.java:78)
	at com.google.idea.blaze.android.resources.BlazeLightResourceClassService$Builder.addRClass(BlazeLightResourceClassService.java:68)
	at com.google.idea.blaze.android.sync.projectstructure.BlazeAndroidProjectStructureSyncer.updateInMemoryState(BlazeAndroidProjectStructureSyncer.java:411)
	at com.google.idea.blaze.android.sync.projectstructure.BlazeAndroidProjectStructureSyncer.updateInMemoryState(BlazeAndroidProjectStructureSyncer.java:336)
	at com.google.idea.blaze.android.sync.BlazeAndroidSyncPlugin.updateInMemoryState(BlazeAndroidSyncPlugin.java:227)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$updateInMemoryState$10(SyncPhaseCoordinator.java:599)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:946)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$updateInMemoryState$11(SyncPhaseCoordinator.java:592)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.updateInMemoryState(SyncPhaseCoordinator.java:584)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.finishSync(SyncPhaseCoordinator.java:480)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.updateProjectAndFinishSync(SyncPhaseCoordinator.java:444)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:343)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:197)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:33)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:189)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mhadidg** [comment]
Restructuring the project following the traditional Android project structure resolves the issue.
