### ISSUE TITLE
Support CLion 2017.3

### ISSUE THREAD

**Issue by grefab** [bazelbuild/intellij#175]
After installing the plugin when restarting CLion I get the following error message:

```
Plugin 'com.google.idea.bazel.clwb' failed to initialize and will be disabled.  Please restart CLion.

java.lang.NoClassDefFoundError: com/jetbrains/cidr/modulemap/resolve/ModuleMapInitialBuildingActivity
    at com.google.idea.blaze.cpp.CidrSymbolBuilderSuppressor.<clinit>(CidrSymbolBuilderSuppressor.java:35)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:380)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:95)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:67)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.jetbrains.cidr.modulemap.resolve.ModuleMapInitialBuildingActivity PluginClassLoader[com.google.idea.bazel.clwb, 2017.11.06.0.5] com.intellij.ide.plugins.cl.PluginClassLoader@3f21793b
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 28 more
```

My CLion installation is as follows:
```
CLion 2017.3
Build #CL-173.3727.83, built on November 22, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

After confirming above message the plugin is diabled and next start of CLion works smoothly. However, plugin cannot be used.

**Comment by brendandouglas** [comment]
We haven't released a plugin compatible with 2017.3 yet. It will likely be another month or so before we do -- I'll update this issue when that happens.

**Comment by davidhopper2003** [comment]
I have encountered the same problem. Could you please accelerate the process of providing a plugin compatible with 2017.3? Thanks very much. 
```
Plugin 'com.google.idea.bazel.clwb' failed to initialize and will be disabled.  Please restart CLion.

java.lang.NoClassDefFoundError: com/jetbrains/cidr/modulemap/resolve/ModuleMapInitialBuildingActivity
    at com.google.idea.blaze.cpp.CidrSymbolBuilderSuppressor.<clinit>(CidrSymbolBuilderSuppressor.java:35)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:385)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.jetbrains.cidr.modulemap.resolve.ModuleMapInitialBuildingActivity PluginClassLoader[com.google.idea.bazel.clwb, 2017.12.04.0.2] com.intellij.ide.plugins.cl.PluginClassLoader@503dfb1f
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 28 more
```

**Comment by rctoris** [comment]
Any updates on a timeline for this?

**Comment by plumpy** [comment]
It should happen in roughly two weeks, with the 2018.01.16 release.

**Comment by rctoris** [comment]
Great, thanks!!

**Comment by rlenglet** [comment]
Why has this ticket been closed? The Bazel plugin works neither on 2017.3.3 nor on 2018.1 EAP. There is no downloadable version of CLion for which this plugin works.

**Comment by grefab** [comment]
Works now for me for CLion 2017.3.3 under Ubuntu. Windows support is buggy, though. 2018.1 EAP letzt plugin crash like before.

**Comment by rlenglet** [comment]
It doesn't work on Mac.

**Comment by rlenglet** [comment]
Upgrading to 2018.01.29.0.2 worked. My bad. Nevermind.

**Comment by brendandouglas** [comment]
For future reference, you can see the list of plugin versions and associated IDE version on the JetBrains [plugin repository](https://plugins.jetbrains.com/plugin/9554-bazel).
