### ISSUE TITLE
"Executor with context action id: "RunClass" was already registered!" when open Bazel menu in Idea CE

### ISSUE THREAD

**Issue by ar4development** [bazelbuild/intellij#1982]
IDEA info:
----------------------------------------------------------
IntelliJ IDEA 2020.1.3 (Community Edition)
Build #IC-201.8538.31, built on July 7, 2020
Runtime version: 11.0.7+10-b765.64 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.3.0-62-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 962M
Cores: 12
Non-Bundled Plugins: org.jetbrains.kotlin, gherkin, cucumber-java, org.intellij.scala, com.google.idea.bazel.ijwb, zielu.gittoolbox
Current Desktop: ubuntu:GNOME

Plugin info
----------------------------------------------------------
2020.06.25.0.3

Steps
----------------------------------------------------------
1. Install plugin
2. Restart IDE
3. Open Bazel menu item in top menu

EXPECTED: Menu is opened
OBSERVED: Menu item disappears. Following exception is logged:

> java.lang.Throwable: Executor with context action id: "RunClass" was already registered!
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
> 	at com.intellij.execution.ExecutorRegistryImpl.initExecutorActions(ExecutorRegistryImpl.java:80)
> 	at com.intellij.execution.ExecutorRegistryImpl.init(ExecutorRegistryImpl.java:155)
> 	at com.intellij.execution.ExecutorRegistryImpl.access$000(ExecutorRegistryImpl.java:43)
> 	at com.intellij.execution.ExecutorRegistryImpl$ExecutorRegistryActionConfigurationTuner.customize(ExecutorRegistryImpl.java:72)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$new$0(ActionManagerImpl.java:160)
> 	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:21)
> 	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:160)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:660)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:54)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:411)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:394)
> 	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:28)
> 	at com.google.idea.common.actions.ReplaceActionHelper.conditionallyHideAction(ReplaceActionHelper.java:31)
> 	at com.google.idea.blaze.base.plugin.BlazeSpecificInitializer.hideMakeActions(BlazeSpecificInitializer.java:47)
> 	at com.google.idea.blaze.base.plugin.BlazeSpecificInitializer.access$000(BlazeSpecificInitializer.java:28)
> 	at com.google.idea.blaze.base.plugin.BlazeSpecificInitializer$1.appStarting(BlazeSpecificInitializer.java:39)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:546)
> 	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
> 	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
> 	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:397)
> 	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
> 	at com.sun.proxy.$Proxy32.appStarting(Unknown Source)
> 	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:124)
> 	at com.intellij.idea.ApplicationLoader$startApp$8.run(ApplicationLoader.kt:222)
> 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
> 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
> 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by hanikesn** [comment]
I get the same crash in the Ultimate Edition and v2020.07.13

**Comment by brendandouglas** [comment]
@hanikesn this should have been fixed by v2020.07.13 (https://github.com/bazelbuild/intellij/commit/b0efcb74b2a95178622beacdd28046f212bc8263) -- could you paste your stack trace here?

**Comment by hanikesn** [comment]
Can confirm it's working now. I just had to reimport the project with new version.

**Comment by Sxxjava** [comment]
I get the same crash in the Ultimate Edition and 2022.2.3

**Comment by fengzengfly** [comment]
java.lang.Throwable: Executor with context action id: "RunClass" was already registered!
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.execution.ExecutorRegistryImpl.initExecutorActions(ExecutorRegistryImpl.java:100)
	at com.intellij.execution.ExecutorRegistryImpl.init(ExecutorRegistryImpl.java:278)
	at com.intellij.execution.ExecutorRegistryImpl$ExecutorRegistryActionConfigurationTuner.customize(ExecutorRegistryImpl.java:92)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$new$0(ActionManagerImpl.java:141)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:141)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:890)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:609)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:29)
	at com.zeroturnaround.javarebel.idea.plugin.ui.IntellijNewUISupport.doInitActions(IntellijNewUISupport.java:43)
	at com.zeroturnaround.javarebel.idea.plugin.ui.IntellijNewUISupport.access$000(IntellijNewUISupport.java:15)
	at com.zeroturnaround.javarebel.idea.plugin.ui.IntellijNewUISupport$1.invoke(IntellijNewUISupport.java:29)
	at jdk.proxy3/jdk.proxy3.$Proxy37.appFrameCreated(Unknown Source)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:629)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy2/jdk.proxy2.$Proxy42.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:100)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:80)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt:185)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
