### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/intellij#200]
java.lang.IllegalStateException: This function should be called while holding treeLock
	at java.awt.Component.checkTreeLock(Component.java:1209)
	at java.awt.Container.validateTree(Container.java:1690)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$900(ActionMenu.java:55)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuItemSynchronizer.propertyChange(ActionMenu.java:341)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
	at com.intellij.openapi.actionSystem.Presentation.firePropertyChange(Presentation.java:300)
	at com.intellij.openapi.actionSystem.Presentation.setVisible(Presentation.java:268)
	at com.intellij.openapi.actionSystem.Presentation.setEnabledAndVisible(Presentation.java:295)
	at com.google.idea.blaze.base.actions.BlazeMenuGroup.update(BlazeMenuGroup.java:30)
	at com.intellij.openapi.wm.impl.IdeMenuBar.a(IdeMenuBar.java:422)
	at com.intellij.openapi.wm.impl.IdeMenuBar.updateMenuActions(IdeMenuBar.java:332)
	at com.intellij.openapi.wm.impl.IdeMenuBar$MyTimerListener.run(IdeMenuBar.java:482)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1396)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1386)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by brendandouglas** [comment]
Closing, as this appears to be an upstream bug.

**Comment by solomatov** [comment]
It's not an upstream bug. You are using IntelliJ API incorrectly. See this line:

at com.google.idea.blaze.base.actions.BlazeMenuGroup.update(BlazeMenuGroup.java:30)

I have experience developing with IntelliJ platform (I work for JetBrains), and if you open this repository for pull requests, I would be eager to help.

**Comment by chaoren** [comment]
Fixed upstream bug with https://github.com/JetBrains/intellij-community/pull/705.
