### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.idea.blaze.google3.objfs.RemoteOutputStateProtoConverter 

### ISSUE THREAD

**Issue by mskonovalov** [bazelbuild/intellij#2014]
Hi,

```
com.intellij.diagnostic.PluginException: com.google.idea.blaze.google3.objfs.RemoteOutputStateProtoConverter PluginClassLoader[PluginDescriptor(name=Bazel, id=com.google.idea.bazel.ijwb, path=/Users/kms/Library/Application Support/JetBrains/IntelliJIdea2020.2/plugins/ijwb, version=2030.07.28.0.0)] com.intellij.ide.plugins.cl.PluginClassLoader@3976f098 [Plugin: com.google.idea.bazel.ijwb]
	at com.intellij.serviceContainer.ComponentManagerImplKt.createPluginExceptionIfNeeded(ComponentManagerImpl.kt:956)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$createPluginExceptionIfNeeded(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:733)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:39)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:69)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:480)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:421)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:263)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:38)
	at com.google.idea.blaze.base.filecache.ArtifactStateProtoConverter.fromProto(ArtifactStateProtoConverter.java:40)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceState.fromProto(BlazeIdeInterfaceState.java:63)
	at com.google.idea.blaze.base.model.ProjectTargetData.fromProto(ProjectTargetData.java:51)
	at com.google.idea.blaze.base.model.BlazeProjectData.parseTargetData(BlazeProjectData.java:87)
	at com.google.idea.blaze.base.model.BlazeProjectData.fromProto(BlazeProjectData.java:74)
	at com.google.idea.blaze.base.model.BlazeProjectData.loadFromDisk(BlazeProjectData.java:151)
	at com.google.idea.blaze.base.sync.data.BlazeProjectDataManagerImpl.loadProject(BlazeProjectDataManagerImpl.java:85)
	at com.google.idea.blaze.base.sync.data.BlazeProjectDataManagerImpl.loadProjectRoot(BlazeProjectDataManagerImpl.java:71)
	at com.google.idea.blaze.base.prefetch.PrefetchProjectInitializer.getBlazeProjectData(PrefetchProjectInitializer.java:101)
	at com.google.idea.blaze.base.prefetch.PrefetchProjectInitializer.lambda$prefetchProjectFiles$1(PrefetchProjectInitializer.java:81)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:160)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:143)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.google.idea.blaze.google3.objfs.RemoteOutputStateProtoConverter PluginClassLoader[PluginDescriptor(name=Bazel, id=com.google.idea.bazel.ijwb, path=/Users/kms/Library/Application Support/JetBrains/IntelliJIdea2020.2/plugins/ijwb, version=2030.07.28.0.0)] com.intellij.ide.plugins.cl.PluginClassLoader@3976f098
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:74)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:36)
	... 26 more
```

Seems was introduced here https://github.com/bazelbuild/intellij/commit/1af8d0a996611d8e9b295c8b6cd7ca94dcffc630#diff-6e0aca904f170600d0cf8be827594fd8R520

**Comment by brendandouglas** [comment]
Thanks for letting us know, I've fixed this upstream, and it will land in the release after next.
