### ISSUE TITLE
[Android] Native debugging in Android Studio 4.0 is broken

### ISSUE THREAD

**Issue by Lizz0y** [bazelbuild/intellij#2028]
Android Studio 4.0 RC1

I can debug java, but when i choose dual or native only, it broken, the error as below:

m.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 8,4,Idea Thread Group] 1688058739
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 957085981
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:920)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:346)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:153)
	at com.android.tools.ndk.run.editor.ProcessNameReader.readGlobalProcessNames(ProcessNameReader.java:60)
	at com.android.tools.ndk.run.editor.ProcessNameReader.hasGlobalProcess(ProcessNameReader.java:44)
	at com.android.tools.ndk.run.editor.NativeAndroidDebugger.attachToClient(NativeAndroidDebugger.java:170)
	at org.jetbrains.android.actions.AndroidConnectDebuggerAction.closeOldSessionAndRun(AndroidConnectDebuggerAction.java:52)
	at org.jetbrains.android.actions.AndroidConnectDebuggerAction.lambda$actionPerformed$0(AndroidConnectDebuggerAction.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mai93** [comment]
Hello @Lizz0y is this problem reproducible with newer version of the plugin?

**Comment by mai93** [comment]
Closing this issue, if you are still seeing it with newer versions of the plugin, please reopen with clear steps to reproduce it.
