### ISSUE TITLE
UI become unresponsive during sync

### ISSUE THREAD

**Issue by zack-sampson** [bazelbuild/intellij#2056]
Hey,

I've regularly noticed that my IDE will seize up for minutes at a time during sync. I caught a stack trace here:

```

"AWT-EventQueue-0 [WriteAccessToken]" #27 prio=6 os_prio=31 cpu=104476.14ms elapsed=2514.66s tid=0x00007fd69fa90800 nid=0x1030b runnable  [0x000070000f92a000]
   java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.canonicalize0(java.base@11.0.7/Native Method)
	at java.io.UnixFileSystem.canonicalize(java.base@11.0.7/UnixFileSystem.java:178)
	at java.io.File.getCanonicalPath(java.base@11.0.7/File.java:620)
	at com.intellij.openapi.util.io.FileSystemUtil$JnaUnixMediatorImpl.resolveSymLink(FileSystemUtil.java:336)
	at com.intellij.openapi.util.io.FileSystemUtil.resolveSymLink(FileSystemUtil.java:135)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.resolveSymLink(LocalFileSystemBase.java:125)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getChildData(PersistentFSImpl.java:1391)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.persistAllChildren(PersistentFSImpl.java:175)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.listAll(PersistentFSImpl.java:202)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.loadAllChildren(VirtualDirectoryImpl.java:363)
	- locked <0x0000000781fb2668> (a com.intellij.openapi.vfs.newvfs.impl.VfsData$DirectoryData)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.getChildren(VirtualDirectoryImpl.java:355)
	at com.intellij.history.integration.IdeaGateway.loadAndIterateChildren(IdeaGateway.java:244)
	at com.intellij.history.integration.LocalHistoryEventDispatcher$1.getChildrenIterable(LocalHistoryEventDispatcher.java:112)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:313)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:328)
	at com.intellij.history.integration.LocalHistoryEventDispatcher.createRecursively(LocalHistoryEventDispatcher.java:98)
	at com.intellij.history.integration.LocalHistoryEventDispatcher.fileCreated(LocalHistoryEventDispatcher.java:93)
	at com.intellij.history.integration.LocalHistoryEventDispatcher.handleAfterEvent(LocalHistoryEventDispatcher.java:217)
	at com.intellij.history.integration.LocalHistoryEventDispatcher.lambda$after$1(LocalHistoryEventDispatcher.java:207)
	at com.intellij.history.integration.LocalHistoryEventDispatcher$$Lambda$3051/0x0000000801cb0840.run(Unknown Source)
	at com.intellij.history.integration.IdeaGateway.runWithVfsEventsDispatchContext(IdeaGateway.java:138)
	at com.intellij.history.integration.LocalHistoryEventDispatcher.after(LocalHistoryEventDispatcher.java:205)
	at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.7/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.7/Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:541)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
	at com.intellij.util.messages.impl.MessageBusImpl$$Lambda$369/0x000000080042e040.invoke(Unknown Source)
	at com.sun.proxy.$Proxy144.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:991)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.processEvents(AsyncEventSupport.java:124)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEventsInWriteAction(RefreshSessionImpl.java:190)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.lambda$fireEvents$1(RefreshSessionImpl.java:177)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl$$Lambda$3018/0x0000000801c8c840.run(Unknown Source)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:177)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.lambda$runAsyncListeners$6(RefreshQueueImpl.java:122)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$$Lambda$948/0x0000000800ad4440.run(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$$Lambda$936/0x0000000800ad7840.accept(Unknown Source)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:539)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission$$Lambda$949/0x0000000800af0440.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$340/0x00000008003dec40.run(Unknown Source)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.7/InvocationEvent.java:313)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.7/EventQueue.java:776)
	at java.awt.EventQueue$4.run(java.desktop@11.0.7/EventQueue.java:727)
	at java.awt.EventQueue$4.run(java.desktop@11.0.7/EventQueue.java:721)
	at java.security.AccessController.doPrivileged(java.base@11.0.7/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.7/ProtectionDomain.java:85)
	at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.7/EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.ide.IdeEventQueue$$Lambda$676/0x0000000800733c40.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.ide.IdeEventQueue$$Lambda$674/0x0000000800734840.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.7/EventDispatchThread.java:203)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.7/EventDispatchThread.java:124)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.7/EventDispatchThread.java:113)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.7/EventDispatchThread.java:109)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.7/EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.run(java.desktop@11.0.7/EventDispatchThread.java:90)
```
Looks like some sort of heavy filesystem exploration is going on, but presumably because it's on the UI event thread it totally locks up the UI.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
