### ISSUE TITLE
Clicking stop sync leaves sync button & menu items disabled

### ISSUE THREAD

**Issue by BrentDouglas** [bazelbuild/intellij#208]
Since upgrading to 2017.11.20.0.4 (I'm not sure which version I was on before) clicking the Stop sync button during a sync does not enable the Sync button any more. It, and all sync related context menu items, remain greyed out until I restart IDEA.

**Comment by woodenflute** [comment]
Had the same issue

**Comment by brendandouglas** [comment]
I haven't been able to reproduce this. Which IDE are you using (and on which environment)?

**Comment by woodenflute** [comment]
I'm using IntelliJ U - 2017.3.1 with Bazel version 2017.11.06.0.5
So yeah, I should probably update, but need to finish a few things first.

**Comment by BrentDouglas** [comment]
@brendandouglas IDEA reports this:
IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.27, built on December 25, 2017
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

The bazel plugin version is Version: 2018.01.02.0.1

I think I have seen it on earlier versions of both IDEA & the plugin as well. I just tested it again however and I can still reproduce it, this time it logged an error:

```
<null> : Control-flow exceptions (like ProcessCanceledException) should never be logged
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:118)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:162)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:257)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:189)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:163)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:113)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.a(AbstractProgressIndicatorBase.java:142)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:133)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:120)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:51)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:39)
	at com.google.idea.blaze.base.logging.EventLoggingService.getInstance(EventLoggingService.java:31)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:255)
	... 20 more
```

**Comment by BrentDouglas** [comment]
I just upgraded to:
IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.25, built on January 15, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

With the same exception

**Comment by brendandouglas** [comment]
Thanks for the details. I can't reproduce this (at least not in 2017.2), but it's clear from the exception what the root cause is.
