### ISSUE TITLE
Cannot debug Python code in PyCharm

### ISSUE THREAD

**Issue by vmax** [bazelbuild/intellij#2093]
# Description

Currently, it's impossible to debug `py_binary`/`py_test` in PyCharm; this is a sample exception message:

```
/usr/bin/setsid --wait /usr/bin/python3.8 /snap/pycharm-community/205/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 46541 --file /home/vmax/.cache/bazel/_bazel_vmax/379e6d40d9b6adee7e2caab387d392a8/execroot/__main__/bazel-out/k8-fastbuild/bin/test
pydev debugger: process 80673 is connecting

Connected to pydev debugger (build 201.8743.11)
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/io.py", line 78, in <module>
    class BufferedIOBase(_io._BufferedIOBase, IOBase):
  File "/usr/lib/python3.8/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
KeyboardInterrupt

Process finished with exit code 1
```

What's curious is that with every debug rerun it's having a different stack trace (`KeyboardInterrupt` is always the last element)

# Reproducible example

`BUILD`:

```
py_binary(
    name = "test",
    srcs = ["test.py"],
)
```

`test.py`:

```
import sys
print(sys.path)
```

# Configuration

OS: Ubuntu 20.04
PyCharm version: `pycharm-community (2020.1/stable)`; installed via Snap
Python: 3.8.2
Plugin version: reproduced both on latest released version (`2020.07.13.0.2`) and one built from latest `master` (commit sha `43c4949a35bcde233c2f1b9bd2c6ecfdfa93acb6`)

**Comment by vinayan3** [comment]
An older PyCharm bug indicated that switching on `Attaching to subprocess automatically while debugging` is an issue. 

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003290559-KeyboardInterrupt-when-debugging-a-PyTorch-project

I tried turning this off and then the debugger says that it cannot debug because the main process has a subprocess.

**Comment by cwaeland** [comment]
I'm experiencing this the issue as well and would love to hear if there's a possible workaround. I cross posted on the Bazel slack as well.

**Comment by sseveran** [comment]
I have to manually update pydevd. Explanation here: https://github.com/bazelbuild/intellij/issues/402

**Comment by PoncinMatthieu** [comment]
See this comment for a fix with latest bazel version and latest intellij: https://github.com/bazelbuild/intellij/issues/402#issuecomment-726749713

**Comment by therearesomewhocallmetim** [comment]
Has there been any progress on this issue? I'm in 2022 on PyCharm 2022.2 and Bazel plugin 2022.08.09.0.1-api-version-222, but debugging doesn't work either

**Comment by tpasternak** [comment]
Hey @therearesomewhocallmetim, debugging works for me, despite the error you mentioned (I get it, too)

**Comment by tpasternak** [comment]
Closing, as this is likely to be fixed, please fill free to reopen if it still doesn't work for you

**Comment by Robbie-Palmer** [comment]
I'm getting the same issue after updating to Pycharm v2025.1.1.1

When I spawn a sub process and place a breakpoint on code in that subprocess I get after a second or so
```
Process Process-1:
Exception ignored in atexit callback: <function _exit_function at 0x7113fdcb9120>
Traceback (most recent call last):
  File "/home/robbie/miniconda3/envs/vs/lib/python3.12/multiprocessing/util.py", line 360, in _exit_function
    p.join()
  File "/home/robbie/miniconda3/envs/vs/lib/python3.12/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robbie/miniconda3/envs/vs/lib/python3.12/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robbie/miniconda3/envs/vs/lib/python3.12/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/home/robbie/miniconda3/envs/vs/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/robbie/miniconda3/envs/vs/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robbie/repos/stonehenge/vision/engine/solutions/static-camera/vision-service/src/domain/stream_processor.py", line 329, in run_stream_processor
    Resource(attributes)
    ^^^^^^^^
  File "/home/robbie/.local/share/JetBrains/Toolbox/apps/pycharm-professional/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_pep_669_tracing.py", line 553, in py_line_callback
    py_db.do_wait_suspend(thread, frame, 'line', None)
  File "/home/robbie/.local/share/JetBrains/Toolbox/apps/pycharm-professional/plugins/python-ce/helpers/pydev/pydevd.py", line 1220, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/home/robbie/.local/share/JetBrains/Toolbox/apps/pycharm-professional/plugins/python-ce/helpers/pydev/pydevd.py", line 1235, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
```
