### ISSUE TITLE
IDE Fatal Error on launching project

### ISSUE THREAD

**Issue by thomaslangston-mongodb** [bazelbuild/intellij#2095]
Error doesn't seem to prevent the code from syncing and compiling, but appears consistently in the error log under the "!" on the bottom right of the IDE window.

IntelliJ 2020.1.4
Bazel Plugin 2020.07.13.0.2
OS: MacOS Catalina 10.15.6 (19G2021)

Stacktrace:
com.intellij.diagnostic.PluginException: com.google.idea.blaze.google3.objfs.RemoteOutputStateProtoConverter PluginClassLoader[com.google.idea.bazel.ijwb, 2020.07.13.0.2] com.intellij.ide.plugins.cl.PluginClassLoader@1598d4d0 [Plugin: com.google.idea.bazel.ijwb]
	at com.intellij.serviceContainer.ComponentManagerImplKt.createPluginExceptionIfNeeded(ComponentManagerImpl.kt:939)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$createPluginExceptionIfNeeded(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:732)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:42)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:68)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:446)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:401)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:249)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:37)
	at com.google.idea.blaze.base.filecache.ArtifactStateProtoConverter.fromProto(ArtifactStateProtoConverter.java:40)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceState.fromProto(BlazeIdeInterfaceState.java:63)
	at com.google.idea.blaze.base.model.ProjectTargetData.fromProto(ProjectTargetData.java:51)
	at com.google.idea.blaze.base.model.BlazeProjectData.parseTargetData(BlazeProjectData.java:87)
	at com.google.idea.blaze.base.model.BlazeProjectData.fromProto(BlazeProjectData.java:74)
	at com.google.idea.blaze.base.model.BlazeProjectData.loadFromDisk(BlazeProjectData.java:151)
	at com.google.idea.blaze.base.sync.data.BlazeProjectDataManagerImpl.loadProject(BlazeProjectDataManagerImpl.java:85)
	at com.google.idea.blaze.base.sync.data.BlazeProjectDataManagerImpl.loadProjectRoot(BlazeProjectDataManagerImpl.java:71)
	at com.google.idea.blaze.base.prefetch.PrefetchProjectInitializer.getBlazeProjectData(PrefetchProjectInitializer.java:101)
	at com.google.idea.blaze.base.prefetch.PrefetchProjectInitializer.lambda$prefetchProjectFiles$1(PrefetchProjectInitializer.java:81)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:160)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleAsyncTask.runInterruptibly(TrustedListenableFutureTask.java:143)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.google.idea.blaze.google3.objfs.RemoteOutputStateProtoConverter PluginClassLoader[com.google.idea.bazel.ijwb, 2020.07.13.0.2] com.intellij.ide.plugins.cl.PluginClassLoader@1598d4d0
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:80)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:39)
	... 22 more

**Comment by thomaslangston-mongodb** [comment]
Issue persists through IDE restarts, project deletion and re-import, and plugin uninstallation and reinstallation.

**Comment by alexhanson** [comment]
This issue was also reported in issue #2014 and fixed in commit 9f65fdd, first included in the `v2020.08.26` tagged release.

There's still another issue (described in #2097, #2392, and #2874) pertaining to `ArtifactStateHelper` extensions, but I think this one can be closed.
