### ISSUE TITLE
Sync state is lost on restart 

### ISSUE THREAD

**Issue by iuliand-db** [bazelbuild/intellij#2097]
On every IDEA restart, the Bazel project re-syncs. The log shows a null file entries wile deserializing JDepsState:

```
java.lang.NullPointerException: Null file
	at com.google.idea.blaze.java.sync.jdeps.AutoValue_JdepsState_JdepsData.<init>(AutoValue_JdepsState_JdepsData.java:32)
	at com.google.idea.blaze.java.sync.jdeps.JdepsState$JdepsData.create(JdepsState.java:50)
	at com.google.idea.blaze.java.sync.jdeps.JdepsState.lambda$fromNewProto$3(JdepsState.java:74)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.idea.blaze.java.sync.jdeps.JdepsState.fromNewProto(JdepsState.java:78)
	at com.google.idea.blaze.java.sync.jdeps.JdepsState.fromProto(JdepsState.java:84)
	at com.google.idea.blaze.java.sync.jdeps.JdepsState.access$100(JdepsState.java:39)
	at com.google.idea.blaze.java.sync.jdeps.JdepsState$Extractor.extract(JdepsState.java:171)
	at com.google.idea.blaze.java.sync.jdeps.JdepsState$Extractor.extract(JdepsState.java:167)
	at com.google.idea.blaze.base.model.SyncData.lambda$extract$0(SyncData.java:36)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.idea.blaze.base.model.SyncData.extract(SyncData.java:38)
	at com.google.idea.blaze.base.model.SyncState.fromProto(SyncState.java:59)
	at com.google.idea.blaze.base.model.BlazeProjectData.fromProto(BlazeProjectData.java:82)
	at com.google.idea.blaze.base.model.BlazeProjectData.loadFromDisk(BlazeProjectData.java:151)
```

I think the root cause are two refactorings:

- https://github.com/bazelbuild/intellij/commit/1af8d0a996611d8e9b295c8b6cd7ca94dcffc630 that creates and `ArtifactsStateHelper` extension point, adds two implementations (a Local and a Remote one). The extension point is implemented via the remote one
- https://github.com/bazelbuild/intellij/commit/9f65fdd190a79bebb0550d8988ddaad4bc12396f Moves the Remote implementation out of the Bazel plugin, and leaves the extension point with no implementation

These two in turn lead to NPEs during initialization, at `BlazeProjectDataManagerImpl.loadProject`.

I think the fix just adding one line to `blaze-base.xml`:

```
    <ArtifactStateHelper implementation="com.google.idea.blaze.base.filecache.LocalArtifactStateProtoConverter"/>
```

Happy to open a PR if you'd want it.

**Comment by iuliand-db** [comment]
@brendandouglas does this make sense? 

I'm happy to provide a patch, but there seems to be a problem with my fork, see for instance BuildKite's failure to find it in #2089
