### ISSUE TITLE
Errors when trying to do a Bazel sync

### ISSUE THREAD

**Issue by gpmo** [bazelbuild/intellij#216]
Hi,

I'm experiencing issues when trying to sync my project using Bazel intellij plugin:

```
Error:(161, 1) in @intellij_aspect//:intellij_info.bzl%intellij_info_aspect aspect on java_toolchain rule @bazel_tools//tools/jdk:toolchain: 
```

Intellij version is `2017.3.2` on MacOS 10.12.6, Bazel version is `0.9.0-homebrew`, intellij plugin version is `2017.07.05.0.2`.

Thanks.

**Comment by plumpy** [comment]
That's a very old plugin version and a very new Bazel version. Try upgrading the plugin. The newest version is 2018.01.02.

**Comment by abhijith-gururaj** [comment]
I am facing the same issue!
`ERROR: C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/local_config_cc/BUILD:31:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on cc_toolchain_suite rule @local_config_cc//:toolchain: 
Traceback (most recent call last):
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/local_config_cc/BUILD", line 31
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/intellij_aspect/intellij_info_bundled.bzl", line 38, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/intellij_aspect/intellij_info_impl.bzl", line 788, in intellij_info_aspect_impl
		collect_c_toolchain_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/intellij_aspect/intellij_info_impl.bzl", line 364, in collect_c_toolchain_info
		cc_common.create_compile_variables(feature_configuration = feature_..., <2 more arguments>)`

I am using the latest plugin version on IntelliJ 2018.2.6 along with the latest bazel version. Can you please help me with this?
