### ISSUE TITLE
ERROR: cannot load '//bazel/tools:intellij.bzl': no such file

### ISSUE THREAD

**Issue by kamalrama** [bazelbuild/intellij#2238]
#### Version information
CLion: 2020.1.3
Platform: Mac OS X 10.15.6
Bazel plugin: 2020.09.16.0.6
Bazel: 3.4.1

#### Error

Building Bazel targets...
Building targets for shard 1 of 5...
Command: /Users/<xxxxxx>/bin/bazel build --tool_tag=ijwb:CLion --keep_going --build_event_binary_file=/var/folders/hz/pv4jljf13pjg6z055nj8q4mh0000gn/T/intellij-bep-c53e666b-508a-4fde-ad83-563968b5ed6f --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --config=titanos-arm64 --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/<xxxxxx>/Library/Application Support/JetBrains/CLion2020.1/plugins/clwb/aspect" --output_groups=intellij-info-cpp,intellij-info-generic,intellij-resolve-cpp -- 
//plat...
Loading: 
Loading: 0 packages loaded
Analyzing: 840 targets (0 packages loaded, 0 targets configured)
ERROR: cannot load '//bazel/tools:intellij.bzl': no such file
INFO: Analyzed 840 targets (2 packages loaded, 27 targets configured).
INFO: Found 840 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 1.436s, Critical Path: 0.01s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by kamalrama** [comment]
There is this Java exception associated with this plugin

java.lang.AbstractMethodError
	at com.intellij.ui.EditorNotifications$Provider.createNotificationPanel(EditorNotifications.java:51)
	at com.google.idea.blaze.plugin.CMakeNotificationFilter.createNotificationPanel(CMakeNotificationFilter.java:53)
	at com.intellij.ui.EditorNotifications$Provider.createNotificationPanel(EditorNotifications.java:56)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:167)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$2(EditorNotificationsImpl.java:149)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:472)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$2(NonBlockingReadActionImpl.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:437)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$0(NonBlockingReadActionImpl.java:370)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by sgowroji** [comment]
Hello @kamalrama, Are you still seeing the issue with latest Clion and Bazel plugin versions. Thanks!

**Comment by kshyanashree** [comment]
Closing this issue as there is no significant update from long duration. Please feel free to reopen if the above issue still exists. Thank you!
