### ISSUE TITLE
Intellij doesn't resolve external imports after git init.

### ISSUE THREAD

**Issue by bdleitner** [bazelbuild/intellij#2277]
Admittedly, I'm using the bazel plugin on windows, which I know is not really supported, but I'm not sure if this is related.

I had been able to get things working, and while some features (like partial sync) would have trouble due to malformed (for windows) paths, the project-level sync was working fine.

When I integrated with version control (git) however, things changed.

In my `WORKSPACE` I have 

```
maven_install(
    artifacts = [
        (various deps including...)
        "com.google.guava:guava:30.0-jre",
        "com.google.inject:guice:4.2.3",
        "com.google.protobuf:protobuf-java:4.0.0-rc-2",
        "com.google.truth:truth:1.1",
        "javax.inject:javax.inject:1",
        "junit:junit:4.13.1",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://maven.jahia.org/maven2",
        "https://repo1.maven.org/maven2",
    ],
)
```

and to reference them I have an `ext` package and subpackages with `BUILD` files to reference these.  For example:

`ext/google/BUILD`
```
package(default_visibility = ["//visibility:public"])

...

java_library(
    name = "guava",
    exports = ["@maven//:com_google_guava_guava"],
)

java_library(
    name = "guice",
    exports = ["@maven//:com_google_inject_guice"],
)

...
```

I could then use `//ext/google:guava` in `deps` for a `java_library` and everything would work fine.

Once I ran `git init`, however, things changed.  To avoid including all of bazel's output, I have my `.gitignore`:

```
/.ijwb/
/bazel-*/
```

When I now click to sync the project, everything syncs fine an the bazel console shows no errors, but if I navigate to a class that uses imports from a target under `ext`, Intellij no longer recognizes the import.  The import statements and all references to the class are now red.  Everything still builds, but it makes IJ rather unusable.

If I then rename the `.git` directory to `.gitold`, remove the VC integration from settings, and resync the project, all the imports are recognized again.

**Comment by bdleitner** [comment]
I don't know what changed, but after a couple updates to the plugin, now if I try to sync while the `.git` directory exists, the sync crashes due to malformed paths for windows.  The workaround of renaming the `.git` directory to `.gitold` during syncs still works.

**Comment by bdleitner** [comment]
Any progres/thoughts/ETA?  This is consistently the most irritating issue when using bazel on windows (this, and the fact that partial sync doesn't work because path names).  Having to disengage the VCS every time I need to sync e.g. because new generated code, or because I had to run `blaze clean` because "failed to delete output files" (another annoyance) is rather tiresome.

**Comment by bdleitner** [comment]
Something seems to have changed as the behavior is now back to what it was prior to my March 26th, 2021 update.  Pressing the sync button no longer leads to a failure, but after the sync completes, imports from outside the project show up in red in IntelliJ.

**Comment by bdleitner** [comment]
It had been a while since I did work on my personal projects, but I decided to poke around today and thought of checking on this issue in the process.  

I'm now on bazel 6.4.0 (via bazelisk 1.19.0) and Bazel IJ plugin 2023.11.21.0.1-api-version-232

After a `bazel clean` and `bazel sync` when the git directory is present, a click of the sync button:

1. shows an error in bazel problems:
    ```
    "Error: no such target '//:WORKSPACE': target 'WORKSPACE' not declared in package '' defined by"
    ```
    though it just continues.

2. It completes the sync but class outside the workspace are still highlighted in red.

If I rename the `.git` directory as before and resync, then neither of these happens.  No errors and everything is recognized.

So safe to say this is still occurring.

**Comment by bdleitner** [comment]
> > 1. shows an error in bazel problems:
> >    ```
> >    "Error: no such target '//:WORKSPACE': target 'WORKSPACE' not declared in package '' defined by"
> >    ```
> >    though it just continues.
> 
> This is an unrelated problem (IMO)

I suspect you are correct.  Not only is it new, it seems unrelated to whether or not the IDE "knows about" other dependencies.

> 
> > 2. It completes the sync but class outside the workspace are still highlighted in red.
> 
> What do you mean by the "class outside" an external dependency (like maven central one)?

Should have read "classes."  I mean any import statement for a class not in the workspace (so anything coming from an external maven or bazel dependency) is highlighted in red and references to the class in code are similarly marked.

**Comment by bdleitner** [comment]
Sorry for the delay.  I was out of town for a while.

> Oh, I forgot there was one in the message from 2021. Could you please add your "guava" target directly to `targets` section in the project view and check if it gets better?

While the above example is how I was able to construct a simple repro back in 2021, this isn't how I construct these dependencies anymore.  I don't have a quick small repro that accurately represents my real setup.

I have a separate project/workspace (`bdl_deps`) that contains code to set up repos for various dependencies (in effect to do some of what modules do now, so I'm excited to update to `bzlmod`).

For Guava specifically, I wanted to split up the monolith as I'm used to working internally with blaze and separate `//java/com/google/common/...` targets rather than a Guava monolith.  I have a `java.bzl` file that defines methods that create targets and load their dependencies.  An except from that file for the Guava target is included below.

I tried to go and see if I could modify an existing workspace I had to see this, but with the bazel update to v7 (bazelisk auto-update) I had to disable modules, but then I ran into other problems with the javaformatter, and then with `io_bazel_rules_go`.

When I tried to create a minimal example from scratch, I couldn't reproduce the problem.  So it might have something to do with my setup (though my setup for things other than guava, e.g. Guice or JUnit is much simpler and they also exhibit symptoms).  But it looks like I have a fair amount of rot to clean up in my ecosystem (hopefully `bzlmod` will help with that.  

Right now I've got completely unrelated backward compatibility issues all over the place: 

The latest being:
```
ERROR: D:/_bazel_out/gbubqhd3/external/io_bazel_rules_go/BUILD.bazel:71:16: in (an implicit dependency) attribute of go_context_data rule @@io_bazel_rules_go//:go_context_data: in $whitelist_function_transition attribute of go_context_da
ta rule @@io_bazel_rules_go//:go_context_data: package group '@@bazel_tools//tools/whitelists/function_transition_whitelist:function_transition_whitelist' is misplaced here (they are only allowed in the visibility attribute)
```

and then when I updated `io_bazel_rules_go` to the lastest version `0.43`

```
Traceback (most recent call last):
        File "D:/_bazel_out/gbubqhd3/external/io_bazel_rules_go/go/private/rules/stdlib.bzl", line 33, column 20, in _stdlib_impl
                go = go_context(ctx)
        File "D:/_bazel_out/gbubqhd3/external/io_bazel_rules_go/go/private/context.bzl", line 425, column 20, in go_context
                mode = get_mode(ctx, toolchain, cgo_context_info, go_config_info)
        File "D:/_bazel_out/gbubqhd3/external/io_bazel_rules_go/go/private/mode.bzl", line 109, column 13, in get_mode
                fail(("linkmode '{}' can't be used when cgo is disabled. Check that pure is not set to \"off\" and that a C/C++ toolchain is configured for " +
Error in fail: linkmode 'c-shared' can't be used when cgo is disabled. Check that pure is not set to "off" and that a C/C++ toolchain is configured for your current platform. If you defined a custom platform, make sure that it has the @i
o_bazel_rules_go//go/toolchain:cgo_on constraint value.
```

Plus apparently something with JavaFormatter:
```
java.lang.RuntimeException: java.lang.NoSuchFieldError: Class com.google.googlejavaformat.java.JavacTokens$CommentSavingTokenizer does not have member field 'com.sun.tools.javac.parser.UnicodeReader reader'
```

Which is used my some of my annotation processors, so there's something version-y going on there too.

So... yeah... my entire ecosystem is a mess and I have to figure out what to do about that.

But if it helps, here's the excerpt from my `java.bzl` file for how I load Guice and Guava:

```
def google_guice():
    if not native.existing_rule("maven_google_guice"):
        google_guava()

        maven_install(
            name = "maven_google_guice",
            excluded_artifacts = [
                maven.exclusion(
                    group = "com.google.guava",
                    artifact = "guava",
                ),
            ],
            artifacts = [
                "com.google.inject:guice:4.2.3",
            ],
            repositories = [
                "https://maven.google.com",
                "https://repo1.maven.org/maven2",
            ],
            fetch_sources = True,
        )

        new_simple_repo(
            name = "google_guice",
            build_file_content = """
package(default_visibility = ["//visibility:public"])

java_library(
    name = "guice",
    exports = [
        "@maven_google_guice//:com_google_inject_guice",
        "@guava//:collect",
    ],
)
""",
        )


def google_guava():
    java()
    google_errorprone()

    if not native.existing_rule("maven_guava"):
        maven_install(
            name = "maven_guava",
            artifacts = [
                "com.google.j2objc:j2objc-annotations:1.3",
                # TODO: Switch to -jre once https://github.com/bazelbuild/bazel/issues/12944 is fixed
                "org.checkerframework:checker-compat-qual:2.5.5",
                "org.checkerframework:checker-qual:3.35.0",
            ],
            repositories = [
                "https://maven.google.com",
                "https://repo1.maven.org/maven2",
            ],
            fetch_sources = True,
        )

        http_archive(
            name = "guava",
            sha256 = "0b0c81e865edd6db7e493919814ffd2779d1f468ff793bfb05924a3999689e0a",
            strip_prefix = "guava-32.1.1",
            urls = [
                "https://github.com/google/guava/archive/v32.1.1.zip",
            ],
            # TODO: Switch to -jre once https://github.com/bazelbuild/bazel/issues/12944 is fixed
            build_file_content = """
package(default_visibility = ["//visibility:public"])

java_library(
  name="checker",
  neverlink = 1,
  exports = [
    "@maven_guava//:org_checkerframework_checker_compat_qual",
    "@maven_guava//:org_checkerframework_checker_qual",
  ],
)

java_library(
  name = "annotations",
  srcs = glob(["android/guava/src/com/google/common/annotations/*.java"]),
)

java_library(
  name = "base",
  srcs = glob(["android/guava/src/com/google/common/base/*.java"]),
  javacopts = ["-XepDisableAllChecks"],
  deps = [
    ":annotations",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    "@maven_guava//:com_google_j2objc_j2objc_annotations",
    ":checker",
  ]
)

java_library(
  name = "cache",
  srcs = glob(["android/guava/src/com/google/common/cache/*.java"]),
  javacopts = ["-XepDisableAllChecks"],
  deps = [
    ":annotations",
    ":base",
    ":collect",
    ":concurrent",
    ":math",
    ":primitives",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    "@maven_guava//:com_google_j2objc_j2objc_annotations",
    ":checker",
  ]
)

# A split to allow for bundling the guava workaround into the externally visible package.
java_library(
  name = "collect_internal",
  srcs = glob(["android/guava/src/com/google/common/collect/*.java"]),
  visibility = [
    "@bdl_deps//java/com/bdl/workarounds/guava:__pkg__",
  ],
  javacopts = ["-XepDisableAllChecks"],
  deps = [
    ":annotations",
    ":base",
    ":math",
    ":primitives",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    "@maven_guava//:com_google_j2objc_j2objc_annotations",
    ":checker",
  ],
)

java_library(
  name = "collect",
  exports = [
    ":collect_internal",
    "@bdl_deps//java/com/bdl/workarounds/guava",
  ],
)

java_library(
  name = "concurrent",
  srcs = glob(["android/guava/src/com/google/common/util/concurrent/*.java"]),
  javacopts = ["-XepDisableAllChecks"],
  deps = [
    ":annotations",
    ":base",
    ":collect",
    ":futures_failureaccess",
    ":math",
    ":primitives",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    "@maven_guava//:com_google_j2objc_j2objc_annotations",
    ":checker",
  ],
)

java_library(
  name = "futures_failureaccess",
  srcs = glob(["futures/failureaccess/src/com/google/common/util/concurrent/internal/*.java"]),
  visibility = ["//visibility:private"],
)

java_library(
  name = "graph",
  srcs = glob(["android/guava/src/com/google/common/graph/*.java"]),
  javacopts = ["-XepDisableAllChecks"],
  deps = [
    ":annotations",
    ":base",
    ":collect",
    ":math",
    ":primitives",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    ":checker",
  ],
)

java_library(
  name = "hash",
  srcs = glob(["android/guava/src/com/google/common/hash/*.java"]),
  javacopts = ["-XepDisableAllChecks"],
  deps = [
    ":annotations",
    ":base",
    ":math",
    ":primitives",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    ":checker",
  ],
)

java_library(
  name = "io",
  srcs = glob(["android/guava/src/com/google/common/io/*.java"]),
  javacopts = ["-XepDisableAllChecks"],
  deps = [
    ":annotations",
    ":base",
    ":collect",
    ":graph",
    ":hash",
    ":math",
    ":primitives",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    "@maven_guava//:com_google_j2objc_j2objc_annotations",
    ":checker",
  ],
)

java_library(
  name = "math",
  srcs = glob(["android/guava/src/com/google/common/math/*.java"]),
  javacopts = ["-XepDisableAllChecks"],
  deps = [
    ":annotations",
    ":base",
    ":primitives",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    ":checker",
  ],
)

java_library(
  name = "primitives",
  srcs = glob(["android/guava/src/com/google/common/primitives/*.java"]),
  javacopts = ["-XepDisableAllChecks"],
  deps = [
    ":annotations",
    ":base",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    ":checker",
  ],
)

java_library(
  name = "reflect",
  srcs = glob(["android/guava/src/com/google/common/reflect/*.java"]),
  deps = [
    ":annotations",
    ":base",
    ":collect",
    ":io",
    ":primitives",
    "@java//:jsr305_annotations",
    "@google_errorprone//:annotations",
    ":checker",
  ],
)
""",
        )
```
