### ISSUE TITLE
TSConfig - Workspace path must be relative; cannot start with '/'

### ISSUE THREAD

**Issue by wardellbagby** [bazelbuild/intellij#2338]
I've been getting an error in Intellij IDEA Ultimate 2020.2.4 when using the Bazel plugin and opening a TS file.

It seems like it's failing to resolve my TSConfig file, which means that things like IDE support for the TS paths don't exist.

I don't have a small sample repo but I do have the exact repo it's failing against, along with my `.bazelproject` file.

Things I've tried:

- Downgrading my Bazel plugin to `2021.01.06.0.1`
- Downgrading my Typescript version to `3.9.7`
- Deleting the `.ijwb` folder and reimporting.
- Making a dedicated `//:tsconfig` rule in my root `BUILD.bazel` file and referencing that in my `.bazelproject` instead of using the `//:tsconfig.json` label.
- Removing `javascript` from `additional_languages`
- A few `bazel clean` s thrown about.
- Creating a `tsconfig.json` that only extends the root `tsconfig` and referencing that in `.bazelproject`.

My setup:
- macOS Catalina - 10.15.7
- Bazelisk 1.7.4, fetching Bazel 3.7.2 for my project
- `rules_nodejs` 3.0.0
- Typescript 4.1 (this was previously 3.9.7 and I still saw the issue there)

Notes:
While I did try downgrading my IJWB plugin version, I've seen this across multiple, from approx. version `2020.10.19.0.3` onward, which is about when I started using the plugin.

Repo: https://github.com/wardellbagby/lyricistant/tree/c3a1e5b9735a6a68b0c231517e269db54d8d5e86
Stack trace:
```
java.lang.IllegalArgumentException: Invalid workspace path '/tsconfig.json': Workspace path must be relative; cannot start with '/': /tsconfig.json
	at com.google.idea.blaze.base.model.primitives.WorkspacePath.<init>(WorkspacePath.java:54)
	at com.google.idea.blaze.base.model.primitives.WorkspacePath.<init>(WorkspacePath.java:60)
	at com.google.idea.blaze.typescript.AddTsConfigNotificationProvider.getTsConfigDirectoryForFile(AddTsConfigNotificationProvider.java:177)
	at com.google.idea.blaze.typescript.AddTsConfigNotificationProvider.getTsConfigLabelForFile(AddTsConfigNotificationProvider.java:139)
	at com.google.idea.blaze.typescript.AddTsConfigNotificationProvider.createNotificationPanel(AddTsConfigNotificationProvider.java:85)
	at com.google.idea.blaze.typescript.AddTsConfigNotificationProvider.createNotificationPanel(AddTsConfigNotificationProvider.java:52)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:170)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$2(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:508)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:456)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:56)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.jetbrains.rdserver.BackendProgressManager.executeProcessUnderProgress(BackendProgressManager.kt:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:56)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:473)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:397)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:186)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by dsilvasc** [comment]
I think this happens when you only have a tsconfig.json in the root of your workspace.

The loop in https://github.com/bazelbuild/intellij/blob/0e0aa728bc889331e935ba025d10eaba2a010029/javascript/src/com/google/idea/blaze/typescript/AddTsConfigNotificationProvider.java#L177 eventually reaches a case where `parent` is the workspace root, so its `relativePath()` returns the empty string, and https://github.com/bazelbuild/intellij/blob/0e0aa728bc889331e935ba025d10eaba2a010029/base/src/com/google/idea/blaze/base/model/primitives/WorkspacePath.java#L60 produces the invalid `/tsconfig.json`.

If you add a tsconfig.json alongside your package's BUILD.bazel it works again, even if that tsconfig just extends the root one with no other config.  Like this in the case of `packages/apps/hello/tsconfig.json`:

```json
{
  "extends": "../../../tsconfig.json"
}
```

**Comment by mscolnick** [comment]
I am hitting this issue as well. We have a lot of projects/BUILD files (many not typescript) so its not so feasible to add `tsconfig.json` to all of them. Would it be possible to get a fix or fail gracefully? 

When this plugin hits the `IllegalArgumentException`, "Go To Definition" is no longer supported

**Comment by CoopeyB** [comment]
@mai93 - This bug breaks many typescript users (placing tsconfig.json at the root of the repository/workspace is common practice). We already have a PR to fix it, so it shouldn't take too much time for a maintainer to take a look. Who should review this?

Thanks!
