### ISSUE TITLE
Fatal error at init

### ISSUE THREAD

**Issue by mbravi** [bazelbuild/intellij#234]
Today I updated both CLion and the Bazel plugin. After restarting I got an error (reported later) and I had to disable the plugin.
Any idea what the issue might be?

Thanks

Plugin 'com.google.idea.bazel.clwb' failed to initialize and will be disabled.  Please restart CLion.

java.lang.NoClassDefFoundError: com/jetbrains/cidr/modulemap/resolve/ModuleMapInitialBuildingActivity
    at com.google.idea.sdkcompat.cidr.CidrStartupActivitiesToSuppress.<clinit>(CidrStartupActivitiesToSuppress.java:28)
    at com.google.idea.blaze.cpp.CidrSymbolBuilderSuppressor.addFiltersToStartupActivities(CidrSymbolBuilderSuppressor.java:38)
    at com.google.idea.blaze.cpp.CidrSymbolBuilderSuppressor.initComponent(CidrSymbolBuilderSuppressor.java:52)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.jetbrains.cidr.modulemap.resolve.ModuleMapInitialBuildingActivity PluginClassLoader[com.google.idea.bazel.clwb, 2018.01.02.0.1] com.intellij.ide.plugins.cl.PluginClassLoader@2c9122f4
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more

**Comment by ittaiz** [comment]
Are you on latest IntelliJ?

**Comment by mbravi** [comment]
I downloaded the latest CLion as https://plugins.jetbrains.com/plugin/9554-bazel said it is compatible with the latest bazel plugin.

I am on Clion-2017.3.3 build 173.4548.31, from the 31st of January 2017.

**Comment by brendandouglas** [comment]
The CLion plugin API is changing pretty frequently now (perhaps partly because there are very few CLion-specific plugins like ours), so our plugin often won't work with any version but the specific one it was built against (in this case, 173.4301, which is 2017.3.2).

Can you try downgrading to 2017.3.2?

**Comment by mbravi** [comment]
Yes, that was it.
Thanks.

**Comment by brendandouglas** [comment]
Closing -- we now support 2017.3.3, and there's a separate FR to support 2018.1
