### ISSUE TITLE
Can't import existing project

### ISSUE THREAD

**Issue by samikama** [bazelbuild/intellij#236]
Hi,

I am trying to import tensorflow into clion 2017.3.3 using bazel plugin 2018.01.29.0.0 . I get the following error 

> Syncing project: Sync Project (startup)...
> Updating VCS...
> Running Bazel info...
> Command: bazel info --tool_tag=ijwb:CLion --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --
> 
> 
> Command: git diff --name-status --no-renames 289a7c1ac96f58f7ca4e9d85b3640faa0a46b610
> 
> 
> ERROR: While parsing option --client_env=: Variable definitions must be in the form of a 'name=value' assignment
> 
> ==== TIMING REPORT ====
> 
> Sync: 307ms
>     BazelInfo: 234ms
>     GitDiff: 149ms
> 
> Timing summary:
> 
> BlazeInvocation: 234ms
> Other: 149ms
> Sync failed
Also 
com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 2
java.util.concurrent.ExecutionException: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 2
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:96)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:86)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:315)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:228)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:189)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:163)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:113)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: 2
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.runBlazeInfo(BlazeInfoRunnerImpl.java:102)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:72)
	... 6 more

Any chance this being fixed?

**Comment by chaoren** [comment]
Seems like this issue:
https://github.com/bazelbuild/bazel/issues/3196
solution is to unset `GTK_MODULES` before starting CLion.

**Comment by chaoren** [comment]
Closing this, please follow https://github.com/bazelbuild/intellij/issues/108 for more information.
