### ISSUE TITLE
Error when a test fails (2020.3)

### ISSUE THREAD

**Issue by ekatz-quotient** [bazelbuild/intellij#2492]
```
2021-04-06 11:03:53,748 [1168659]  ERROR - ecution.process.ProcessHandler - null 
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy36.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:204)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:279)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:187)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:183)
	at com.intellij.execution.process.KillableProcessHandler.notifyProcessTerminated(KillableProcessHandler.java:136)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:206)
	at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:97)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$0(ProcessWaitFor.java:55)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.String.replace(String.java:2142)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.pruneErrorMessage(BlazeXmlToTestEventsConverter.java:379)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.getTestFailedEvent(BlazeXmlToTestEventsConverter.java:386)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processTestCase(BlazeXmlToTestEventsConverter.java:367)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processTestSuite(BlazeXmlToTestEventsConverter.java:265)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processTestSuite(BlazeXmlToTestEventsConverter.java:259)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processParsedTestResults(BlazeXmlToTestEventsConverter.java:179)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processAllTestResults(BlazeXmlToTestEventsConverter.java:114)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.flushBufferOnProcessTermination(BlazeXmlToTestEventsConverter.java:97)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.processTerminated(SMTestRunnerConnectionUtil.java:211)
	... 25 more
2021-04-06 11:03:53,748 [1168659]  ERROR - ecution.process.ProcessHandler - IntelliJ IDEA 2020.3.3  Build #IU-203.7717.56 
2021-04-06 11:03:53,748 [1168659]  ERROR - ecution.process.ProcessHandler - JDK: 11.0.9.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-04-06 11:03:53,748 [1168659]  ERROR - ecution.process.ProcessHandler - OS: Linux 
2021-04-06 11:03:53,749 [1168660]  ERROR - ecution.process.ProcessHandler - Plugin to blame: Bazel version: 2021.03.25.0.1 
```

**Comment by alice-ks** [comment]
Thanks for the report. From the stack trace, this error only occurs in a specific situation: when there is no error message from the test run. That should only happen in corner cases. In any case, I added an additional null check with #2522. That should avoid the NPE.
