### ISSUE TITLE
Error in 2021.1

### ISSUE THREAD

**Issue by ekatz-quotient** [bazelbuild/intellij#2733]
```
java.lang.Throwable: cannot share data context between Swing events; initial event count = 16360524; current event count = 16426813
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:327)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:63)
	at com.google.idea.blaze.java.run.producers.TestMethodSelectionUtil.getSelectedPsiElements(TestMethodSelectionUtil.java:130)
	at com.google.idea.blaze.java.run.producers.TestMethodSelectionUtil.getDirectlySelectedMethods(TestMethodSelectionUtil.java:107)
	at com.google.idea.blaze.java.run.producers.TestMethodSelectionUtil.getSelectedMethods(TestMethodSelectionUtil.java:55)
	at com.google.idea.blaze.java.run.producers.TestMethodSelectionUtil.getSelectedMethods(TestMethodSelectionUtil.java:85)
	at com.google.idea.blaze.java.run.producers.JavaTestContextProvider.getTestContext(JavaTestContextProvider.java:57)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.lambda$doFindTestContext$1(TestContextRunConfigurationProducer.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.doFindTestContext(TestContextRunConfigurationProducer.java:94)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.lambda$findTestContext$0(TestContextRunConfigurationProducer.java:84)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.findTestContext(TestContextRunConfigurationProducer.java:79)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.doIsConfigFromContext(TestContextRunConfigurationProducer.java:126)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.doIsConfigFromContext(TestContextRunConfigurationProducer.java:38)
	at com.google.idea.blaze.base.run.producers.BlazeRunConfigurationProducer.isConfigurationFromContext(BlazeRunConfigurationProducer.java:71)
	at com.intellij.execution.actions.RunConfigurationProducer.findExistingConfiguration(RunConfigurationProducer.java:234)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:253)
	at com.intellij.execution.actions.BaseRunConfigurationAction.findExisting(BaseRunConfigurationAction.java:62)
	at com.intellij.execution.actions.BaseRunConfigurationAction.fullUpdate(BaseRunConfigurationAction.java:232)
	at com.intellij.execution.actions.BaseRunConfigurationAction.beforeActionPerformedUpdate(BaseRunConfigurationAction.java:186)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:169)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:626)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:486)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:481)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:232)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:889)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by AlexeyGy** [comment]
Thanks for sharing the error message, could you elaborate on when exactly the error happens and, ideally, provide a project to reproduce? For one, I don't see it when I build/sync/open our plugin project.

**Comment by ekatz-quotient** [comment]
I can't reproduce it on demand, thought the stack trace might be enough.

**Comment by sgowroji** [comment]
Hello @ekatz-quotient, Could you please try the above with the latest bazel plugin and intellij releases. Let us know if you are still seeing the above error logs. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
