### ISSUE TITLE
Error when syncing (2021.1)

### ISSUE THREAD

**Issue by ekatz-quotient** [bazelbuild/intellij#2792]
```
java.lang.NullPointerException
	at com.google.idea.blaze.java.run.producers.ProducerUtils.getTestClass(ProducerUtils.java:104)
	at com.google.idea.blaze.java.run.producers.ProducerUtils.getTestClass(ProducerUtils.java:98)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestContextProvider.getNonAbstractTestClass(MultipleJavaClassesTestContextProvider.java:292)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestContextProvider.lambda$selectedTestClasses$2(MultipleJavaClassesTestContextProvider.java:156)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestContextProvider.selectedTestClasses(MultipleJavaClassesTestContextProvider.java:158)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestContextProvider.getTestContext(MultipleJavaClassesTestContextProvider.java:89)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.lambda$doFindTestContext$1(TestContextRunConfigurationProducer.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.doFindTestContext(TestContextRunConfigurationProducer.java:94)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.lambda$findTestContext$0(TestContextRunConfigurationProducer.java:84)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.findTestContext(TestContextRunConfigurationProducer.java:79)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.doIsConfigFromContext(TestContextRunConfigurationProducer.java:126)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.doIsConfigFromContext(TestContextRunConfigurationProducer.java:38)
	at com.google.idea.blaze.base.run.producers.BlazeRunConfigurationProducer.isConfigurationFromContext(BlazeRunConfigurationProducer.java:71)
	at com.intellij.execution.actions.RunConfigurationProducer.findExistingConfiguration(RunConfigurationProducer.java:234)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:253)
	at com.intellij.execution.actions.BaseRunConfigurationAction.findExisting(BaseRunConfigurationAction.java:62)
	at com.intellij.execution.actions.BaseRunConfigurationAction.fullUpdate(BaseRunConfigurationAction.java:232)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:198)
	at com.intellij.execution.lineMarker.ExecutorAction.update(ExecutorAction.kt:86)
	at com.intellij.execution.lineMarker.RunLineMarkerContributor.getText(RunLineMarkerContributor.java:90)
	at com.google.idea.blaze.base.run.producers.BuildFileRunLineMarkerContributor.lambda$getInfo$0(BuildFileRunLineMarkerContributor.java:71)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1913)
	at com.google.idea.blaze.base.run.producers.BuildFileRunLineMarkerContributor.lambda$getInfo$1(BuildFileRunLineMarkerContributor.java:71)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.lambda$createLineMarker$2(RunLineMarkerProvider.java:127)
	at com.intellij.codeInsight.daemon.LineMarkerInfo.getLineMarkerTooltip(LineMarkerInfo.java:192)
	at com.intellij.codeInsight.daemon.LineMarkerInfo$LineMarkerGutterIconRenderer.getTooltipText(LineMarkerInfo.java:257)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl$2.lambda$run$0(EditorGutterComponentImpl.java:1739)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl$2.run(EditorGutterComponentImpl.java:1739)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by alice-ks** [comment]
This NPE shouldn't be new in 2021.1 but could also occur in older versions. You might run into it when the selected PsiElement becomes invalid. This NPE should be fixed with #2847.
