### ISSUE TITLE
Plugin hangs with an error when a test fails (2021.2)

### ISSUE THREAD

**Issue by ekatz-quotient** [bazelbuild/intellij#2825]
```
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:247)
	at com.sun.proxy.$Proxy34.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:205)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:280)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:188)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:184)
	at com.intellij.execution.process.KillableProcessHandler.notifyProcessTerminated(KillableProcessHandler.java:138)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:205)
	at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:99)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$0(ProcessWaitFor.java:45)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:23)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at com.intellij.rt.execution.testFrameworks.AbstractExpectedPatterns.createExceptionNotification(AbstractExpectedPatterns.java:51)
	at com.intellij.rt.execution.testFrameworks.AbstractExpectedPatterns.createExceptionNotification(AbstractExpectedPatterns.java:36)
	at com.intellij.junit4.ExpectedPatterns.createExceptionNotification(ExpectedPatterns.java:48)
	at com.google.idea.blaze.java.run.smrunner.JunitTestComparisonFailureParser.tryParse(JunitTestComparisonFailureParser.java:29)
	at com.google.idea.blaze.base.run.smrunner.TestComparisonFailureParser.parse(TestComparisonFailureParser.java:28)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.parseComparisonData(BlazeXmlToTestEventsConverter.java:419)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.getTestFailedEvent(BlazeXmlToTestEventsConverter.java:390)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processTestCase(BlazeXmlToTestEventsConverter.java:367)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processTestSuite(BlazeXmlToTestEventsConverter.java:265)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processTestSuite(BlazeXmlToTestEventsConverter.java:259)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processParsedTestResults(BlazeXmlToTestEventsConverter.java:179)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processAllTestResults(BlazeXmlToTestEventsConverter.java:114)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.flushBufferOnProcessTermination(BlazeXmlToTestEventsConverter.java:97)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.processTerminated(SMTestRunnerConnectionUtil.java:211)
	... 25 more
```

**Comment by alice-ks** [comment]
This NPE doesn't seem to be related to the new version for 2021.2. It seems to occur whenever the test framework doesn't set a message for the failed test, which might be specific for your Bazel environment. This NPE should be fixed with #2845.
