### ISSUE TITLE
Support IJ 2018.1

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#290]
```
com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: -1
java.util.concurrent.ExecutionException: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: -1
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:96)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:86)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:311)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:228)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:189)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:163)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:113)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.idea.blaze.base.command.info.BlazeInfoException: blaze info failed with exit code: -1
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.runBlazeInfo(BlazeInfoRunnerImpl.java:102)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:72)
	... 6 more
```

Console output:

```
Error:Cannot run program "bazel" (in directory "/Volumes/work/src/github.com/hsyed/rules_kotlin"): error=2, No such file or directory
```

@brendandouglas is 2018.1 working in general ?

**Comment by chaoren** [comment]
Do you have the absolute path for bazel set in your settings?

**Comment by excavador** [comment]
Hi!
Thank you for great plugin.
Do you have any estimate when support will be available?

**Comment by brendandouglas** [comment]
As a rough estimate, I expect we'll upload a 2018.1-compatible plugin around late May.

**Comment by tdyas** [comment]
Any incomplete work that could be shared to let others help with the effort?

**Comment by brendandouglas** [comment]
We've switched to 2018.1 for the next release (in 3 weeks time). Most of the work involved is tracking down the many edge cases where things stop working in a new release, which can't really be shared.

**Comment by excavador** [comment]
verified, works, thank you!

**Comment by ricelid** [comment]
@excavador Where'd you get the working plugin? I tried downloading it from here and the latest version (2018.05.07.0.2) doesn't work.

**Comment by brendandouglas** [comment]
@ricelid what problems are you having with that plugin version? Could you include:
- your IDE + IDE version
- any exceptions coming from the problem and/or else expected vs actual results

**Comment by ricelid** [comment]
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
Licensed to Google

JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

Problem 1:
The Bazel plugin doesn't show up in the search results within "Browse Repositories".

Problem 2:
When I download the zip file from [here](https://plugins.jetbrains.com/plugin/8609-bazel) and "install plugin from disk", I get "Plugin 'Bazel' is incompatible with this installation".

**Comment by brendandouglas** [comment]
That's an old version of IJ 2018.1, which the plugin isn't compatible with (the version compatibility information is listed in the JetBrains plugin repo site you linked).

**Comment by excavador** [comment]
@ricelid I download new IDEA (2018.1.3) and new bazel plugins.
Works fine for golang, python, javascript
