### ISSUE TITLE
This plugin triggers "IntelliJ Idea needs to be updated" warning on MacOS 12 Monterey

### ISSUE THREAD

**Issue by lukaszwawrzyk** [bazelbuild/intellij#3020]
Under the following stacktrace
```
 at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method) at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method) - parking to wait for  <0x000000072287e028> (a com.intellij.util.concurrency.Semaphore$Sync) at java.util.concurrent.locks.LockSupport.park(java.base@11.0.10/LockSupport.java:194) at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.10/AbstractQueuedSynchronizer.java:885) at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.10/AbstractQueuedSynchronizer.java:1039) at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.10/AbstractQueuedSynchronizer.java:1345) at com.intellij.util.concurrency.Semaphore.waitForUnsafe(Semaphore.java:81) at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:73) at com.intellij.execution.process.ProcessHandler.waitFor(ProcessHandler.java:95) at com.intellij.execution.process.BaseOSProcessHandler.waitFor(BaseOSProcessHandler.java:184) at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:112) at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:39) at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:55) at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:145) at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:93) at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:83) at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:75) at com.jetbrains.python.sdk.flavors.PythonSdkFlavor.getVersionString(PythonSdkFlavor.java:180) at com.jetbrains.python.sdk.flavors.PythonSdkFlavor.getLanguageLevel(PythonSdkFlavor.java:228) at com.google.idea.blaze.python.sdk.FallbackPythonSdkSuggester.getSdkLanguageLevel(FallbackPythonSdkSuggester.java:78) at com.google.idea.blaze.python.sdk.FallbackPythonSdkSuggester.lambda$findSystemSdks$0(FallbackPythonSdkSuggester.java:61) at com.google.idea.blaze.python.sdk.FallbackPythonSdkSuggester$$Lambda$3671/0x0000000801ee6c40.test(Unknown Source) at java.util.stream.ReferencePipeline$2$1.accept(java.base@11.0.10/ReferencePipeline.java:176) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@11.0.10/ArrayList.java:1655) at java.util.stream.AbstractPipeline.copyInto(java.base@11.0.10/AbstractPipeline.java:484) at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@11.0.10/AbstractPipeline.java:474) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@11.0.10/ReduceOps.java:913) at java.util.stream.AbstractPipeline.evaluate(java.base@11.0.10/AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.reduce(java.base@11.0.10/ReferencePipeline.java:558) at java.util.stream.ReferencePipeline.max(java.base@11.0.10/ReferencePipeline.java:594) at com.google.idea.blaze.python.sdk.FallbackPythonSdkSuggester.findSystemSdks(FallbackPythonSdkSuggester.java:62) at com.google.idea.blaze.python.sdk.FallbackPythonSdkSuggester$$Lambda$3664/0x0000000801ec2440.get(Unknown Source) at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167) - locked <0x0000000722884228> (a com.google.common.base.Suppliers$NonSerializableMemoizingSupplier) at com.google.idea.blaze.python.sdk.FallbackPythonSdkSuggester$SdkInitializer.runActivity(FallbackPythonSdkSuggester.java:49) at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:329) at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:303) at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$4(StartupManagerImpl.java:229) at com.intellij.ide.startup.impl.StartupManagerImpl$$Lambda$2445/0x0000000801689040.accept(Unknown Source) at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:296) at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:158) at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:223) at com.intellij.ide.startup.impl.StartupManagerImpl$$Lambda$2442/0x0000000801688440.run(Unknown Source) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178) at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$346/0x0000000800466440.run(Unknown Source) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165) at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254) at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:157) at com.intellij.ide.startup.impl.StartupManagerImpl$$Lambda$2439/0x0000000801668840.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.10/ThreadPoolExecutor.java:1128) at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.10/ThreadPoolExecutor.java:628) at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(java.base@11.0.10/Executors.java:668) at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(java.base@11.0.10/Executors.java:665) at java.security.AccessController.doPrivileged(java.base@11.0.10/Native Method) at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(java.base@11.0.10/Executors.java:665) at java.lang.Thread.run(java.base@11.0.10/Thread.java:834) 
```
`python2 -V` command is called.
Essentially IntelliJ checks version of python instances available in the system at startup. Calling python 2 process on latest macos causes this warning:
![image](https://user-images.githubusercontent.com/10235198/138119251-b6c96c5f-90cd-4b1e-a383-9c6389e51970.jpg)
The "Learn more" button takes us to docs about python 2 and 3.
Can we somehow avoid it?

**Comment by AlexeyGy** [comment]
Looks like apple is tightening the screws on sunsetting Python2 https://developer.apple.com/forums/thread/691799. The solution here could be somewhere in [FallbackPythonSdkSuggester](https://github.com/bazelbuild/intellij/blob/master/python/src/com/google/idea/blaze/python/sdk/FallbackPythonSdkSuggester.java). Although, since we rely on upstream methods:
```
import com.jetbrains.python.psi.LanguageLevel;
import com.jetbrains.python.sdk.PyDetectedSdk;
import com.jetbrains.python.sdk.PySdkExtKt;

List<PyDetectedSdk> detectedSdks = PySdkExtKt.detectSystemWideSdks(null, ImmutableList.of());
detectedSdks.stream()
     .filter(sdk -> sdk.getHomePath() != null && getSdkLanguageLevel(sdk).isPython2())
```
 this probably is this upstream issue: https://youtrack.jetbrains.com/issue/IDEA-271050.

**Comment by kylecordes** [comment]
I've dug into this, and don't have a fix, but maybe some things here will help the next person take a step.

As noted above, the root cause appears to be in the IDEA- issue. Code provided by the JetBrains IDEs aggressively scrounges for Python versions (it has a list of places to look, it does not merely search the path), and when it finds anything Python2, tries to run it to find out what version it is. This angers MacOS Monterrey which is trying to push us away from Python2.

Possible solutions:

1. Wait patiently for JetBrains to stop doing the above. Then upgrade to the newer IDE to get the fix.

1. I've seen discussion elsewhere that a **fresh complete install of MacOS** makes the problem go away. I have not verified this, but suspect it is because MacOS no longer installs Python2 (but also leaves it in place on an upgrade). No Python2 to find means no problem from the JetBrains code.

1. Delete the Apple-installed Python 2 from your upgrade-based OS install; I suspect this is possible, but every mention of it around the web strongly cautions against trying.

1. Patch the JetBrains code, make it not even touch Python2 if it spots a candidate.

1. Enhance the Bazel IntelliJ plug-in to have its own code for walking available Pythons; perhaps just grab the obvious one from the path, don't look around and find a Python2 to trigger difficulties like this.

1. Enhance the Bazel IntelliJ plug-in to not look for Python installations at all, unless/until the user needs to do something for which they require Python.

Maybe someone familiar with this plug-in could advise whether one of the last two options is a short path.

**Comment by sgowroji** [comment]
Hello @lukaszwawrzyk, Are you still looking support for this issue and Did the [solutions](https://github.com/bazelbuild/intellij/issues/3020#issuecomment-1039696754) mentioned here helped you . Thanks!

**Comment by lukaszwawrzyk** [comment]
I think it doesn't happen anymore in our setup. Thanks!
