### ISSUE TITLE
Exception when running a specs2 text in IntelliJ 2018.1

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#303]
```
org.jetbrains.plugins.scala.lang.psi.api.expr.ScInfixExpr.lOp()Lorg/jetbrains/plugins/scala/lang/psi/api/expr/ScExpression;
java.lang.NoSuchMethodError: org.jetbrains.plugins.scala.lang.psi.api.expr.ScInfixExpr.lOp()Lorg/jetbrains/plugins/scala/lang/psi/api/expr/ScExpression;
	at com.google.idea.blaze.scala.run.Specs2Utils.getSpecs2TestName(Specs2Utils.java:69)
	at com.google.idea.blaze.scala.run.Specs2Utils.getSpecs2ScopedTestName(Specs2Utils.java:74)
	at com.google.idea.blaze.scala.run.producers.BlazeScalaTestRunLineMarkerContributor.getSpecs2TestUrl(BlazeScalaTestRunLineMarkerContributor.java:134)
	at com.google.idea.blaze.scala.run.producers.BlazeScalaTestRunLineMarkerContributor.getTestUrl(BlazeScalaTestRunLineMarkerContributor.java:97)
	at com.google.idea.blaze.scala.run.producers.BlazeScalaTestRunLineMarkerContributor.getInfo(BlazeScalaTestRunLineMarkerContributor.java:84)
	at com.google.idea.blaze.scala.run.producers.BlazeScalaTestRunLineMarkerContributor.getInfo(BlazeScalaTestRunLineMarkerContributor.java:71)
   ...
```

Seems that `ScInfixExpr.lOp()` was removed in 2018.x, and replaced with [`ScInfixExpr.left`](https://github.com/JetBrains/intellij-scala/blob/idea181.x/scala/scala-impl/src/org/jetbrains/plugins/scala/lang/psi/api/expr/ScInfixExpr.scala#L21).

How are API changes handled between plugin versions?

**Comment by chaoren** [comment]
See [sdkcompat](https://github.com/bazelbuild/intellij/tree/master/sdkcompat).
