### ISSUE TITLE
clion+bazel crash every day

### ISSUE THREAD

**Issue by chengwei920412** [bazelbuild/intellij#3038]
clion version: CLion 2020.3.4 Build #CL-203.8084.11
bazel version: Build label: 4.2.0
clion crash log:

2021-10-31 13:15:28,716 [ 937071]   INFO - tellij.psi.stubs.StubIndexImpl - StubIndexExtension-s were unloaded 
2021-10-31 13:15:28,731 [ 937086]   INFO - brains.cidr.execution.debugger - Debugger exited with code 0 
2021-10-31 13:15:28,735 [ 937090]   WARN - pl.local.NativeFileWatcherImpl - Watcher terminated with exit code 143 
2021-10-31 13:15:28,739 [ 937094]   INFO - il.indexing.FileBasedIndexImpl - END INDEX SHUTDOWN 
2021-10-31 13:15:28,742 [ 937097]   INFO - newvfs.persistent.PersistentFS - VFS dispose started 
2021-10-31 13:15:28,745 [ 937100]   INFO - newvfs.persistent.PersistentFS - VFS dispose completed 
2021-10-31 13:15:28,746 [ 937101]   INFO - stubs.SerializationManagerImpl - Start shutting down /home/maky/.cache/JetBrains/CLion2020.3/index/rep.names 
2021-10-31 13:15:28,746 [ 937101]   INFO - stubs.SerializationManagerImpl - Finished shutting down /home/maky/.cache/JetBrains/CLion2020.3/index/rep.names 
2021-10-31 13:15:28,746 [ 937101]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2021-10-31 13:15:28,748 [ 937103]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 
2021-10-31 13:15:28,751 [ 937106]   INFO - ngd.lsp.ClangDaemonContextImpl - Using clangd from: /home/maky/opt/clion/clion-2020.3.4/bin/clang/linux/clangd 
2021-10-31 13:15:28,778 [ 937133]  ERROR - aemon.impl.PassExecutorService - Vfs must be initialized 
java.lang.AssertionError: Vfs must be initialized
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getRecords(FSRecords.java:548)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getRecordInt(FSRecords.java:1300)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.doGetFlags(FSRecords.java:1233)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.lambda$getFlags$24(FSRecords.java:1228)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readAndHandleErrors(FSRecords.java:919)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getFlags(FSRecords.java:1228)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getLengthIfUpToDate(PersistentFSImpl.java:698)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getLength(PersistentFSImpl.java:444)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getLength(VirtualFileSystemEntry.java:300)
	at com.intellij.psi.SingleRootFileViewProvider.fileSizeIsGreaterThan(SingleRootFileViewProvider.java:212)
	at com.intellij.psi.SingleRootFileViewProvider.isTooLargeForIntelligence(SingleRootFileViewProvider.java:170)
	at com.intellij.psi.SingleRootFileViewProvider.isTooLargeForIntelligence(SingleRootFileViewProvider.java:157)
	at com.intellij.psi.SingleRootFileViewProvider.calcBaseLanguage(SingleRootFileViewProvider.java:72)
	at com.intellij.psi.SingleRootFileViewProvider.<init>(SingleRootFileViewProvider.java:46)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.createFileViewProvider(FileManagerImpl.java:264)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:192)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:368)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:154)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.findFile(PsiDirectoryImpl.java:177)
	at com.jetbrains.cidr.lang.OCIncludeHelpers.findInDir(OCIncludeHelpers.java:385)
	at com.jetbrains.cidr.lang.OCIncludeHelpers.findChild(OCIncludeHelpers.java:369)
	at com.jetbrains.cidr.lang.OCIncludeHelpers.find(OCIncludeHelpers.java:328)
	at com.jetbrains.cidr.lang.OCIncludeHelpers.find(OCIncludeHelpers.java:333)
	at com.jetbrains.cidr.lang.OCIncludeHelpers.findHeader(OCIncludeHelpers.java:247)
	at com.jetbrains.cidr.lang.OCIncludeHelpersKt.findHeaderInSegmentCache(OCIncludeHelpers.kt:83)
	at com.jetbrains.cidr.lang.OCIncludeHelpersKt.findHeaderUsingSegmentCache(OCIncludeHelpers.kt:51)
	at com.jetbrains.cidr.lang.OCIncludeHelpersKt.findHeaderUsingSegmentCache(OCIncludeHelpers.kt:27)
	at com.jetbrains.cidr.lang.OCIncludeHelpers.resolveNextIncludedFile(OCIncludeHelpers.java:191)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.resolvePath(OCInclusionContextImpl.java:852)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.lambda$conformsToByIncludes$6(OCInclusionContextImpl.java:467)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processIncludes(FileSymbolTable.java:311)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.conformsToByIncludes(OCInclusionContextImpl.java:456)
	at com.jetbrains.cidr.lang.preprocessor.OCInclusionContextImpl.checkConformanceAndFillSignatures(OCInclusionContextImpl.java:264)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesPack.findConformingTable(FileSymbolTablesPack.java:233)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.forFile(FileSymbolTablesCache.java:422)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache.forFile(FileSymbolTablesCache.java:406)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.findTableForInclude(FileSymbolTable.java:407)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:393)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:399)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:399)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:399)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:399)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:399)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:399)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:399)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:399)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.processInclude(FileSymbolTable.java:399)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:368)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable$1Builder.process(FileSymbolTable.java:338)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processFile(FileSymbolTable.java:296)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTable.processSymbols(FileSymbolTable.java:503)
	at com.jetbrains.cidr.lang.psi.impl.symbols.OCFileGlobalSymbolsCache.processFileImpl(OCFileGlobalSymbolsCache.java:163)
	at com.jetbrains.cidr.lang.psi.impl.symbols.OCFileGlobalSymbolsCache.processFile(OCFileGlobalSymbolsCache.java:112)
	at com.jetbrains.cidr.lang.psi.impl.symbols.OCLightFileGlobalSymbols.buildSymbols(OCLightFileGlobalSymbols.java:42)
	at com.jetbrains.cidr.lang.psi.impl.symbols.OCFileGlobalSymbolsCache$Cache$3.createValue(OCFileGlobalSymbolsCache.java:59)
	at com.jetbrains.cidr.lang.psi.impl.symbols.OCFileGlobalSymbolsCache$Cache$3.createValue(OCFileGlobalSymbolsCache.java:55)
	at com.jetbrains.cidr.lang.psi.impl.symbols.SLRUSynchronizedCache$myCache$1$1.create(SLRUSynchronizedCache.kt:8)
	at com.intellij.openapi.progress.util.AtomicCancelableLazyValue$1.compute(AtomicCancelableLazyValue.java:52)
	at com.intellij.openapi.progress.util.AtomicCancelableLazyValue.lambda$getValue$0(AtomicCancelableLazyValue.java:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.computeWithLockAndCheckingCanceled(ProgressIndicatorUtils.java:326)
	at com.intellij.openapi.progress.util.AtomicCancelableLazyValue.getValue(AtomicCancelableLazyValue.java:26)
	at com.jetbrains.cidr.lang.psi.impl.symbols.SLRUSynchronizedCache.get(SLRUSynchronizedCache.kt:15)
	at com.jetbrains.cidr.lang.psi.impl.symbols.OCFileGlobalSymbolsCache.typesOnlyTableForFile(OCFileGlobalSymbolsCache.java:96)
	at com.jetbrains.cidr.lang.psi.OCPsiFile.getMembersContainer(OCPsiFile.java:58)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReferenceResolver.processWorksets(OCSymbolReferenceResolver.java:206)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReferenceResolver.processSymbolsForGlobalRef(OCSymbolReferenceResolver.java:145)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReference.lambda$doResolve$5(OCSymbolReference.java:974)
	at com.jetbrains.cidr.lang.ui.OCLongActionUtil.execWithTimeoutProgressInDispatch(OCLongActionUtil.java:52)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReference.doResolve(OCSymbolReference.java:915)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReference.resolveToSymbols(OCSymbolReference.java:853)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReference.resolveToSymbols(OCSymbolReference.java:191)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReferenceResolver.addWorksets(OCSymbolReferenceResolver.java:281)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReferenceResolver.processSymbolsForGlobalRef(OCSymbolReferenceResolver.java:137)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReference.lambda$doResolve$5(OCSymbolReference.java:1042)
	at com.jetbrains.cidr.lang.ui.OCLongActionUtil.execWithTimeoutProgressInDispatch(OCLongActionUtil.java:52)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReference.doResolve(OCSymbolReference.java:915)
	at com.jetbrains.cidr.lang.symbols.OCSymbolReference.resolveToSymbols(OCSymbolReference.java:853)
	at com.jetbrains.cidr.lang.symbols.OCResolveContext.doResolveToSymbols(OCResolveContext.java:171)
	at com.jetbrains.cidr.lang.symbols.OCResolveContext.resolveToSymbols(OCResolveContext.java:187)
	at com.jetbrains.cidr.lang.symbols.OCResolveContext.resolveToSymbols(OCResolveContext.java:182)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.getResolvedQualifiedName(OCSymbolWithQualifiedNameImpl.java:180)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedName.getResolvedQualifiedName(OCSymbolWithQualifiedName.java:108)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedName.getResolvedQualifiedName(OCSymbolWithQualifiedName.java:78)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.isSameSymbol(OCSymbolWithQualifiedNameImpl.java:566)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl$1.process(OCSymbolWithQualifiedNameImpl.java:406)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl$1.process(OCSymbolWithQualifiedNameImpl.java:384)
	at com.jetbrains.cidr.lang.util.OCCommonProcessors$OrderedProcessor.finish(OCCommonProcessors.java:103)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.processSameSymbols(OCSymbolWithQualifiedNameImpl.java:428)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedName.processSameSymbols(OCSymbolWithQualifiedName.java:177)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.processSameSymbols(OCSymbolWithQualifiedNameImpl.java:368)
	at com.jetbrains.cidr.lang.search.OCSearchUtil.processPredeclarations(OCSearchUtil.java:367)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.processAssociatedSymbols(OCSymbolWithQualifiedNameImpl.java:448)
	at com.jetbrains.cidr.lang.symbols.cpp.OCSymbolWithQualifiedNameImpl.getAssociatedSymbol(OCSymbolWithQualifiedNameImpl.java:640)
	at com.jetbrains.cidr.lang.navigation.OCLineMarkerProvider.getRelatedSymbol(OCLineMarkerProvider.java:533)
	at com.jetbrains.cidr.lang.navigation.OCLineMarkerProvider.getRelatedSymbolAction(OCLineMarkerProvider.java:522)
	at com.jetbrains.cidr.lang.navigation.OCLineMarkerProvider.getDeclDefMarker(OCLineMarkerProvider.java:212)
	at com.jetbrains.cidr.lang.navigation.OCLineMarkerProvider.getLineMarkerInfo(OCLineMarkerProvider.java:74)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:158)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:83)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:78)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-10-31 13:15:28,781 [ 937136]  ERROR - aemon.impl.PassExecutorService - CLion 2020.3.4  Build #CL-203.8084.11

**Comment by sgowroji** [comment]
I will close this issue as there are no complete steps. Please reopen if you can reproduce with latest bazel plugin and clion release. Thanks !
