### ISSUE TITLE
com.google.protobuf.repackaged.TextFormat$ParseException: 56:1: Expected identifier. Found '}'

### ISSUE THREAD

**Issue by roblg** [bazelbuild/intellij#306]
Hand a report from a developer about the following error:

```
com.google.protobuf.repackaged.TextFormat$ParseException: 56:1: Expected identifier. Found '}'
java.util.concurrent.ExecutionException: com.google.protobuf.repackaged.TextFormat$ParseException: 56:1: Expected identifier. Found '}'
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.lambda$updateState$5(BlazeIdeInterfaceAspectsImpl.java:412)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.updateState(BlazeIdeInterfaceAspectsImpl.java:338)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.updateTargetMap(BlazeIdeInterfaceAspectsImpl.java:200)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$getIdeQueryResult$9(BlazeSyncTask.java:727)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.getIdeQueryResult(BlazeSyncTask.java:719)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:407)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:228)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:189)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:163)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:113)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.repackaged.TextFormat$ParseException: 56:1: Expected identifier. Found '}'
	at com.google.protobuf.repackaged.TextFormat$Tokenizer.parseException(TextFormat.java:1038)
	at com.google.protobuf.repackaged.TextFormat$Tokenizer.consumeIdentifier(TextFormat.java:763)
	at com.google.protobuf.repackaged.TextFormat$Parser.mergeField(TextFormat.java:1645)
	at com.google.protobuf.repackaged.TextFormat$Parser.mergeField(TextFormat.java:1592)
	at com.google.protobuf.repackaged.TextFormat$Parser.merge(TextFormat.java:1553)
	at com.google.protobuf.repackaged.TextFormat$Parser.merge(TextFormat.java:1448)
	at com.google.protobuf.repackaged.TextFormat$Parser.merge(TextFormat.java:1418)
	at com.google.idea.blaze.base.sync.aspects.strategy.AspectStrategy.readAspectFile(AspectStrategy.java:107)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.lambda$updateState$4(BlazeIdeInterfaceAspectsImpl.java:393)
	... 6 more
```

Ultimately `bazel clean` fixed it, but we don't have any idea what caused it. (Seems like a corrupt file of some sort though 🤷‍♂️ )

Details:

* Bazel 0.10.1
* IntelliJ 2017.3.5 (CE) 
* ijwb 2018.03.12.0.6

**Comment by brendandouglas** [comment]
It does look like a corrupt proto file. Not much we'll be able to do here without being able to reproduce. I'll close for now, but let us know if it happens again, or if you can track down reproduction steps.

**Comment by roblg** [comment]
This is still happening to us in one form or another a couple times a week (that I know of. I have no idea how many times it happens to folks that just clean without reporting it).

This is a slightly different stack trace, but I suspect the same cause:

```
com.google.protobuf.repackaged.TextFormat$ParseException: 56:1: Expected identifier. Found ':'
java.util.concurrent.ExecutionException: com.google.protobuf.repackaged.TextFormat$ParseException: 56:1: Expected identifier. Found ':'
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.lambda$updateState$4(BlazeIdeInterfaceAspectsImpl.java:408)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.updateState(BlazeIdeInterfaceAspectsImpl.java:336)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.updateTargetMap(BlazeIdeInterfaceAspectsImpl.java:198)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$getIdeQueryResult$9(BlazeSyncTask.java:733)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.getIdeQueryResult(BlazeSyncTask.java:725)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:413)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:234)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:190)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:164)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:113)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.repackaged.TextFormat$ParseException: 56:1: Expected identifier. Found ':'
	at com.google.protobuf.repackaged.TextFormat$Tokenizer.parseException(TextFormat.java:1038)
	at com.google.protobuf.repackaged.TextFormat$Tokenizer.consumeIdentifier(TextFormat.java:763)
	at com.google.protobuf.repackaged.TextFormat$Parser.mergeField(TextFormat.java:1645)
	at com.google.protobuf.repackaged.TextFormat$Parser.mergeField(TextFormat.java:1592)
	at com.google.protobuf.repackaged.TextFormat$Parser.merge(TextFormat.java:1553)
	at com.google.protobuf.repackaged.TextFormat$Parser.merge(TextFormat.java:1448)
	at com.google.protobuf.repackaged.TextFormat$Parser.merge(TextFormat.java:1418)
	at com.google.idea.blaze.base.sync.aspects.strategy.AspectStrategy.readAspectFile(AspectStrategy.java:111)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.lambda$updateState$3(BlazeIdeInterfaceAspectsImpl.java:390)
	... 6 more```
```

I found the file this time though! The file is `bazel-bin/<project>/<target>.intellij-info.txt`, busted line is line 56:

```
 52 key {
 53   label: "//notifications.push/deviceUpdater:DeviceUpdater"
 54 }
 55 kind_string: "java_binary"
 56 :jsr305"
 57   }
 58 }
 59 deps {
 60   dependency_type: 0
 61   target {
 62     label: "//zdeps/java/defaults/com/google/guava:guava"
 63   }
 64 }
```

**Comment by roblg** [comment]
🤦‍♂️ I think I figured it out. I believe this is happening because some of our devs are on a case-insensitive filesystem (the MacOS default). We happen to have two different targets that have the same name, but different case in several packages (no good reason for it; it just ended up that way organically). On a case-sensitive filesystem, the IntelliJ plugin will write two different files (`deviceUpdater.intellij-info.txt` and `DeviceUpdater.intellij-info.txt`) correctly, but they clobber each other (sometimes mid-write) on a case-sensitive partition.

**Comment by brendandouglas** [comment]
That's interesting, thanks for tracking down the problem. We don't officially support macs yet, and I suspect there are several case-sensitivity bugs in the plugin (e.g. https://github.com/bazelbuild/intellij/issues/357).

We can fix this particular problem by making the file names unique. I'd recommend also changing the target names though, as there are probably similar issues.

**Comment by roblg** [comment]
> I'd recommend also changing the target names though, as there are probably similar issues.

Yeah, we're going to work on that. I'd guess the only reason we've gotten away with this w/ bazel at all is that java_library is prefixed with `lib`, so we have `DeviceUpdater.jar` and `libdeviceUpdater.jar` when bazel is compiling things. 

Time to encourage folks to use a case-sensitive code partition, I suppose!

**Comment by brendandouglas** [comment]
We've made the file names unique for the next release, so this particular problem should be fixed.
