### ISSUE TITLE
Bazel plugin not available in remote development mode (JetBrains Gateway)

### ISSUE THREAD

**Issue by caandewiel** [bazelbuild/intellij#3152]
Are there any plans regarding support of Clion through JetBrains Gateway?

**Comment by caandewiel** [comment]
@alice-ks I meant the latter. You are right, I made the wrong assumption that gateway was using a different api which doesn't seem to be the case as it just launches de clion backend server side. But for now Gateway only seems to work with clion 2021.3.1+ so that's most likely the reason the plugin isn't working yet.

**Comment by alice-ks** [comment]
Yeah, the plugin hadn't been compatible with CLion 2021.3 yet. It reached compatibility recently and we pushed a compatible version to the beta channel of the public plugin repository yesterday. See https://github.com/bazelbuild/intellij/issues/3001#issuecomment-1011302963.

You could check it out and see whether it works with a Gateway setup in Clion 2021.3.1. I'd be interested to hear your feedback.

**Comment by caandewiel** [comment]
Good and bad news! It installs properly on the host machine and I can access the plugin settings. However, the frontend is missing in the Gateway client. Also, Gateway doesn't have the import new project wizard so you have to configure that over VNC/Projector. I get proper highlighting in bazel files, but there is currently (afaict) no way to sync the project.

**Comment by alice-ks** [comment]
Thanks for the feedback.

I guess the new project wizard is missing as Gateway has a connection to only one project. Therefore, the regular functionality to switch between projects is generally missing from the IDE, which in turn also means that creating new projects is not possible. I don't think we can do anything on the plugin's side for improvement at the moment.

I'm a bit surprised to hear that the frontend is missing. When I tested the plugin with IntelliJ 2021.3.0, the sync button showed up in the toolbar. Upon a click, it started a sync and even opened the corresponding tool window. Maybe Clion is different to IntelliJ.

**Comment by caandewiel** [comment]
Did you try the plugin with IntelliJ 2021.3.0 through the Gateway client?

**Comment by nikunjy** [comment]
I tried launching intelij 2021.3.2 from gateway client. I can't see bazel buttons. Note: this is specifically about the gateway client.

**Comment by alice-ks** [comment]
Did you ensure that the plugin is installed in the project you accessed with the Gateway client? When I tested this, the Gateway connection created a separate IDE environment, which only had the bundled plugins available. I needed to manually add the Bazel plugin.

**Comment by nikunjy** [comment]
Yup. I installed the bazel plugin. This caused the restart of the project.
When it opened again I didn’t see bazel options for that project.

What did you do to make it work?

**Comment by tandel-pratik** [comment]
When I installed IntelliJ manually via disk for the "Plugins" section (not "Plugins on host"). I'm seeing this error:

```
Failed to execute task com.intellij.openapi.project.DumbServiceMergingTaskQueue$QueuedDumbModeTask@2a9c3757. com/intellij/vfs/AsyncVfsEventsPostProcessor

java.lang.NoClassDefFoundError: com/intellij/vfs/AsyncVfsEventsPostProcessor
	at com.google.idea.blaze.base.sync.libraries.ExternalLibraryManager.<init>(ExternalLibraryManager.java:70)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.compute(ServiceComponentAdapter.kt:41)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:237)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:40)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:595)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:27)
	at com.google.idea.blaze.base.sync.libraries.ExternalLibraryManager.getInstance(ExternalLibraryManager.java:63)
	at com.google.idea.blaze.base.sync.libraries.BlazeExternalLibraryProvider.getAdditionalProjectLibraries(BlazeExternalLibraryProvider.java:38)
	at com.intellij.util.indexing.roots.AdditionalLibraryRootsContributor.getIndexableFiles(standardContributors.kt:125)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$getIndexableFilesProviders$12(FileBasedIndexEx.java:479)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:421)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:186)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$getIndexableFilesProviders$13(FileBasedIndexEx.java:479)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.intellij.util.indexing.FileBasedIndexEx.getIndexableFilesProviders(FileBasedIndexEx.java:481)
	at com.intellij.util.indexing.UnindexedFilesUpdater.getOrderedProviders(UnindexedFilesUpdater.java:359)
	at com.intellij.util.indexing.UnindexedFilesUpdater.updateUnindexedFiles(UnindexedFilesUpdater.java:193)
	at com.intellij.util.indexing.UnindexedFilesUpdater.performScanningAndIndexing(UnindexedFilesUpdater.java:532)
	at com.intellij.util.indexing.UnindexedFilesUpdater.performInDumbMode(UnindexedFilesUpdater.java:522)
	at com.intellij.openapi.project.DumbServiceMergingTaskQueue$QueuedDumbModeTask.executeTask(DumbServiceMergingTaskQueue.java:201)
	at com.intellij.openapi.project.DumbServiceMergingTaskQueue$QueuedDumbModeTask.executeTask(DumbServiceMergingTaskQueue.java:185)
	at com.intellij.openapi.project.DumbServiceGuiTaskQueue.lambda$runSingleTask$1(DumbServiceGuiTaskQueue.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.project.DumbServiceGuiTaskQueue.runSingleTask(DumbServiceGuiTaskQueue.java:62)
	at com.intellij.openapi.project.DumbServiceGuiTaskQueue.lambda$processTasksWithProgress$0(DumbServiceGuiTaskQueue.java:49)
	at com.intellij.util.io.storage.HeavyProcessLatch.performOperation(HeavyProcessLatch.java:79)
	at com.intellij.openapi.project.DumbServiceGuiTaskQueue.processTasksWithProgress(DumbServiceGuiTaskQueue.java:49)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runBackgroundProcess$13(DumbServiceImpl.java:613)
	at com.intellij.openapi.util.ShutDownTracker.executeWithStopperThread(ShutDownTracker.java:114)
	at com.intellij.openapi.project.DumbServiceImpl.runBackgroundProcess(DumbServiceImpl.java:609)
	at com.intellij.openapi.project.DumbServiceImpl$5.run(DumbServiceImpl.java:587)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:238)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:238)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.intellij.vfs.AsyncVfsEventsPostProcessor PluginClassLoader(plugin=PluginDescriptor(name=Bazel, id=com.google.idea.bazel.ijwb, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/JetBrainsClient213.6777.38/plugins/ijwb, version=2022.01.13.0.1-api-version-213, package=null, isBundled=false), packagePrefix=null, instanceId=4, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

	... 100 more
```


![Bazel On Host Plugin](https://user-images.githubusercontent.com/62570452/151261279-66bee2e5-16a1-4922-9dc8-0e00fb42dffc.png)

**Comment by long-stripe** [comment]
Hey there,

I gave IntelliJ Ultimate 2021.3.2 a shot today with the latest Bazel plugin to try out the beta support for remote development. My setup is roughly macOS to a Linux host and am seeing the same things as the commenters before me -- there's some evidence the Bazel plugin is loading since you can pull up its preferences pane, but core functionality for the Bazel plugin like opening as a Bazel project and syncing isn't working when running as a JetBrains Client and the headless IJ instance on the remote host.

I think this might on the Bazel plugin side of things. Would it be okay to re-open this issue?

**Comment by alice-ks** [comment]
Sure, let's reopen it. I just can't promise that there's anything on the plugin's side we can do to make it work. So far, I'm only aware that dialogs/windows opened by a plugin can prevent the IntelliJ remote server from even starting up properly. Since others reported that a connection to the remote server was possible, that wouldn't be the issue.

I'm a bit surprised about the `ClassNotFoundException` for `AsyncVfsEventsPostProcessor`. I haven't tested exactly the Bazel plugin in this remote dev mode, but I've used our internal plugin bundle which contains the Bazel plugin. This superset of the Bazel plugin works within the remote dev mode and doesn't run into the `ClassNotFoundException`.

`AsyncVfsEventsPostProcessor` is a class from the IntelliJ platform API. It should be available. If not, that would be an issue with the IntelliJ remote server. Are you sure that the server is starting up properly? Does it run in an environment which allows the IntelliJ platform to properly start up?

Please note that you need to install the Bazel plugin on the remote server/host. If you instead installed it on the local client, that would explain the `ClassNotFoundException`.

> Additionally typically in IntelliJ, we select a bazel project in the IntelliJ startup screen. The gateway doesn't offer that choice and has a different UI for opening projects.

Gateway is a separate product with its own API. At the moment, we can't extend it yet. Even when this becomes possible, we'd need to introduce a separate plugin targeted for Gateway as Gateway doesn't use/include IntelliJ plugins.

**Comment by goldencz** [comment]
Is there any plan to support remote developoment?
There's a workaround which allows bazel working on remote development, sounds like it doesn't need to develop a new plugin for Jetbrains Gateway.
#3249

**Comment by mai93** [comment]
@liucijus Should this be considered fixed with https://github.com/bazelbuild/intellij/pull/3601?

**Comment by liucijus** [comment]
> @liucijus Should this be considered fixed with #3601?

Yes, this should be fixed, @mai93

**Comment by oquenchil** [comment]
This was just about one part of the plugin that has a workaround. There is a lot of other stuff missing: https://ij.bazel.build/docs/build-file-support.html

I'm especially missing highlighting and navigation. Can this issue be re-opened? The title of the issue is generic enough to encompass all the functionality, not just importing projects.

**Comment by hypdeb** [comment]
I wanted to try that just this afternoon and the strangest thing happens: the project folder appears empty in the project view, as if all the files were somehow excluded. It starts as soon as I install the CLion Bazel extension. If I don't install it, then I can see the files.

**Comment by awelless** [comment]
Are there any plans to support Jetbrains Gateway out of the box?

Currently on [the plugin page](https://plugins.jetbrains.com/plugin/8609-bazel-for-intellij) I get "Not compatible with the version of your running IDE (Client 2023.2.5, Gateway 2023.2.5)".
I often need to open and close different subprojects and it's kinda inconvenient to follow the sequence specified in #3249 each time. It would be much better to have a plugin in the Client installed.

If there are no plans to do that, I could try to contribute myself.
