### ISSUE TITLE
Support IntelliJ 2016.3

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/intellij#32]
As soon as I imported my first Bazel project, I got an "IDE Fatal Errors" popup with this exception:

```
Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities={ModalityState.NON_MODAL=true, ModalityState:Loading Project 2012642121: running=false; canceled=false=true, ModalityState:com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,475,229,1024x728,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Import Project from Bazel,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]=true}
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:246)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:296)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:288)
	at com.google.idea.blaze.base.util.SaveUtil$1.run(SaveUtil.java:28)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I'm on Ubuntu 16.04.1 64-bit, IntelliJ IDEA CE 2016.3.

**Comment by brendandouglas** [comment]
Thanks for letting us know. This is caused by a change in IntelliJ's API between 2016.2 and 2016.3.
For now, the only workaround is to use IntelliJ 2016.2

**Comment by dfabulich** [comment]
Indeed, when I downgrade to 2016.2, this exception goes away.

**Comment by dfabulich** [comment]
@brendandouglas so is this fixed now? What commit fixed this? This one from today? https://github.com/bazelbuild/intellij/commit/00d82dd57e49657c3416830669bbfc3830747585

Can you describe the release cycle for this plugin? Should I expect to just open IntelliJ in a few hours and have the bug fixes auto-update?

**Comment by brendandouglas** [comment]
The most recent release (2017.01.30) supports 2016.3 -- please let us know if there are any issues.
