### ISSUE TITLE
"Error parsing runtime jars" when debugging certain Java binary targets

### ISSUE THREAD

**Issue by daviswahl** [bazelbuild/intellij#321]
Sorry in advance: I'm not great at Java and don't know very much about jars. However I have a simple testcase. 

testcase:
https://github.com/daviswahl/intellij-bazel-debug-error-testcase

steps: 
1. Check out the repo
2. Import the bazel workspace with the bazel intellij plugin
3. Sync to //:testcase
4. Debug the //:testcase run target. 

Observe the following in the intellij logs:
```
2018-05-22 18:29:03,304 [  93796]   INFO - azeJavaRunConfigurationHandler - Error parsing runtime jars
com.intellij.execution.ExecutionException: Error parsing runtime jars
	at com.google.idea.blaze.java.run.hotswap.ClassFileManifest.build(ClassFileManifest.java:117)
	at com.google.idea.blaze.java.run.hotswap.ClassFileManifestBuilder.buildManifest(ClassFileManifestBuilder.java:122)
	at com.google.idea.blaze.java.run.BlazeJavaRunConfigurationHandler$BlazeJavaRunConfigurationRunner.executeBeforeRunTask(BlazeJavaRunConfigurationHandler.java:113)
	at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:112)
	at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:35)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:314)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Multiple entries with same key: org/apache/xmlbeans/xml/stream/Location.class=4200516764 and org/apache/xmlbeans/xml/stream/Location.class=4200516764
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.idea.blaze.java.run.hotswap.ClassFileManifest.buildJarManifests(ClassFileManifest.java:129)
	at com.google.idea.blaze.java.run.hotswap.ClassFileManifest.build(ClassFileManifest.java:109)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: org/apache/xmlbeans/xml/stream/Location.class=4200516764 and org/apache/xmlbeans/xml/stream/Location.class=4200516764
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:503)
	at com.google.idea.blaze.java.run.hotswap.ClassFileManifest$JarManifest.build(ClassFileManifest.java:145)
	at com.google.idea.blaze.java.run.hotswap.ClassFileManifest.lambda$buildJarManifests$2(ClassFileManifest.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	... 3 more
```

See: https://github.com/bazelbuild/intellij/blob/master/java/src/com/google/idea/blaze/java/run/hotswap/ClassFileManifest.java#L145

The issue seems to be caused by particular jars, in this case the xmlbeans jar.  
The `JarFile#stream` method is yielding multiple entries for `org/apache/xmlbeans/xml/stream/Location.class=4200516764`. Simply de-duping the stream by jar name fixes the error, but I am not sure that this is the correct solution.

**Comment by brendandouglas** [comment]
Thanks, I can reproduce. It seems likely a poorly constructed jar, having two identical copies of the same class file. In any case, we'll just handle this gracefully and move on.

I don't think this is possible for jars created by bazel's built-in java rules, so it's only an issue for external libraries and custom rules.

I'll put in a fix today, but it won't make it in until the release after next.
