### ISSUE TITLE
Cannot debug python 3.8 application in Clion with bazel

### ISSUE THREAD

**Issue by fkeidelbmw** [bazelbuild/intellij#3241]
I cannot debug a python 3.8 application in Clion (CLion 2021.2.4) with bazel (Bazel Plugin Version: 2021.12.14.0.0-api-version-21).
It is possible to RUN the bazel target. But when I start the bazel DEBUG target, I get:

/usr/bin/setsid --wait /usr/bin/python3.8 /home/q456941/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.5712.21/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 36487 --file /home/q456941/.cache/bazel/_bazel_q456941/7feed9b793d9a0995f44316b06a89ae6/execroot/ddad/bazel-out/k8-fastbuild/bin/application/adp/debug_test/debug_test
Connected to pydev debugger (build 212.5712.21)
Traceback (most recent call last):
File "/home/q456941/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.5712.21/plugins/python-ce/helpers/pydev/pydevd.py", line 28, in <module>
from _pydevd_bundle.pydevd_constants import IS_JYTH_LESS25, IS_PYCHARM, get_thread_id, get_current_thread_id, \
File "/home/q456941/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.5712.21/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_constants.py", line 60, in <module>
from _pydevd_bundle import pydevd_vm_type
File "/home/q456941/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.5712.21/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vm_type.py", line 1, in <module>
import sys
KeyboardInterrupt

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

If I change the Python Interpreter setting of .workspace to Python 2.7, the debugger works.

How to get the debugger running with Python 3.8?

---
In another run I got:
/usr/bin/setsid --wait /usr/bin/python3.8 /home/q456941/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.5712.21/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 43487 --file /home/q456941/.cache/bazel/_bazel_q456941/7feed9b793d9a0995f44316b06a89ae6/execroot/ddad/bazel-out/k8-fastbuild/bin/application/adp/debug_test/debug_test
Connected to pydev debugger (build 212.5712.21)
Traceback (most recent call last):
File "/home/q456941/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.5712.21/plugins/python-ce/helpers/pydev/pydevd.py", line 28, in <module>
from _pydevd_bundle.pydevd_constants import IS_JYTH_LESS25, IS_PYCHARM, get_thread_id, get_current_thread_id, \
File "/home/q456941/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.5712.21/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_constants.py", line 5, in <module>
import platform
File "/usr/lib/python3.8/platform.py", line 945, in <module>
_sys_version_parser = re.compile(
File "/usr/lib/python3.8/re.py", line 252, in compile
return _compile(pattern, flags)
File "/usr/lib/python3.8/re.py", line 304, in _compile
p = sre_compile.compile(pattern, flags)
File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
p = sre_parse.parse(p, flags)
File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
itemsappend(_parse(source, state, verbose, nested + 1,
File "/usr/lib/python3.8/sre_parse.py", line 680, in _parse
subpattern[-1] = (MAX_REPEAT, (min, max, item))
File "/usr/lib/python3.8/sre_parse.py", line 168, in __setitem__
def __setitem__(self, index, code):
KeyboardInterrupt

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

===================

Clion App Info:

CLion 2021.2.4
Build #CL-212.5712.21, built on December 15, 2021
Licensed to BMW AG / Frank Keidel
You have a perpetual fallback license for this version.
Subscription is active until December 31, 2022.
Runtime version: 11.0.13+8-b1504.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-1057-oem
GC: G1 Young Generation, G1 Old Generation
Memory: 19000M
Cores: 40
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.google.idea.bazel.clwb (2021.12.14.0.0-api-version-212)
Current Desktop: ubuntu:GNOME

=====================

file content debug_test.py:

```
def main():
    print("hello")

if __name__ == "__main__":
    main()
```

=====================

BUILD file:

```
py_binary(
   name = "debug_test",
   testonly = True,
   srcs = [
      "debug_test.py",
   ],
   main = "debug_test.py",
   srcs_version = "PY3",
   visibility = ["//visibility:public"],
   deps = [
   ],
)
```

=====================

In another run I got:

/usr/bin/setsid --wait /usr/bin/python3.8 /home/q456941/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.5712.21/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 38359 --file /home/q456941/.cache/bazel/_bazel_q456941/7feed9b793d9a0995f44316b06a89ae6/execroot/ddad/bazel-out/k8-fastbuild/bin/application/adp/debug_test/debug_test
Connected to pydev debugger (build 212.5712.21)
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
File "/usr/lib/python3.8/site.py", line 597, in <module>
main()
File "/usr/lib/python3.8/site.py", line 592, in main
execusercustomize()
File "/usr/lib/python3.8/site.py", line 549, in execusercustomize
import usercustomize
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 914, in _find_spec
File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
File "<frozen importlib._bootstrap_external>", line 1382, in _get_spec
KeyboardInterrupt

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

**Comment by sgowroji** [comment]
Hello @fkeidelbmw, Are you still looking support for the above issue. Could you please share complete steps to reproduce the above request. Thanks!

**Comment by fkeidelbmw** [comment]
Yes I still have the problem and am looking for a solution. First, I will check if there are newer versions of Clion/bazel plugin, then I will supply you with updated information and the steps.

**Comment by sgowroji** [comment]
Thank you for the reply. Please post us the latest update.

**Comment by fkeidelbmw** [comment]
I updated Clion and the Bazel plugin to the newest versions, and now debugging python targets with python 3.8 interpreter works again for me. That's great.
CLion 2022.2.4
Bazel plugin:  2022.09.20.0.1-api-version-222
Bazel: 5.3.0
Python: 3.8.10
