### ISSUE TITLE
Bazel sync throws java.lang.IndexOutOfBoundsException exception

### ISSUE THREAD

**Issue by pkrishnaiah** [bazelbuild/intellij#3243]
I see this exception in IDE stacktrace when I run Bazel > "Sync Projects with BUILD files".  The sync seems to be successful but Bazel console ends with "Sync failed" in the final line. There is no other error log in the console. 

Bazel build from the command line works fine without any errors. 

Environment detials:

```
IntelliJ IDEA 2021.3.1 (Community Edition)
Build #IC-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.2

Bazel plugin version: 2022.01.25.0.0-api-version-213

```

```
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.lambda$updateState$7(BlazeIdeInterfaceAspectsImpl.java:368)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.updateState(BlazeIdeInterfaceAspectsImpl.java:300)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.updateTargetMap(BlazeIdeInterfaceAspectsImpl.java:258)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.updateTargetData(BlazeIdeInterfaceAspectsImpl.java:135)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.lambda$updateTargetData$0(ProjectUpdateSyncTask.java:98)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.updateTargetData(ProjectUpdateSyncTask.java:92)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.updateTargetData(SyncPhaseCoordinator.java:538)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$updateProjectAndFinishSync$7(SyncPhaseCoordinator.java:503)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$runWithTiming$1(SyncScope.java:61)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$push$2(SyncScope.java:74)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:89)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:71)
	at com.google.idea.blaze.base.sync.SyncScope.runWithTiming(SyncScope.java:63)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.updateProjectAndFinishSync(SyncPhaseCoordinator.java:500)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:404)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:229)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:33)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:219)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at com.google.idea.blaze.base.ideinfo.PyIdeInfo.lambda$parseArgs$0(PyIdeInfo.java:68)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.idea.blaze.base.ideinfo.PyIdeInfo.parseArgs(PyIdeInfo.java:69)
	at com.google.idea.blaze.base.ideinfo.PyIdeInfo.fromProto(PyIdeInfo.java:62)
	at com.google.idea.blaze.base.ideinfo.TargetIdeInfo.fromProto(TargetIdeInfo.java:134)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.protoToTarget(BlazeIdeInterfaceAspectsImpl.java:475)
	at com.google.idea.blaze.base.sync.aspects.BlazeIdeInterfaceAspectsImpl.lambda$updateState$6(BlazeIdeInterfaceAspectsImpl.java:351)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:246)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:225)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	... 1 more
```

**Comment by sgowroji** [comment]
Hello @pkrishnaiah, Is above your issue resolved with latest intellij and bazel plugin ? Could you please provide more information on the above request if you are still looking for support. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
