### ISSUE TITLE
Support CLion 2018.1.3 (plugin API changed since 2018.1.2)

### ISSUE THREAD

**Issue by akowpak-ssimwave** [bazelbuild/intellij#325]
I just installed CLion 2018.1.3 with the new bazel plugin, and, almost immediately received this error:

```
com.jetbrains.cidr.lang.workspace.OCWorkspaceImpl$ModifiableModel.commit()V
java.lang.NoSuchMethodError: com.jetbrains.cidr.lang.workspace.OCWorkspaceImpl$ModifiableModel.commit()V
	at com.google.idea.blaze.cpp.BlazeCWorkspace.update(BlazeCWorkspace.java:206)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.lambda$updateInMemoryState$0(BlazeCSyncPlugin.java:68)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.updateInMemoryState(BlazeCSyncPlugin.java:62)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$updateInMemoryState$14(BlazeSyncTask.java:912)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:902)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$updateInMemoryState$15(BlazeSyncTask.java:905)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.updateInMemoryState(BlazeSyncTask.java:899)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:245)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:190)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:164)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:113)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Rolled back to CLion 2017.3.4 and everything is still working fine.

Please let me know if I can provide further details.

**Comment by dtormoen** [comment]
I got this same error. Rolling back to 2018.1.2 worked for me if you don't want to revert all the way back to Clion 2017.

**Comment by nickgolob** [comment]
This happened to me on 2018.1.5 just now.   Is this still not fixed?  Should I roll back to 2018.1.2? Thanks!

**Comment by brendandouglas** [comment]
It will be fixed in the next release, scheduled for tomorrow (we add the 'fixed pending release' flag to indicate this, then close bugs when there's a release with the fix).

**Comment by nickgolob** [comment]
Awesome, thanks!

**Comment by beiju** [comment]
Is this still on the way? The last update says the release was scheduled for nearly a week ago, but the plugin on the Jetbrains Plugin Repository hasn't been updated since June 4.

**Comment by rohanjoyce** [comment]
Sorry for the delay. It has been submitted to the plugin repository and is just waiting on approval.

**Comment by beiju** [comment]
Ok, thanks for the update.
