### ISSUE TITLE
plugin crash

### ISSUE THREAD

**Issue by brown** [bazelbuild/intellij#338]
It has been reported to me that the plugin sometimes crashes when running bazel targets.
Here is the stack trace.  I do not have more info at this time.

null
java.lang.NullPointerException
at com.google.idea.blaze.java.run.hotswap.ClassFileManifest.lambda$build$0(ClassFileManifest.java:105)
at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
at com.google.idea.blaze.java.run.hotswap.ClassFileManifest.build(ClassFileManifest.java:102)
at com.google.idea.blaze.java.run.hotswap.ClassFileManifestBuilder.buildManifest(ClassFileManifestBuilder.java:119)
at com.google.idea.blaze.java.run.BlazeJavaRunConfigurationHandler$BlazeJavaRunConfigurationRunner.executeBeforeRunTask(BlazeJavaRunConfigurationHandler.java:106)
at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:112)
at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:35)
at com.intellij.execution.impl.ExecutionManagerImpl.lambda$compileAndRun$0(ExecutionManagerImpl.java:314)
at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by brendandouglas** [comment]
This would happen if we fail to read a timestamp for one of the output jars, or the timestamp is 0, for whatever reason.

Interestingly this hasn't happened internally. Whatever the cause, it's almost completely harmless to ignore these errors and move on -- we only need the jar's timestamp to enable hotswapping.

**Comment by keithkml** [comment]
Thanks for looking into it @brendandouglas!! This has been affecting many of my coworkers in various parts of their workflow.
