### ISSUE TITLE
Bazel plugin crashing when running debug configuration

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/intellij#344]
I believe this relates to #338. On occasion when running in debug configuration, the plugin crashes spewing out the following stacktrace

```java
null
java.lang.NullPointerException
at com.google.idea.blaze.java.run.hotswap.ClassFileManifest.lambda$build$0(ClassFileManifest.java:105)
at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
at com.google.idea.blaze.java.run.hotswap.ClassFileManifest.build(ClassFileManifest.java:102)
at com.google.idea.blaze.java.run.hotswap.ClassFileManifestBuilder.buildManifest(ClassFileManifestBuilder.java:119)
at com.google.idea.blaze.java.run.BlazeJavaRunConfigurationHandler$BlazeJavaRunConfigurationRunner.executeBeforeRunTask(BlazeJavaRunConfigurationHandler.java:106)
at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:112)
at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:35)
at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:314)
at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

The log in our Bazel console is
```
Building debug binary
Command: /<>/bin/bazel build --tool_tag=ijwb:IDEA:ultimate --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --aspects=@intellij_aspect//:java_classpath.bzl%java_classpath_aspect --override_repository=intellij_aspect=/<>/.IntelliJIdea2017.3/config/plugins/ijwb/aspect --output_groups=runtime_classpath --experimental_build_event_binary_file=/tmp/intellij-bep-ef090539-0a04-4c1b-a222-c96ee374bba3 --noexperimental_build_event_binary_file_path_conversion – //<>/service/java:app_TimeAllocation

INFO: Loading complete. Analyzing...
INFO: Found 1 target...
INFO: Building...
INFO: Elapsed time: 1.596s, Critical Path: 0.01s
```

Here are the details of our IntelliJ version:
```
IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.25, built on January 15, 2018
Licensed to <> and affiliates / <>
Subscription is active until November 4, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.1.35-pv-ts2
```

**Comment by petroseskinder** [comment]
After crashing, we need to disable and reenable the bazel plugin in order to use it again. Usually, this requires 2 intellij restarts.

Interestingly enough, the plugin works fine when debugging `bazel test` configurations. However, when debugging `bazel run` and on occasion,`bazel build` configruations, we run into this issue with the plugin crashing.
