### ISSUE TITLE
Enabling local jar cache breaks sync

### ISSUE THREAD

**Issue by liucijus** [bazelbuild/intellij#3533]
Since [this](https://github.com/bazelbuild/intellij/commit/79e6ce1886d58c6315cfec7e2062d69fc9c6a1ba) change, if user enables local jar cache, sync fails with:
```
com.intellij.diagnostic.PluginException: The specified parameters not match any of the following constructors: 
for interface com.google.idea.blaze.java.libraries.JarRepackager [Plugin: com.google.idea.bazel.ijwb]
	at com.intellij.serviceContainer.ConstructorInjectionKt.getGreediestSatisfiableConstructor(constructorInjection.kt:183)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:38)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.compute(ServiceComponentAdapter.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:44)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.google.idea.blaze.java.libraries.JarRepackager.getInstance(JarRepackager.java:25)
	at com.google.idea.blaze.java.libraries.JarCache.copyAndRepackageLocally(JarCache.java:296)
	at com.google.idea.blaze.java.libraries.JarCache.refresh(JarCache.java:224)
	at com.google.idea.blaze.java.libraries.JarCache.onSync(JarCache.java:159)
	at com.google.idea.blaze.java.libraries.JarCache.access$000(JarCache.java:80)
	at com.google.idea.blaze.java.libraries.JarCache$FileCacheAdapter.onSync(JarCache.java:485)
	at com.google.idea.blaze.base.filecache.FileCaches.lambda$onSync$0(FileCaches.java:50)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.filecache.FileCaches.onSync(FileCaches.java:45)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.run(ProjectUpdateSyncTask.java:217)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.runProjectUpdatePhase(ProjectUpdateSyncTask.java:122)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$updateProjectAndFinishSync$8(SyncPhaseCoordinator.java:552)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$runWithTiming$1(SyncScope.java:67)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$push$2(SyncScope.java:80)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:95)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:77)
	at com.google.idea.blaze.base.sync.SyncScope.runWithTiming(SyncScope.java:69)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.updateProjectAndFinishSync(SyncPhaseCoordinator.java:543)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:459)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:253)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:233)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by alice-ks** [comment]
This issue will be fixed by #3547. Please disable the jar cache in the meantime.

**Comment by fivetran-andydreyfuss** [comment]
For anybody stumbling upon this like me, and not 100% clear on the temporary workaround, it's

Settings --> Bazel Settings --> Uncheck the "Use a local jar cache."

**Comment by TRL-Official** [comment]
> For anybody stumbling upon this like me, and not 100% clear on the temporary workaround, it's
> 
> Settings --> Bazel Settings --> Uncheck the "Use a local jar cache."

Thank you very much for this information.
