### ISSUE TITLE
blaze plugin implicated in IDE crash.

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/intellij#36]
on starting up:

Internal error. Please report to http://jb.gg/ide/critical-startup-errors

java.lang.RuntimeException: java.lang.RuntimeException: Duplicate registration for EP: com.google.idea.blaze.base.lang.buildfile.DumbAnnotator
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:200)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:47)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: Duplicate registration for EP: com.google.idea.blaze.base.lang.buildfile.DumbAnnotator
    at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.java:282)
    at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.java:128)
    at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.registerExtensionPoints(IdeaPluginDescriptorImpl.java:330)
    at com.intellij.ide.plugins.PluginManagerCore.registerExtensionPointsAndExtensions(PluginManagerCore.java:1309)
    at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:1221)
    at com.intellij.ide.plugins.PluginManagerCore.initPlugins(PluginManagerCore.java:1350)
    at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:115)
    at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:109)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponentConfigs(ComponentManagerImpl.java:328)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:94)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:384)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:193)
    ... 16 more

[  20124]  ERROR -       #com.intellij.util.Alarm - IntelliJ IDEA 2016.2.4  Build #IC-162.2032.8 
[  20124]  ERROR -       #com.intellij.util.Alarm - JDK: 1.8.0_112-google-v7 
[  20124]  ERROR -       #com.intellij.util.Alarm - VM: OpenJDK 64-Bit Server VM 
[  20125]  ERROR -       #com.intellij.util.Alarm - Vendor: Google Inc. 
[  20125]  ERROR -       #com.intellij.util.Alarm - OS: Linux 

$ bazel version
..........
Build label: 0.4.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 2 17:54:14 2016 (1478109254)
Build timestamp: 1478109254
Build timestamp as int: 1478109254

sha1sum  ~/.IdeaIC2016.2/config/plugins/ijwb_bazel.jar 
fbb7a66b56680bb52e6b48f7d39571d5a02136e4  /home/hanwen/.IdeaIC2016.2/config/plugins/ijwb_bazel.jar

**Comment by brendandouglas** [comment]
Hi! This is likely caused by having both the blaze and bazel plugins
installed. They're incompatible, so you'll need to remove one (if you're
using blaze, you may as well remove the bazel-only plugin, as you won't
lose any functionality).

**Comment by hanwen** [comment]
I checked, but this is on my laptop, which doesn't have the blaze plugin.

After I deleted the jar , intellij starts up, and has a Bazel menu, and Bazel console output, but it complains of that the plugin is missing. I have no idea how that might be possible.

**Comment by brendandouglas** [comment]
OK, thanks for checking. It's almost certainly conflicting plugins, so there's probably a second bazel plugin somewhere.

Could you try uninstalling the remaining bazel plugin, then reinstalling the latest version?

**Comment by hanwen** [comment]
where should I look for these plugins? Is deleting the .jar enough, or do I have to edit XML files too?

**Comment by brendandouglas** [comment]
Just uninstalling through IntelliJ (then restarting) should be enough (Settings > Plugins). If you've got a Bazel menu showing up, you should also have a Bazel plugin there.

**Comment by hanwen** [comment]
I do have the blaze plugin, but the 'uninstall' is greyed out. I can (Has it been bundled with IJ ?). 

Looks like this was installed automatically, internally.
