### ISSUE TITLE
Bazel plugin causes IJ to freeze on large project view files

### ISSUE THREAD

**Issue by kamildoleglo** [bazelbuild/intellij#3622]
When importing a large project (`.bazelproject` file with around 20k lines => 10k directories + 10k targets) the plugin causes IntelliJ to freeze. A common stacktrace part seems to be a `calculateMinimalWorkspacePaths` call, which in turn calls `.toCanonicalPath` which is a slow operation and may or may not be the cause of the freezes: 

```
	at com.intellij.openapi.util.io.FileUtilRt.toCanonicalPath(FileUtilRt.java:229)
	at com.intellij.openapi.util.io.FileUtil.toCanonicalPath(FileUtil.java:599)
	at com.intellij.openapi.util.io.FileUtil.isAncestorThreeState(FileUtil.java:135)
	at com.intellij.openapi.util.io.FileUtil.isAncestor(FileUtil.java:117)
	at com.google.idea.blaze.base.util.WorkspacePathUtil.includePath(WorkspacePathUtil.java:67)
	at com.google.idea.blaze.base.util.WorkspacePathUtil.lambda$calculateMinimalWorkspacePaths$1(WorkspacePathUtil.java:50)
	at com.google.idea.blaze.base.util.WorkspacePathUtil$$Lambda$2222/0x0000000801a58c40.test(Unknown Source)
	at java.base@11.0.13/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base@11.0.13/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base@11.0.13/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.13/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.13/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.13/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.13/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.idea.blaze.base.util.WorkspacePathUtil.calculateMinimalWorkspacePaths(WorkspacePathUtil.java:51)
	at com.google.idea.blaze.base.sync.projectview.ImportRoots$Builder.build(ImportRoots.java:114)
	at com.google.idea.blaze.base.treeview.WorkspaceRootNode.getChildrenImpl(WorkspaceRootNode.java:74)
```

**Comment by sgowroji** [comment]
Hello @kamildoleglo, Could you please confirm if you are still seeing the crash and screen freeze even with the latest IntelliJ release. And can you share complete steps followed to check the above with the code repo. Thanks !

**Comment by kamildoleglo** [comment]
Yes, the freezes still happen. Unfortunately, I can't share with you the project nor the projectview, however the reproduction should be fairly easy, just open a large codebase and put many targets in the projectview file. The `toCanonicalPath` invocation is still in the logs. Maybe just changing it to `toAbsolutePath` would be sufficient to fix some of the freezes, since the call is significantly lighter

**Comment by crazyjat** [comment]
I'm also having this issue with 2024.1.1. Importing a large bazel project causes IntelliJ to freeze and be completely unresponsive.
