### ISSUE TITLE
Issue with importing existing Bazel project

### ISSUE THREAD

**Issue by stfedosov** [bazelbuild/intellij#3626]
I face the following problem when open an existing Bazel project in IntellijIDEA. 
File -> Import Bazel project... -> from scratch

This is the stack trace that I'm getting:

```
java.lang.IllegalStateException: Missing required properties: blazeInfo
	at com.google.idea.blaze.base.sync.AutoValue_BlazeSyncBuildResult$Builder.build(AutoValue_BlazeSyncBuildResult.java:125)
	at com.google.idea.blaze.base.sync.BuildPhaseSyncTask.run(BuildPhaseSyncTask.java:128)
	at com.google.idea.blaze.base.sync.BuildPhaseSyncTask.runBuildPhase(BuildPhaseSyncTask.java:87)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:431)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:256)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:236)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:127)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:127)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Due to that reason Bazel sync fails.

Is there any fix for this?

Current configuration:
Bazel plugin 2022.05.03.0.1-api-version-221 
Please plugin v2.1.3. 
Java 11.0.8 
IntellijIDEA 2022.1.1
Bazel binary location is set to this directory `/usr/local/bin/bazel`

**Comment by fivetran-andydreyfuss** [comment]
@stfedosov did you solve this? I'm hitting it as well.

**Comment by stfedosov** [comment]
@fivetran-andydreyfuss yes, you need to update Bazel plugin to **2022.05.17.0.3-api-version-221**
