### ISSUE TITLE
'Application.acquireReadActionLock' is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by rdesgroppes** [bazelbuild/intellij#3653]
With IntelliJ IDEA 2022.1.1 (Community Edition) together with plugin Bazel 2022.05.17.0.3-api-version-221 that are both pretty recent, I sometimes get suggested by the former to report the following issue on the latter:
```java
java.lang.Throwable: 'Application.acquireReadActionLock' is deprecated and going to be removed soon. Use `runReadAction()` instead
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl.acquireReadActionLock(ApplicationImpl.java:1182)
	at com.google.idea.blaze.python.run.BlazePyPositionConverter.convertLocalLineToRemote(BlazePyPositionConverter.java:111)
	at com.google.idea.blaze.python.run.BlazePyPositionConverter.convertToPython(BlazePyPositionConverter.java:65)
	at com.jetbrains.python.debugger.AbstractLineBreakpointHandler.registerBreakpoint(AbstractLineBreakpointHandler.java:39)
	at com.jetbrains.python.debugger.AbstractLineBreakpointHandler.registerBreakpoint(AbstractLineBreakpointHandler.java:16)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.handleBreakpoint(XDebugSessionImpl.java:430)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.processBreakpoints(XDebugSessionImpl.java:415)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.processAllBreakpoints(XDebugSessionImpl.java:571)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initBreakpoints(XDebugSessionImpl.java:310)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.init(XDebugSessionImpl.java:278)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:280)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:232)
	at com.jetbrains.python.debugger.PyDebugRunner.createXDebugSession(PyDebugRunner.java:159)
	at com.jetbrains.python.debugger.PyDebugRunner.doExecute(PyDebugRunner.java:245)
	at com.google.idea.blaze.python.run.BlazePyDebugRunner.doExecute(BlazePyDebugRunner.java:81)
	at com.jetbrains.python.debugger.PyDebugRunner.lambda$executeWithLegacyWorkaround$11(PyDebugRunner.java:298)
	at com.intellij.openapi.application.constraints.ConstrainedTaskExecutor.lambda$submit$4(ConstrainedTaskExecutor.java:64)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion$scheduleWithinConstraints$1.invoke(BaseConstrainedExecution.kt:68)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion.scheduleWithinConstraints(BaseConstrainedExecution.kt:71)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution.scheduleWithinConstraints(BaseConstrainedExecution.kt:38)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.access$scheduleWithinConstraints$s1153900543(BaseExpirableExecutorMixinImpl.kt:12)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl$scheduleWithinConstraints$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.impl.AppUIExecutorImpl$MyEdtExecutor.execute(AppUIExecutorImpl.kt:72)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.scheduleWithinConstraints(BaseExpirableExecutorMixinImpl.kt:23)
	at com.intellij.openapi.application.constraints.ConstrainedTaskExecutor.submit(ConstrainedTaskExecutor.java:62)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.submit(BaseExpirableExecutorMixinImpl.kt:30)
	at com.jetbrains.python.debugger.PyDebugRunner.executeWithLegacyWorkaround(PyDebugRunner.java:298)
	at com.jetbrains.python.debugger.PyDebugRunner.lambda$execute$10(PyDebugRunner.java:271)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:173)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:72)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:234)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by sgowroji** [comment]
Hello @rdesgroppes, Could you please verify the above with the latest release and let us know if you still see the error. Thanks!

**Comment by rdesgroppes** [comment]
Hi @sgowroji, thanks for asking. Well, no, the problem seems to have gone away over plugin updates.
`blaze`-related stack traces I still observe:
```
INFO - #c.i.u.i.RootChangesLogger - New rootsChanged event for "project" project with partial rescanning with trace_hash = 1234567890:
java.lang.Throwable
        at com.intellij.util.indexing.RootChangesLogger.info(RootChangesLogger.java:27)
        at com.intellij.util.indexing.EntityIndexingServiceImpl.logRootChanges(EntityIndexingServiceImpl.java:108)
        at com.intellij.util.indexing.EntityIndexingServiceImpl.indexChanges(EntityIndexingServiceImpl.java:87)
        at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.synchronizeRoots(ProjectRootManagerComponent.java:299)
        at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.fireRootsChangedEvent(ProjectRootManagerComponent.java:212)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:477)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$1.fireRootsChanged(ProjectRootManagerImpl.java:137)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$1.fireRootsChanged(ProjectRootManagerImpl.java:134)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.lambda$levelDown$0(ProjectRootManagerImpl.java:84)
        at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:86)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1011)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1037)
        at com.intellij.openapi.application.WriteAction.run(WriteAction.java:85)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.levelDown(ProjectRootManagerImpl.java:84)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:401)
        at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.lambda$updateProject$7(ProjectUpdateSyncTask.java:320)
```
```
WARN - #c.g.i.b.b.a.p.ExternalTask - Cannot run program "glogin" (in directory "/"): error=2, No such file or directory
java.io.IOException: Cannot run program "glogin" (in directory "/"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at com.google.idea.blaze.base.async.process.ExternalTask$ExternalTaskImpl.invokeCommand(ExternalTask.java:276)
        at com.google.idea.blaze.base.async.process.ExternalTask$ExternalTaskImpl.lambda$run$0(ExternalTask.java:193)
        at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
        at com.google.idea.blaze.base.async.process.ExternalTask$ExternalTaskImpl.run(ExternalTask.java:186)
        at com.google.idea.blaze.base.actions.FileGitHubIssueAction.lambda$static$0(FileGitHubIssueAction.java:65)
        at com.intellij.openapi.util.NotNullLazyValue$1.compute(NotNullLazyValue.java:61)
        at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:37)
        at com.google.idea.blaze.base.actions.FileGitHubIssueAction.updateForBlazeProject(FileGitHubIssueAction.java:74)
        at com.google.idea.blaze.base.actions.BlazeProjectAction.update(BlazeProjectAction.java:58)
```
```
SEVERE - #c.g.i.b.j.s.m.BlazeJarLibrary - No local jar file found for bazel-out/k8-fastbuild/bin/path/to/target-filtered-gen.jar
java.lang.Throwable: No local jar file found for bazel-out/k8-fastbuild/bin/path/to/target-filtered-gen.jar
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
        at com.google.idea.blaze.java.sync.model.BlazeJarLibrary.modifyLibraryModel(BlazeJarLibrary.java:77)
        at com.google.idea.blaze.base.sync.libraries.LibraryEditor.updateLibrary(LibraryEditor.java:140)
        at com.google.idea.blaze.base.sync.libraries.LibraryEditor.updateProjectLibraries(LibraryEditor.java:69)
        at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.updateProjectStructure(ProjectUpdateSyncTask.java:390)
        at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.lambda$updateProject$6(ProjectUpdateSyncTask.java:322)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:398)
        at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.lambda$updateProject$7(ProjectUpdateSyncTask.java:320)
```

**Comment by rdesgroppes** [comment]
The following one shouldn't be hard to reproduce as it happens when loading any Bazel project:
```
WARN - #c.g.i.b.b.a.p.ExternalTask - Cannot run program "glogin" (in directory "/"): error=2, No such file or directory
java.io.IOException: Cannot run program "glogin" (in directory "/"): error=2, No such file or directory
```
My environment:
- Bazel 2022.09.07.0.1-api-version-222
- IntelliJ IDEA 2022.2.2 (Community Edition)
- Build #IC-222.4167.29, built on September 13, 2022
- Runtime version: 17.0.4+7-b469.53 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS: Ubuntu 22.04.1 LTS

As the other ones happen way more sporadically, I'd need to reset my logs and record what I was doing next time they surface.

**Comment by amir-f** [comment]
I keep hitting a similar issue

```
java.lang.Throwable: 'Application.acquireReadActionLock' is deprecated and going to be removed soon. Use `runReadAction()` instead
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl.acquireReadActionLock(ApplicationImpl.java:1116)
	at com.google.idea.blaze.python.run.BlazePyPositionConverter.convertLocalLineToRemote(BlazePyPositionConverter.java:111)
	at com.google.idea.blaze.python.run.BlazePyPositionConverter.convertToPython(BlazePyPositionConverter.java:65)
	at com.jetbrains.python.debugger.AbstractLineBreakpointHandler.unregisterBreakpoint(AbstractLineBreakpointHandler.java:48)
	at com.jetbrains.python.debugger.AbstractLineBreakpointHandler.unregisterBreakpoint(AbstractLineBreakpointHandler.java:16)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.handleBreakpoint(XDebugSessionImpl.java:444)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.processBreakpoint(XDebugSessionImpl.java:469)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.processAllHandlers(XDebugSessionImpl.java:458)
	at com.intellij.xdebugger.impl.XDebugSessionImpl$MyBreakpointListener.processRemove(XDebugSessionImpl.java:1043)
	at com.intellij.xdebugger.impl.XDebugSessionImpl$MyBreakpointListener.breakpointRemoved(XDebugSessionImpl.java:1039)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:655)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:621)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:395)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:374)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:433)
	at jdk.proxy1/jdk.proxy1.$Proxy160.breakpointRemoved(Unknown Source)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.lambda$doRemoveBreakpointImpl$5(XBreakpointManagerImpl.java:292)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.sendBreakpointEvent(XBreakpointManagerImpl.java:302)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.doRemoveBreakpointImpl(XBreakpointManagerImpl.java:292)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.doRemoveBreakpoint(XBreakpointManagerImpl.java:272)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.removeBreakpoint(XBreakpointManagerImpl.java:255)
	at com.intellij.xdebugger.impl.XDebuggerUtilImpl.lambda$removeBreakpoint$8(XDebuggerUtilImpl.java:369)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:943)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:969)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:85)
	at com.intellij.xdebugger.impl.XDebuggerUtilImpl.removeBreakpoint(XDebuggerUtilImpl.java:369)
	at com.intellij.xdebugger.impl.XDebuggerUtilImpl.removeBreakpointWithConfirmation(XDebuggerUtilImpl.java:364)
	at com.intellij.xdebugger.impl.breakpoints.RemoveBreakpointGutterIconAction.actionPerformed(RemoveBreakpointGutterIconAction.java:31)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:302)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:302)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.performAction(EditorGutterComponentImpl.java:2209)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.invokeGutterAction(EditorGutterComponentImpl.java:2151)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mouseReleased(EditorGutterComponentImpl.java:2129)
	at com.intellij.openapi.editor.impl.EditorImpl.processMouseReleased(EditorImpl.java:2387)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.lambda$runMouseReleasedCommand$1(EditorImpl.java:4002)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:4004)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3887)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

It does not stop the plugin from working but is quite annoying.

**IDE**: PyCharm 2022.3.1 (Community Edition)
Build #PC-223.8214.51, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON

**Bazel**: bazel 5.0.0

**Comment by mai93** [comment]
Deprecated `Application.acquireReadActionLock` replaced in https://github.com/bazelbuild/intellij/commit/799efd9e9f071ae565d9a478081a29f97dca611c
