### ISSUE TITLE
When debugging in Clion, the bazel plugin cannot find the executable being debugged

### ISSUE THREAD

**Issue by mik90** [bazelbuild/intellij#3706]
Hi,

I was trying out Clion 2022.1.2 with bazel plugin 2022.05.17.0.3-api-version-221 and i cant debug with it. I normally right click a source file or bazel target that's executable and click "Debug 'bazel test MyExecutableTarget'".

Im upgrading from Clion 2021.2.4 with bazel plugin 2022.03.22.0.5-api-version-212 which is able to do debugging.

With this new Clion & bazel combo it complains that the binary I'm trying to debug doesn't exist although i can find it (and run it!) at the path stated in the error message.

The stack trace from the error looks like this (with some source paths obfuscated)
```java
com.intellij.execution.ExecutionException: com.intellij.execution.ExecutionException: com.jetbrains.cidr.execution.debugger.backend.DebuggerCommandException: Cannot load symbol file: /home/path/to/repo/bazel-out/k8-dbg/bin/path/to/executable: No such file or directory.
	at com.jetbrains.cidr.execution.ExecutionResult.get(ExecutionResult.java:53)
	at com.jetbrains.cidr.execution.ExecutionResult.get(ExecutionResult.java:37)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$2.lambda$processWillTerminate$0(CidrDebugProcess.java:256)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$VoidDebuggerCommand.call(CidrDebugProcess.java:1085)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$VoidDebuggerCommand.call(CidrDebugProcess.java:1079)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommand$3.invokeSuspend(CidrDebuggerCommandExecutor.kt:89)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommand$3.invoke(CidrDebuggerCommandExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor.executeCommand(CidrDebuggerCommandExecutor.kt:81)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommandAsync$1.invokeSuspend(CidrDebuggerCommandExecutor.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.execution.ExecutionException: com.jetbrains.cidr.execution.debugger.backend.DebuggerCommandException: Cannot load symbol file: /home/path/to/repo/bazel-out/k8-dbg/bin/path/to/executable
	at com.jetbrains.cidr.execution.ExecutionResult.get(ExecutionResult.java:65)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.executeCommandNoUserException(GDBDriver.java:3539)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.loadForRemote(GDBDriver.java:684)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.loadForRemote(GDBDriver.java:676)
	at com.google.idea.blaze.clwb.run.BlazeCidrRemoteDebugProcess.doLoadTarget(BlazeCidrRemoteDebugProcess.java:85)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.lambda$start$3(CidrDebugProcess.java:465)
	... 23 more
```

Once this happens, I'm unable to use bazel again since it thinks a server is still running even if I kill the server via PID. I have to log out and log back in to start using bazel again.
I assume this is just a consequence of the bug though.

**Comment by mik90** [comment]
Looks like this was either fixed with 2022.08.24.0.1-api-version-222 or it started to work for some other reason
