### ISSUE TITLE
Bazel build of the plugin fails on a fresh machine

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#3928]
### Description of the bug:

If you try to build the plugin without having java installed and you run
`bazel build --define=ij_product=intellij-2021.2 //ijwb:ijwb_bazel_zip`
You get:
```
ERROR: /private/var/tmp/_bazel_ittaiz/8fcd92dbc3da57be8b1fdbdb0fada9a0/external/bazel_tools/tools/jdk/BUILD:336:14: JavaToolchainCompileBootClasspath external/bazel_tools/tools/jdk/platformclasspath.jar failed: (Exit 1): java failed: error executing command external/remotejdk11_macos/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' ... (remaining 6 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1853)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
	at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
	at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
	at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
	at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Target //ijwb:ijwb_bazel_zip failed to build
```
When I ran
`bazel build --define=ij_product=intellij-2021.2 --tool_java_runtime_version=remotejdk_11 --java_runtime_version=remotejdk_11 --java_language_version=8 --tool_java_language_version=11 //ijwb:ijwb_bazel_zip`
then the build passes.

I think that this isn't a problem now because there's an assumption java is installed?
Maybe the plugin should have the above flags in the workspace bazelrc?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Checkout the plugin on a machine without java installed / on the path
Run `bazel build --define=ij_product=intellij-2021.2 //ijwb:ijwb_bazel_zip`
See the failure

### Which Intellij IDE are you using? Please provide the specific version.

2021.2.4

### What programming languages and tools are you using? Please provide specific versions.

scala 2.12, java 11

### What Bazel plugin version are you using?

v2022.08.09 Stable

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/7953
https://github.com/bazelbuild/bazel/issues/7304

**Comment by mai93** [comment]
Resolved with https://github.com/bazelbuild/intellij/commit/d330a5394dd8d57fad3e258ea5a09908f84ee720
