### ISSUE TITLE
Running individual Kotlin JUnit tests sometimes doesn't work depending on the test name

### ISSUE THREAD

**Issue by myronmarston** [bazelbuild/intellij#4065]
### Description of the bug:

We're using kotlin and like using backticks around our test method names so we can be more descriptive:

``` kotlin
  @Test fun `we like using sentences (including parens) as test names`() {

  }
```

But when we use intelliJ to try to run this single test (rather than the entire test class) via the context-menu option, we get an error from the bazel test runner:

```
1) initializationError(org.junit.runner.manipulation.Filter)
java.lang.Exception: No tests found matching RegEx[com.mypackage.MyTestClass.we like using sentences (including parens) as test names]
	at com.google.testing.junit.runner.junit4.JUnit4Runner.createErrorReportingRequestForFilterError(JUnit4Runner.java:245)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.applyFilters(JUnit4Runner.java:213)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:96)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:159)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:85)
```

It looks like an escaping issue. If I remove the parens from the method name, it correctly runs the test.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Define a JUnit test like this in a kotline file:

``` kotlin
  @Test fun `we like using sentences (including parens) as test names`() {

  }
```

Try to run just this test in in intelliJ.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.1.4 (Ultimate Edition)
Build #IU-221.6008.13, built on July 18, 2022

### What programming languages and tools are you using? Please provide specific versions.

Kotlin 1.6.20

### What Bazel plugin version are you using?

2022.08.24.0.1-api-version-221

### Have you found anything relevant by searching the web?

Not yet.

### Any other information, logs, or outputs that you want to share?

Nope.

**Comment by myronmarston** [comment]
I've discovered that this is only a problem with JUnit 4 and on JUnit 5 it's fixed.  Given how old JUnit 4 is I imagine fixing it is not a priority. Will close.
