### ISSUE TITLE
[Android] Native debugging in Android Studio 3.2 is broken

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/intellij#408]
Android Studio 3.2 RC2
Bazel plugin 2018.08.20.0.3

I've tried both running with mobile-install and without, same error. 

>Error while starting native debug session: com.intellij.execution.ExecutionException: Cannot create editor for: class com.google.idea.blaze.base.run.BlazeCommandRunConfiguration

This is working for me in Android Studio 3.0 with same plugin version.

**Comment by jgavris** [comment]
@brendandouglas do you have any ideas on this one? This is a bit of a showstopper for us.

**Comment by vsiva** [comment]
Would you mind posting the full stack trace please? Or you can reproduce the bug and then attach the idea.log file (```Help | Show Log in Files```).

**Comment by jgavris** [comment]
@vsiva Sure, I think this is the relevant bits of the log.

```
2018-09-24 15:27:51,096 [ thread 19]   INFO - idea.stats.RunStatsServiceImpl - notifyDeployFinished: myRun=null, isSuccessful=true 
2018-09-24 15:27:51,197 [nt Monitor]   INFO -            #com.android.ddmlib - Opening a debugger listener at port 8620 for client with pid 32049 
2018-09-24 15:27:52,166 [e-1136-b06]   INFO - s.ndk.run.lldb.ConnectLLDBTask - ABIs supported by app: [x86_64] 
2018-09-24 15:27:52,170 [e-1136-b06]   INFO - s.ndk.run.lldb.ConnectLLDBTask - Launching Bazel:BlazeCommandRunConfigurationType:Hybrid native debug session on device: manufacturer=unknown, model=Android SDK built for x86_64, API=26, codename=REL, ABIs=[x86_64, x86] 
2018-09-24 15:27:52,240 [e-1136-b06]   WARN - s.ndk.run.lldb.ConnectLLDBTask - Using run-as to start debug session 
2018-09-24 15:27:52,265 [e-1136-b06]   INFO - s.ndk.run.lldb.ConnectLLDBTask - ABIs supported by app: [x86_64] 
2018-09-24 15:27:52,277 [e-1136-b06]   INFO - s.ndk.run.lldb.ConnectLLDBTask - Found LLDB server: "/Applications/Android Studio 3.2 Preview.app/Contents/bin/lldb/android/x86_64/lldb-server" 
2018-09-24 15:27:52,282 [e-1136-b06]   INFO - AndroidLLDBDriverConfiguration - LLDB framework file: /Applications/Android Studio 3.2 Preview.app/Contents/bin/lldb/lib/liblldb.7.0.0.dylib 
2018-09-24 15:27:52,370 [e-1136-b06]   WARN - ndk.run.lldb.AndroidLLDBDriver - No symbol directories found 
2018-09-24 15:27:52,375 [e-1136-b06]   INFO - idea.run.AndroidProcessHandler - stopAll() 
2018-09-24 15:27:52,375 [e-1136-b06]   WARN - s.ndk.run.lldb.ConnectLLDBTask - Error while starting native debug session: com.intellij.execution.ExecutionException: Cannot create editor for: class com.google.idea.blaze.base.run.BlazeCommandRunConfiguration 
com.intellij.execution.ExecutionException: Cannot create editor for: class com.google.idea.blaze.base.run.BlazeCommandRunConfiguration
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerLanguageSupportManager.createEditor(CidrDebuggerLanguageSupportManager.kt:74)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.createEditorsProvider(CidrDebugProcess.java:234)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.<init>(CidrDebugProcess.java:205)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.<init>(CidrDebugProcess.java:134)
	at com.android.tools.ndk.run.AndroidNativeAppDebugProcess.<init>(AndroidNativeAppDebugProcess.java:126)
	at com.android.tools.ndk.run.hybrid.AndroidNativeHybridDebugProcessBase.<init>(AndroidNativeHybridDebugProcessBase.java:54)
	at com.android.tools.ndk.run.hybrid.AndroidNativeHybridDebugProcess.<init>(AndroidNativeHybridDebugProcess.java:42)
	at com.android.tools.ndk.run.editor.HybridAndroidDebugger.newAndroidNativeAppDebugProcess(HybridAndroidDebugger.java:174)
	at com.android.tools.ndk.run.editor.HybridAndroidDebugger.newAndroidNativeAppDebugProcess(HybridAndroidDebugger.java:55)
	at com.android.tools.ndk.run.lldb.ConnectLLDBTask$3.createDebugProcess(ConnectLLDBTask.java:604)
	at com.jetbrains.cidr.execution.testing.CidrLauncher.startDebugProcess(CidrLauncher.java:32)
	at com.jetbrains.cidr.execution.CidrCommandLineState.startDebugProcess(CidrCommandLineState.java:30)
	at com.jetbrains.cidr.execution.CidrRunner$1.start(CidrRunner.java:58)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:203)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:164)
	at com.jetbrains.cidr.execution.CidrRunner.startDebugSession(CidrRunner.java:51)
	at com.android.tools.ndk.run.lldb.ConnectLLDBTask.launchCidrDebugger(ConnectLLDBTask.java:628)
	at com.android.tools.ndk.run.lldb.ConnectLLDBTask.launchDebugger(ConnectLLDBTask.java:296)
	at com.android.tools.idea.run.tasks.ConnectDebuggerTask.lambda$perform$0(ConnectDebuggerTask.java:90)
	at com.intellij.util.ui.UIUtil$14.run(UIUtil.java:2936)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-09-24 15:27:52,433 [nt Monitor]   INFO -            #com.android.ddmlib - Opening a debugger listener at port 8621 for client with pid 32076 
2018-09-24 15:27:52,666 [e-1136-b06]   INFO - idea.stats.RunStatsServiceImpl - notifyRunFinished: myRun=null, isSuccessful=true 
```

**Comment by jgavris** [comment]
@vsiva was that helpful? We'd really like to be able to upgrade to AS 3.2.

**Comment by vsiva** [comment]
Yes, sorry about the delay, we had an internal report of this as well, so we'll take a look at this fairly soon.

**Comment by vsiva** [comment]
This is fixed by https://github.com/bazelbuild/intellij/commit/54f5b0709e9a74d4cd1c5a0fdcd4f7cf8c76500d#diff-558a7921d961a8a16d02d89e735db4af. I'm unsure when that actually makes it to a release, but it is not more than 2 weeks.
