### ISSUE TITLE
Weird "Protocol message tag had invalid wire type" error

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#418]
Hi,
I'm getting a weird `Protocol message tag had invalid wire type` error. This happens in our setting of running intellij with a custom bazel binary (that points to bazel in docker) but is relatively new and this setup worked well before.
This is probably a bug on our side but we'd really love to get a few pointers, if you can, on how should one go about debugging such an issue. Where can we look and such because this has very little info for us.
Thank you in advance,
Ittai
cc @brendandouglas 
```
Protocol message tag had invalid wire type.
com.google.protobuf.repackaged.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.repackaged.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:87)
	at com.google.protobuf.repackaged.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:578)
	at com.google.protobuf.repackaged.GeneratedMessage.parseUnknownField(GeneratedMessage.java:267)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage.<init>(Build.java:40471)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage.<init>(Build.java:40417)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage$1.parsePartialFrom(Build.java:41240)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage$1.parsePartialFrom(Build.java:41229)
	at com.google.protobuf.repackaged.AbstractParser.parsePartialFrom(AbstractParser.java:141)
	at com.google.protobuf.repackaged.AbstractParser.parseFrom(AbstractParser.java:175)
	at com.google.protobuf.repackaged.AbstractParser.parseFrom(AbstractParser.java:187)
	at com.google.protobuf.repackaged.AbstractParser.parseFrom(AbstractParser.java:192)
	at com.google.protobuf.repackaged.AbstractParser.parseFrom(AbstractParser.java:21)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage.parseFrom(Build.java:40690)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.parseLanguageSpec(BuildLangSyncPlugin.java:120)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.lambda$getBuildLanguageSpec$0(BuildLangSyncPlugin.java:94)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.getBuildLanguageSpec(BuildLangSyncPlugin.java:89)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.updateSyncState(BuildLangSyncPlugin.java:70)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$doSyncProject$3(BlazeSyncTask.java:471)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:466)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:234)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:190)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:164)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:79)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:113)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:113)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ittaiz** [comment]
@brendandouglas if you can point me to the right direction(s) I'd be really grateful

**Comment by brendandouglas** [comment]
I don't have any specific ideas.

If I was able to reproduce, I'd launch the debugging instance of the IDE, check exactly what's getting output by 'bazel info build-language' (presumably something different than what's output running vanilla bazel, or else it's getting corrupted on the way in to the IDE).

**Comment by ittaiz** [comment]
@hmemcpy can you please assist with this tomorrow? This reproduces every time with wazel

**Comment by hmemcpy** [comment]
Sorry for not chiming in earlier. I've done some digging, and I seem to have an idea why this is happening.
During sync, bazel attempts to [`parseLanguageSpec`](https://github.com/bazelbuild/intellij/blob/b57224d98c01bf1244070f0755c319a2c7870ef5/base/src/com/google/idea/blaze/base/lang/buildfile/sync/BuildLangSyncPlugin.java#L108), by calling the `bazel sync` command, expecting to parse the output bytes as protobuf.
It seems that if there's additional output BEFORE the actual protobuf payload, the deserialization will fail and we'll get this message.
In our case, the erroneous output is a WARNING message, prepended to the actual bazel info command (dumped from the result of `future.get()`):

```
WARNING: Output base '/bazel-nfs-volume/outputs' is on NFS. This may lead to surprising failures and undetermined behavior.

�
bind

name
...
```

We either need to find a way to suppress this warning (requested by @talya in https://github.com/bazelbuild/bazel/issues/5897), otherwise the `parseLanguageSpec` command should gracefully handle possible extraneous outputs.

**Comment by ittaiz** [comment]
sorry, we chased it down to an issue on our side
