### ISSUE TITLE
NullPointerException in GoLand 2018.2.3

### ISSUE THREAD

**Issue by mennanov** [bazelbuild/intellij#423]
The plugin crashes in GoLand 2018.2.3 OS X.

Plugin is built with 
```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-2018.2
```

<img width="1403" alt="goland crash" src="https://user-images.githubusercontent.com/1451079/46779909-cd084280-ccce-11e8-867a-65634fc117a6.png">

```
GoLand 2018.2.3
Build #GO-182.4505.32, built on September 20, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14
```

```
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535)
	at com.google.idea.blaze.golang.resolve.BlazeGoPackageFactory.lambda$getFileToImportPathMap$0(BlazeGoPackageFactory.java:61)
	at com.google.idea.blaze.base.sync.SyncCache.get(SyncCache.java:58)
	at com.google.idea.blaze.golang.resolve.BlazeGoPackageFactory.getFileToImportPathMap(BlazeGoPackageFactory.java:52)
	at com.google.idea.blaze.golang.resolve.BlazeGoPackageFactory.createPackage(BlazeGoPackageFactory.java:41)
	at com.goide.psi.impl.GoPackage.of(GoPackage.java:72)
	at com.goide.psi.impl.GoTypeReference.processUnqualifiedResolve(GoTypeReference.java:109)
	at com.goide.psi.impl.GoTypeReference.processResolveVariants(GoTypeReference.java:76)
	at com.goide.psi.impl.GoReferenceBase.resolveInner(GoReferenceBase.java:126)
	at com.goide.psi.GoFile$GoUnqualifiedResolveCache.computeIfAbsent(GoFile.java:541)
	at com.goide.psi.impl.GoReferenceBase.getCachedResults(GoReferenceBase.java:103)
	at com.goide.psi.impl.GoReferenceBase.resolveOrGet(GoReferenceBase.java:91)
	at com.goide.psi.impl.GoReferenceBase.lambda$static$1(GoReferenceBase.java:56)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:69)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at com.goide.psi.impl.GoReferenceBase.multiResolve(GoReferenceBase.java:74)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at com.goide.psi.GoResolvable.resolve(GoResolvable.java:19)
	at com.goide.psi.impl.GoTypeReference.processQualifierExpression(GoTypeReference.java:85)
	at com.goide.psi.impl.GoTypeReference.processResolveVariants(GoTypeReference.java:73)
	at com.goide.psi.impl.GoReferenceBase.resolveInner(GoReferenceBase.java:126)
	at com.goide.psi.impl.GoReferenceBase.resolveOrGet(GoReferenceBase.java:92)
	at com.goide.psi.impl.GoReferenceBase.lambda$static$1(GoReferenceBase.java:56)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:69)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at com.goide.psi.impl.GoReferenceBase.multiResolve(GoReferenceBase.java:74)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at com.goide.psi.GoResolvable.resolve(GoResolvable.java:19)
	at com.goide.psi.impl.GoPsiImplUtil.resolve(GoPsiImplUtil.java:818)
	at com.goide.psi.impl.GoTypeImpl.resolve(GoTypeImpl.java:54)
	at com.goide.psi.impl.GoNamedElementImpl.findSiblingType(GoNamedElementImpl.java:182)
	at com.goide.psi.impl.GoPsiImplUtil.getGoTypeInner(GoPsiImplUtil.java:404)
	at com.goide.psi.impl.GoParamDefinitionImpl.getGoTypeInner(GoParamDefinitionImpl.java:46)
	at com.goide.psi.impl.GoNamedElementImpl.getGoType(GoNamedElementImpl.java:164)
	at com.goide.psi.impl.GoReference.processReferenceQualifier(GoReference.java:174)
	at com.goide.psi.impl.GoReference.processQualifier(GoReference.java:147)
	at com.goide.psi.impl.GoReference.processResolveVariants(GoReference.java:115)
	at com.goide.psi.impl.GoReferenceBase.resolveInner(GoReferenceBase.java:126)
	at com.goide.psi.impl.GoReferenceBase.resolveOrGet(GoReferenceBase.java:92)
	at com.goide.psi.impl.GoReferenceBase.lambda$static$1(GoReferenceBase.java:56)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:69)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at com.goide.psi.impl.GoReferenceBase.multiResolve(GoReferenceBase.java:74)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at com.goide.psi.GoResolvable.resolve(GoResolvable.java:19)
	at com.goide.psi.impl.GoPsiImplUtil.getGoTypeInner(GoPsiImplUtil.java:661)
	at com.goide.psi.impl.GoPsiImplUtil.lambda$null$3(GoPsiImplUtil.java:473)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:139)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at com.goide.psi.impl.GoPsiImplUtil.lambda$getGoType$4(GoPsiImplUtil.java:472)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:99)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:54)
	at com.goide.psi.impl.GoPsiImplUtil.getGoType(GoPsiImplUtil.java:470)
	at com.goide.psi.impl.GoExpressionImpl.getGoType(GoExpressionImpl.java:31)
	at com.goide.editor.GoParameterInfoHandler.findCallType(GoParameterInfoHandler.java:120)
	at com.goide.highlighting.GoInlayParameterHintsProvider.getParameterHints(GoInlayParameterHintsProvider.java:42)
	at com.intellij.codeInsight.hints.ParameterHintsPass.a(ParameterHintsPass.java:84)
	at com.intellij.codeInsight.hints.ParameterHintsPass.lambda$doCollectInformation$0(ParameterHintsPass.java:76)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by mennanov** [comment]
Actually, the same thing happens even on Intellij 2018.2

**Comment by mennanov** [comment]
I was able to make it work on 
```
IntelliJ IDEA 2017.3.5 (Ultimate Edition)
Build #IU-173.4674.33, built on March 5, 2018
JRE: 1.8.0_152-release-1024-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.14
```
with the plugin version `2018.04.23.0.3`

With newer Intellij & plugin versions (and also GoLand) i still get the exception i posted above when i open any *.go file in the editor.

**Comment by mennanov** [comment]
PR #422  fixed this issue for me and most of the things now work great except for protobufs:

<img width="854" alt="protobuf import fails" src="https://user-images.githubusercontent.com/1451079/46884360-9daa2080-ce09-11e8-8656-68e2293bcbce.png">

And there is an exception in the logs (not sure if it is related though):

```
java.lang.IllegalStateException: This function should be called while holding treeLock
	at java.awt.Component.checkTreeLock(Component.java:1214)
	at java.awt.Container.validateTree(Container.java:1690)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$900(ActionMenu.java:42)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuItemSynchronizer.propertyChange(ActionMenu.java:331)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
	at com.intellij.openapi.actionSystem.Presentation.firePropertyChange(Presentation.java:300)
	at com.intellij.openapi.actionSystem.Presentation.setVisible(Presentation.java:268)
	at com.intellij.openapi.actionSystem.Presentation.setEnabledAndVisible(Presentation.java:295)
	at com.google.idea.blaze.base.actions.BlazeMenuGroup.update(BlazeMenuGroup.java:30)
	at com.intellij.openapi.wm.impl.IdeMenuBar.a(IdeMenuBar.java:390)
	at com.intellij.openapi.wm.impl.IdeMenuBar.updateMenuActions(IdeMenuBar.java:319)
	at com.intellij.openapi.wm.impl.IdeMenuBar$MyTimerListener.run(IdeMenuBar.java:450)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1428)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1417)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1407)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.l(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by chaoren** [comment]
Yes, I checked in a fix for this yesterday, and it should be in the github sync.
The protobuf issue has to do with go source providers from rules_go. We don't have a solution to that yet.
The stack trace is unrelated.
