### ISSUE TITLE
When debugging in Clion, the bazel plugin cannot find the executable being debugged

### ISSUE THREAD

**Issue by happy-san** [bazelbuild/intellij#4231]
### Description of the bug:

Bazel plugin crashes with the following stack trace when debugging the project.

```
com.intellij.execution.ExecutionException: com.intellij.execution.ExecutionException: com.jetbrains.cidr.execution.debugger.backend.DebuggerCommandException: Cannot load symbol file: /home/typesense/.cache/bazel/_bazel_typesense/a8dd01319b9517b0584489f7b60d0f7b/execroot/__main__/bazel-out/k8-dbg/bin/typesense-test: No such file or directory.
	at com.jetbrains.cidr.execution.ExecutionResult.get(ExecutionResult.java:53)
	at com.jetbrains.cidr.execution.ExecutionResult.get(ExecutionResult.java:37)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$2.lambda$processWillTerminate$0(CidrDebugProcess.java:260)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$VoidDebuggerCommand.call(CidrDebugProcess.java:1088)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$VoidDebuggerCommand.call(CidrDebugProcess.java:1082)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommand$3.invokeSuspend(CidrDebuggerCommandExecutor.kt:89)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommand$3.invoke(CidrDebuggerCommandExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor.executeCommand(CidrDebuggerCommandExecutor.kt:81)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommandAsync$1.invokeSuspend(CidrDebuggerCommandExecutor.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.execution.ExecutionException: com.jetbrains.cidr.execution.debugger.backend.DebuggerCommandException: Cannot load symbol file: /home/typesense/.cache/bazel/_bazel_typesense/a8dd01319b9517b0584489f7b60d0f7b/execroot/__main__/bazel-out/k8-dbg/bin/typesense-test: No such file or directory.
	at com.jetbrains.cidr.execution.ExecutionResult.get(ExecutionResult.java:65)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.executeCommandNoUserException(GDBDriver.java:3557)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.loadForRemote(GDBDriver.java:678)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.loadForRemote(GDBDriver.java:670)
	at com.google.idea.blaze.clwb.run.BlazeCidrRemoteDebugProcess.doLoadTarget(BlazeCidrRemoteDebugProcess.java:85)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.lambda$start$3(CidrDebugProcess.java:468)
	... 23 more
Caused by: com.jetbrains.cidr.execution.debugger.backend.DebuggerCommandException: Cannot load symbol file: /home/typesense/.cache/bazel/_bazel_typesense/a8dd01319b9517b0584489f7b60d0f7b/execroot/__main__/bazel-out/k8-dbg/bin/typesense-test: No such file or directory.
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.lambda$loadForRemote$7(GDBDriver.java:689)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$VoidCommand.call(GDBDriver.java:3625)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$VoidCommand.call(GDBDriver.java:3622)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.lambda$doExecuteCommand$58(GDBDriver.java:3602)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 12 more
Caused by: com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: /home/typesense/.cache/bazel/_bazel_typesense/a8dd01319b9517b0584489f7b60d0f7b/execroot/__main__/bazel-out/k8-dbg/bin/typesense-test: No such file or directory.
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$Response.createGDBError(GDBDriver.java:3815)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$Communication.waitFor(GDBDriver.java:3122)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.sendRequestAndWaitForDone(GDBDriver.java:2894)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.doLoadExecutable(GDBDriver.java:758)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.lambda$loadForRemote$7(GDBDriver.java:686)
	... 16 more
```
Running the test works fine.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Environment details:
* GNU gdbserver (Ubuntu 12.1-0ubuntu1~22.04) 12.1
* GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
* gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2022.2.4, 2022.3.1

### What programming languages and tools are you using? Please provide specific versions.

C++, 

### What Bazel plugin version are you using?

2022.11.29.0.1-api-version-222

### Have you found anything relevant by searching the web?

Related: #3706

**Comment by sgowroji** [comment]
Hello @happy-san, Could you please provide minimal steps to reproduce the above error. Thanks!

**Comment by happy-san** [comment]
Hey @sgowroji! I just tried to debug with plugin version `2022.08.24.0.1-api-version-222` since that seemed to work for the other user
> Looks like this was either fixed with 2022.08.24.0.1-api-version-222 or it started to work for some other reason
But that also fails.

```
com.intellij.execution.ExecutionException: com.intellij.execution.ExecutionException: com.jetbrains.cidr.execution.debugger.backend.DebuggerCommandException: Cannot load symbol file: /home/typesense/.cache/bazel/_bazel_typesense/a8dd01319b9517b0584489f7b60d0f7b/execroot/__main__/bazel-out/k8-dbg/bin/typesense-test: No such file or directory.
	at com.jetbrains.cidr.execution.ExecutionResult.get(ExecutionResult.java:53)
	at com.jetbrains.cidr.execution.ExecutionResult.get(ExecutionResult.java:37)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$2.lambda$processWillTerminate$0(CidrDebugProcess.java:260)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$VoidDebuggerCommand.call(CidrDebugProcess.java:1088)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$VoidDebuggerCommand.call(CidrDebugProcess.java:1082)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommand$3.invokeSuspend(CidrDebuggerCommandExecutor.kt:89)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommand$3.invoke(CidrDebuggerCommandExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor.executeCommand(CidrDebuggerCommandExecutor.kt:81)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommandAsync$1.invokeSuspend(CidrDebuggerCommandExecutor.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.execution.ExecutionException: com.jetbrains.cidr.execution.debugger.backend.DebuggerCommandException: Cannot load symbol file: /home/typesense/.cache/bazel/_bazel_typesense/a8dd01319b9517b0584489f7b60d0f7b/execroot/__main__/bazel-out/k8-dbg/bin/typesense-test: No such file or directory.
	at com.jetbrains.cidr.execution.ExecutionResult.get(ExecutionResult.java:65)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.executeCommandNoUserException(GDBDriver.java:3557)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.loadForRemote(GDBDriver.java:678)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.loadForRemote(GDBDriver.java:670)
	at com.google.idea.blaze.clwb.run.BlazeCidrRemoteDebugProcess.doLoadTarget(BlazeCidrRemoteDebugProcess.java:85)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.lambda$start$3(CidrDebugProcess.java:468)
	... 23 more
Caused by: com.jetbrains.cidr.execution.debugger.backend.DebuggerCommandException: Cannot load symbol file: /home/typesense/.cache/bazel/_bazel_typesense/a8dd01319b9517b0584489f7b60d0f7b/execroot/__main__/bazel-out/k8-dbg/bin/typesense-test: No such file or directory.
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.lambda$loadForRemote$7(GDBDriver.java:689)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$VoidCommand.call(GDBDriver.java:3625)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$VoidCommand.call(GDBDriver.java:3622)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.lambda$doExecuteCommand$58(GDBDriver.java:3602)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 12 more
Caused by: com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: /home/typesense/.cache/bazel/_bazel_typesense/a8dd01319b9517b0584489f7b60d0f7b/execroot/__main__/bazel-out/k8-dbg/bin/typesense-test: No such file or directory.
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$Response.createGDBError(GDBDriver.java:3815)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$Communication.waitFor(GDBDriver.java:3122)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.sendRequestAndWaitForDone(GDBDriver.java:2894)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.doLoadExecutable(GDBDriver.java:758)
	at com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver.lambda$loadForRemote$7(GDBDriver.java:686)
	... 16 more
```
I'm not much familiar with bazel to provide a minimal example.

**Comment by happy-san** [comment]
@sgowroji  I've added the bug reproduction steps in the issue.

**Comment by happy-san** [comment]
Hey @tpasternak, just wondering if you've picked up this issue? It's a pain to debug using gdb.

**Comment by happy-san** [comment]
Hey @tpasternak,
![image](https://user-images.githubusercontent.com/68999628/216971317-f0cc6cd0-29f0-4d94-a1fd-50c2c8219d1a.png)
