### ISSUE TITLE
 java.lang.AssertionError: Page 898402883731712 is outside of [0, 4294967295)

### ISSUE THREAD

**Issue by rdesgroppes** [bazelbuild/intellij#4457]
### Description of the bug:

The plugin often throws exceptions:
```java
RunContextAction#update@EditorPopup(preload-bgt) (com.intellij.execution.actions.RunContextAction), actionId=RunClass, text='Run context configuration'

java.lang.AssertionError: Page 898402883731712 is outside of [0, 4294967295)
	at com.intellij.util.io.PagedFileStorage.doGetBufferWrapper(PagedFileStorage.java:453)
	at com.intellij.util.io.PagedFileStorage.getBufferWrapper(PagedFileStorage.java:431)
	at com.intellij.util.io.PagedFileStorage.getReadOnlyBuffer(PagedFileStorage.java:426)
	at com.intellij.util.io.PagedFileStorage.get(PagedFileStorage.java:305)
	at com.intellij.util.io.storage.DataTable.readBytes(DataTable.java:59)
	at com.intellij.util.io.storage.AbstractStorage.lambda$readBytes$5(AbstractStorage.java:273)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:233)
	at com.intellij.util.io.storage.AbstractStorage.withReadLock(AbstractStorage.java:418)
	at com.intellij.util.io.storage.AbstractStorage.readBytes(AbstractStorage.java:266)
	at com.intellij.util.io.storage.AbstractStorage.readStream(AbstractStorage.java:261)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOld.readAttribute(AttributesStorageOld.java:87)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSAttributeAccessor.readAttribute(PersistentFSAttributeAccessor.java:34)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSTreeAccessor.listIds(PersistentFSTreeAccessor.java:112)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.listIds(FSRecords.java:331)
	at com.intellij.openapi.vfs.PlatformVirtualFileManager.listAllChildIds(PlatformVirtualFileManager.java:70)
	at com.intellij.openapi.module.impl.scopes.ModuleWithDependenciesScope.doExtractFilIdEnumeration(ModuleWithDependenciesScope.java:248)
	at com.intellij.openapi.module.impl.scopes.ModuleWithDependenciesScope.lambda$extractFileEnumeration$3(ModuleWithDependenciesScope.java:240)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.openapi.module.impl.scopes.ModuleWithDependenciesScope.extractFileEnumeration(ModuleWithDependenciesScope.java:240)
	at com.intellij.psi.search.impl.VirtualFileEnumeration.extract(VirtualFileEnumeration.java:33)
	at com.intellij.util.indexing.FileBasedIndexImpl.extractFileEnumeration(FileBasedIndexImpl.java:2107)
	at com.intellij.util.indexing.FileBasedIndexImpl.extractIdFilter(FileBasedIndexImpl.java:2078)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAnyKey(FileBasedIndexImpl.java:1144)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByNames(FilenameIndex.java:225)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:62)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaModuleGraphUtil.findDescriptionByModuleInner(JavaModuleGraphUtil.java:134)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaModuleGraphUtil.createModuleCacheResult(JavaModuleGraphUtil.java:124)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaModuleGraphUtil.lambda$findDescriptorByModule$2(JavaModuleGraphUtil.java:111)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaModuleGraphUtil.findDescriptorByModule(JavaModuleGraphUtil.java:111)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaModuleGraphUtil.findDescriptorByFile(JavaModuleGraphUtil.java:65)
	at com.intellij.codeInsight.daemon.impl.analysis.JavaModuleGraphUtil.findDescriptorByElement(JavaModuleGraphUtil.java:49)
	at com.intellij.psi.impl.JavaPlatformModuleSystem.checkAccess(JavaPlatformModuleSystem.kt:90)
	at com.intellij.psi.impl.JavaPlatformModuleSystem.checkAccess(JavaPlatformModuleSystem.kt:52)
	at com.intellij.psi.impl.JavaPlatformModuleSystem.isAccessible(JavaPlatformModuleSystem.kt:40)
	at com.intellij.psi.JavaModuleSystem.isAccessible(JavaModuleSystem.java:40)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.lambda$isAccessible$0(PsiResolveHelperImpl.java:131)
	at com.intellij.util.containers.ContainerUtil.and(ContainerUtil.java:1991)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.isAccessible(PsiResolveHelperImpl.java:142)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.isAccessible(PsiResolveHelperImpl.java:131)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.isAccessible(PsiResolveHelperImpl.java:119)
	at com.intellij.psi.impl.source.resolve.ClassResolverProcessor.checkAccessibility(ClassResolverProcessor.java:252)
	at com.intellij.psi.impl.source.resolve.ClassResolverProcessor.execute(ClassResolverProcessor.java:213)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl$MyResolveCacheProcessor.process(PsiJavaFileBaseImpl.java:607)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl$MyResolveCacheProcessor.process(PsiJavaFileBaseImpl.java:585)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:702)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:289)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:61)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:40)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:207)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:136)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:493)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:379)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:372)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:176)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:237)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:214)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:176)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:801)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:793)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:769)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:427)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:421)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:356)
	at com.intellij.psi.PsiAnnotation.resolveAnnotationType(PsiAnnotation.java:111)
	at com.intellij.codeInsight.AnnotationTargetUtil.findAnnotationTarget(AnnotationTargetUtil.java:170)
	at com.intellij.psi.impl.source.PsiModifierListImpl.lambda$getApplicableAnnotations$1(PsiModifierListImpl.java:302)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:859)
	at com.intellij.psi.impl.source.PsiModifierListImpl.getApplicableAnnotations(PsiModifierListImpl.java:301)
	at com.intellij.codeInsight.MetaAnnotationUtil.getResolvedClassesInAnnotationsList(MetaAnnotationUtil.java:353)
	at com.intellij.codeInsight.MetaAnnotationUtil.isMetaAnnotated(MetaAnnotationUtil.java:248)
	at com.intellij.execution.junit.JUnitUtil.lambda$isJUnit5TestClass$1(JUnitUtil.java:313)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.execution.junit.JUnitUtil.isJUnit5TestClass(JUnitUtil.java:306)
	at com.google.idea.blaze.java.run.producers.ProducerUtils.isTestClass(ProducerUtils.java:130)
	at com.google.idea.blaze.java.run.producers.ProducerUtils.getTestClass(ProducerUtils.java:108)
	at com.google.idea.blaze.java.run.producers.JavaTestContextProvider.getSelectedTestClass(JavaTestContextProvider.java:145)
	at com.google.idea.blaze.java.run.producers.JavaTestContextProvider.getTestContext(JavaTestContextProvider.java:62)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.lambda$doFindTestContext$1(TestContextRunConfigurationProducer.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.doFindTestContext(TestContextRunConfigurationProducer.java:94)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.lambda$findTestContext$0(TestContextRunConfigurationProducer.java:84)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.findTestContext(TestContextRunConfigurationProducer.java:79)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.doIsConfigFromContext(TestContextRunConfigurationProducer.java:126)
	at com.google.idea.blaze.base.run.producers.TestContextRunConfigurationProducer.doIsConfigFromContext(TestContextRunConfigurationProducer.java:38)
	at com.google.idea.blaze.base.run.producers.BlazeRunConfigurationProducer.isConfigurationFromContext(BlazeRunConfigurationProducer.java:71)
	at com.intellij.execution.actions.RunConfigurationProducer.findExistingConfiguration(RunConfigurationProducer.java:231)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:280)
	at com.intellij.execution.actions.BaseRunConfigurationAction.findExisting(BaseRunConfigurationAction.java:65)
	at com.intellij.execution.actions.BaseRunConfigurationAction.fullUpdate(BaseRunConfigurationAction.java:220)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:185)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:157)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:180)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:720)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$5(ActionUpdater.java:186)
	at com.intellij.diagnostic.telemetry.TraceKt.computeWithSpan(trace.kt:123)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:137)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:705)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:556)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:606)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:606)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:606)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:606)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:606)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:309)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:377)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:428)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:424)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$16(ActionUpdater.java:396)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$17(ActionUpdater.java:395)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Hard to tell. I seem to face the above since I upgraded to Version 2023.01.24.0.1-api-version-223.

### Which Intellij IDE are you using? Please provide the specific version.

Build #IC-223.8617.56, built on January 26, 2023

### What programming languages and tools are you using? Please provide specific versions.

Java 17

### What Bazel plugin version are you using?

Version 2023.01.24.0.1-api-version-223

### Have you found anything relevant by searching the web?

Not yet.

**Comment by sgowroji** [comment]
Hi @rdesgroppes, Could you please share complete steps to reproduce the above error. Thanks!

**Comment by rdesgroppes** [comment]
@sgowroji I have no idea, really.

**Comment by mai93** [comment]
Thank you for reporting this, it is hard to identify the root cause from the stack trace, I will keep an eye for similar errors and if you find a pattern or repro steps for this please update the issue.

**Comment by Chyba1997** [comment]
Hgj

**Comment by rdesgroppes** [comment]
Closing as no longer occurring since one of last few upgrades. Doesn't seem to be worth investigating anymore.
