### ISSUE TITLE
Internal errors when synchronizing on a newly created `git` branch

### ISSUE THREAD

**Issue by rdesgroppes** [bazelbuild/intellij#4609]
### Description of the bug:

When synchronizing right after having switched the working copy to a newly created git branch, the IDE shows an internal error:
```
java.lang.Throwable: Could not obtain upstream sha: `git rev-parse @{u}` exited with 128; stderr: fatal: no upstream configured for branch 'regis/remove-unused-identifier-fields'

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.google.idea.blaze.base.vcs.git.GitBlazeVcsHandlerProvider.getUpstreamSha(GitBlazeVcsHandlerProvider.java:143)
	at com.google.idea.blaze.base.vcs.git.GitBlazeVcsHandlerProvider$GitBlazeVcsHandler.lambda$getWorkingSet$0(GitBlazeVcsHandlerProvider.java:72)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create a new git branch, i.e. `git checkout -b name`
2. In the toolbar, click: `Bazel` / `Sync` / `Sync Project with BUILD files`

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.3.3 (Community Edition) - Build #IC-223.8836.41, built on March 10, 2023

### What programming languages and tools are you using? Please provide specific versions.

Any

### What Bazel plugin version are you using?

2023.02.22.0.1-api-version-223

**Comment by mai93** [comment]
Fixed with https://github.com/bazelbuild/intellij/commit/7fd8ed552eaca69cf5eb68c84602289923d723ad
