### ISSUE TITLE
CLion plugin is incompatible to bazel flag incompatible_disable_target_provider_fields

### ISSUE THREAD

**Issue by martis42** [bazelbuild/intellij#4714]
### Description of the bug:

A Bazel project using `incompatible_disable_target_provider_fields` to make sure it is not by accident using deprecated behavior is not compatible to the CLion Bazel plugin.

Desired solution:
Changing the implementation to use the forward path pattern and then to use `incompatible_disable_target_provider_fields` in the CI to make sure the issue does not reappear until Bazel flips this flag in a future release.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Setup a Bazel project with CLion
2. Create a `.bazelrc` file in the project and add `--incompatible_disable_target_provider_fields`
3. Start a project sync

Exemplary error:
```
ERROR: <path_to_build_file>/BUILD:3:10: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on py_binary rule //src/apply_fixes:main: 
Traceback (most recent call last):
	File "<path_into_cache>/e663c61e10a8ed8d3fb71670c233b37b/external/intellij_aspect/intellij_info_bundled.bzl", line 67, column 37, in _aspect_impl
		return intellij_info_aspect_impl(target, ctx, semantics)
	File "<path_into_cache>/e663c61e10a8ed8d3fb71670c233b37b/external/intellij_aspect/intellij_info_impl.bzl", line 1017, column 28, in intellij_info_aspect_impl
		direct_deps = make_deps(direct_dep_targets, COMPILE_TIME)
	File "<path_into_cache>/e663c61e10a8ed8d3fb71670c233b37b/external/intellij_aspect/intellij_info_impl.bzl", line 263, column 21, in make_deps
		return [make_dep(dep, dependency_type) for dep in deps]
	File "<path_into_cache>/e663c61e10a8ed8d3fb71670c233b37b/external/intellij_aspect/intellij_info_impl.bzl", line 258, column 21, in make_dep
		target = dep.intellij_info.target_key,
Error: Accessing providers via the field syntax on structs is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_disable_target_provider_fields=false. See https://github.com/bazelbuild/bazel/issues/9014 for details.
```

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2023.1.1 Build #CL-231.8109.2222

### What programming languages and tools are you using? Please provide specific versions.

Python 3.8, rules_python 0.8.0, bazel_skylib 1.4.1

### What Bazel plugin version are you using?

2023.03.10.0.1-api-version-231

### Have you found anything relevant by searching the web?

There are several automatically created issues which are closed without any comment:
- https://github.com/bazelbuild/intellij/issues/1507
- https://github.com/bazelbuild/intellij/issues/1508
- https://github.com/bazelbuild/intellij/issues/1509
- https://github.com/bazelbuild/intellij/issues/1510

Linked to the [tracking issue](https://github.com/bazelbuild/bazel/issues/9014) for this incompatibility flag is this issue https://github.com/bazel-contrib/SIG-rules-authors/issues/36. An existing bug bounty for resolving this is in my opinion a sign that the Bazel team indeed intends to flip this flag.

### Any other information, logs, or outputs that you want to share?

To my knowledge flipping this flag (with an adapted implementation of course) is backwards compatible up until at least Bazel 4.0.0. I don't know what the status for even older versions is.

**Comment by mai93** [comment]
I can fix this internally as well.

**Comment by martis42** [comment]
@mai93 did you receive feedback in the SIC meeting? With the release of Bazel 7, Bazel 4 is now deprecated. I don't know your user base, but to me requiring at least Bazel 4.0.0 from users seems like a reasonable thing.

**Comment by mai93** [comment]
I think we already have Bazel 4.0.0 as the oldest supported Bazel version for a while now https://github.com/bazelbuild/intellij/commit/8ec77794a6072322316680a7d8bc80c3072f28b8

**Comment by martis42** [comment]
So this issue is unblocked then by now?
If and when somebody has time to fix this is of course a different question.

**Comment by mai93** [comment]
I think we will keep it at P3 for now, meaning that we do not have a plan to fix it but we can review PRs that address this.

**Comment by martis42** [comment]
The issue is still relevant
