### ISSUE TITLE
Unable to set required flags for Bazel plugin's "Sync Project With BUILD files"

### ISSUE THREAD

**Issue by janpfeifer** [bazelbuild/intellij#4744]
#### Description of the issue. Please be specific.

I'm developing a library using [github.com/openxla/xla](https://github.com/openxla/xla) and it requires me to import their bazelrc and set some of their bazel flags also in the `bazel info` command used by the "Sync Project Wtih BULD Files" process used by this plugin.

Namely I need to set the following flags (probably not all of them, but at least the --bazelrc=... and --experimental_repo_remote_exec)

```
bazel --bazelrc=openxla_xla_bazelrc info --tool_tag=ijwb:CLion --curses=no --color=yes --progress_in_terminal_title=no --keep_going --verbose_failures --sandbox_debug --config=linux --config=cuda --config=tpu --define tsl_protobuf_header_only=false --define framework_shared_object=false --check_visibility=false --experimental_repo_remote_exec
```

When I run this command manually it works. When the Bazel plugin tries to run the version without them:

```
bazel info --tool_tag=ijwb:CLion --curses=no --color=yes --progress_in_terminal_title=no --
```

It always fails.

Unfortunately the "Bazel Settings" tab in the Settings window doesnt' have any field that allows me to add those flags. And without this sync up process the whole Intellij/CLion becomes unusable.

I get errors of the following type:

```
DEBUG: /home/unencrypted/janpf/bazel-cache/_bazel_janpf/9e2b9edace8e158516b8f7620a59d766/external/xla/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'tf_runtime' because it already exists.
DEBUG: /home/unencrypted/janpf/bazel-cache/_bazel_janpf/9e2b9edace8e158516b8f7620a59d766/external/xla/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'llvm-raw' because it already exists.
ERROR: Traceback (most recent call last):
	File "/home/unencrypted/janpf/bazel-cache/_bazel_janpf/9e2b9edace8e158516b8f7620a59d766/external/tsl/third_party/gpus/cuda_configure.bzl", line 1475, column 40, in <toplevel>
		remote_cuda_configure = repository_rule(
Error in repository_rule: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: Traceback (most recent call last):
	File "/home/unencrypted/janpf/bazel-cache/_bazel_janpf/9e2b9edace8e158516b8f7620a59d766/external/tsl/third_party/py/python_configure.bzl", line 288, column 42, in <toplevel>
		remote_python_configure = repository_rule(
Error in repository_rule: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: Traceback (most recent call last):
	File "/home/unencrypted/janpf/bazel-cache/_bazel_janpf/9e2b9edace8e158516b8f7620a59d766/external/tsl/tools/toolchains/cpus/aarch64/aarch64.bzl", line 235, column 43, in <toplevel>
		remote_aarch64_configure = repository_rule(
Error in repository_rule: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
...
```

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

Just have a `WORKSPACE` /  `BUILD` files that require `--experimental_repo_remote_exec` flag, or a specific bazelrc file (`--bazelrc=...` flag)

#### Version information
CLion: 2023.1.1
Platform: Linux 5.17.5-051705-generic
Bazel for CLion plugin: 2023.03.10.0.1-api-version-231

**Comment by janpfeifer** [comment]
I managed to work around my problem, by creating a better .bazelrc with the flags I needed, and making it import (with `try-import my_bazelrc`).

Maybe this is the right solution for Bazel, as opposed to have that being configured in the tool itself.

I'll mark this as closed.
