### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.

### ISSUE THREAD

**Issue by AlexBurdu** [bazelbuild/intellij#4845]
### Description of the bug:

I've been getting this for some time, but I believe that recently it started to cause IDE freeze.

```
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:142)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:527)
	at com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(GeneratedMessageV3.java:863)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage$Builder.mergeFrom(Build.java:43626)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage$1.parsePartialFrom(Build.java:43988)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage$1.parsePartialFrom(Build.java:43980)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at com.google.devtools.build.lib.query2.proto.proto2api.Build$BuildLanguage.parseFrom(Build.java:43365)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.parseLanguageSpec(BuildLangSyncPlugin.java:125)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.lambda$getBuildLanguageSpec$0(BuildLangSyncPlugin.java:95)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:40)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.getBuildLanguageSpec(BuildLangSyncPlugin.java:90)
	at com.google.idea.blaze.base.lang.buildfile.sync.BuildLangSyncPlugin.updateSyncState(BuildLangSyncPlugin.java:71)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.lambda$run$2(ProjectUpdateSyncTask.java:189)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.run(ProjectUpdateSyncTask.java:184)
	at com.google.idea.blaze.base.sync.ProjectUpdateSyncTask.runProjectUpdatePhase(ProjectUpdateSyncTask.java:125)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$updateProjectAndFinishSync$7(SyncPhaseCoordinator.java:560)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$runWithTiming$1(SyncScope.java:67)
	at com.google.idea.blaze.base.sync.SyncScope.lambda$push$2(SyncScope.java:80)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:95)
	at com.google.idea.blaze.base.sync.SyncScope.push(SyncScope.java:77)
	at com.google.idea.blaze.base.sync.SyncScope.runWithTiming(SyncScope.java:69)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.updateProjectAndFinishSync(SyncPhaseCoordinator.java:551)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:454)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:257)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:237)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:83)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:131)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:131)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

``` MODULE.bazel
bazel_dep(name = "bazel_skylib", version = "1.4.1")

#------------------------------  JVM -------------------------------------------
bazel_dep(name = "rules_java", version = "5.5.0")

# Maven
bazel_dep(name = "rules_jvm_external", version = "5.1")
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")

maven_deps = use_extension("//third_party/java:maven_deps_install.bzl", "maven_deps")
maven_deps.install()

# Use my internal extension as repo for maven as the deps get installed in it
use_repo(maven_deps, "maven")

#------------------------------  Python ----------------------------------------
bazel_dep(name = "rules_python", version = "0.20.0")

python = use_extension("@rules_python//python:extensions.bzl", "python")
python.toolchain(
    name = "python3_9",
    configure_coverage_tool = True,
    python_version = "3.9",
)
use_repo(python, "python3_9_toolchains")
register_toolchains(
    "@python3_9_toolchains//:all",
)

pip = use_extension("@rules_python//python:extensions.bzl", "pip")
pip.parse(
    name = "pip",
    requirements_lock = "//third_party/python:requirements_lock.txt",
)
use_repo(pip, "pip")

#------------------------------ Build Tools ------------------------------------
bazel_dep(name = "buildifier_prebuilt", version = "6.0.0.1")

bazel_dep(name = "protobuf", version = "21.7")

```

### Which Intellij IDE are you using? Please provide the specific version.

Build #IU-231.8770.65, built on April 27, 2023

### What programming languages and tools are you using? Please provide specific versions.

java, kotlin 1.8, dart/flutter (3.7.6), 

### What Bazel plugin version are you using?

2023.03.10.0.1-api-version-231 → 2023.04.18.0.1-api-version-231

**Comment by mai93** [comment]
I think we need more information about the project targets to be able to reproduce this error.
