### ISSUE TITLE
Bazel plugin throws NPE when Java files appear in the WORKSPACE root

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/intellij#49]
Consider this sample project https://github.com/dfabulich/bazel-intellij-sync-failed

It has a blank `WORKSPACE` and a `BUILD` file containing just one target, `//:x`.

```python
java_binary(
	name='x',
	srcs=['X.java'],
	main_class='X',
)
```

`X.java` is directly in the root directory; it's hello world.

```java
public class X {
	public static void main(String[] args) throws Exception {
		System.out.println("hello");
	}
}
```

When I attempt to build and sync this project, the plugin throws a `NullPointerException` in `SourceDirectoryCalculator`.

<details><summary>stacktrace</summary>

```
java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.idea.blaze.java.sync.source.SourceDirectoryCalculator.calculateJavaSourceDirectories(SourceDirectoryCalculator.java:247)
	at com.google.idea.blaze.java.sync.source.SourceDirectoryCalculator.calculateSourceDirectoriesForContentRoot(SourceDirectoryCalculator.java:211)
	at com.google.idea.blaze.java.sync.source.SourceDirectoryCalculator.lambda$calculateContentEntries$2(SourceDirectoryCalculator.java:124)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:56)
	at com.google.idea.blaze.java.sync.source.SourceDirectoryCalculator.calculateContentEntries(SourceDirectoryCalculator.java:117)
	at com.google.idea.blaze.java.sync.importer.BlazeJavaWorkspaceImporter.importWorkspace(BlazeJavaWorkspaceImporter.java:112)
	at com.google.idea.blaze.java.sync.BlazeJavaSyncPlugin.lambda$updateSyncState$0(BlazeJavaSyncPlugin.java:157)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:36)
	at com.google.idea.blaze.java.sync.BlazeJavaSyncPlugin.updateSyncState(BlazeJavaSyncPlugin.java:153)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$doSyncProject$2(BlazeSyncTask.java:349)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:56)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:344)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:178)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:157)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:56)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:48)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:135)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:108)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:105)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.idea.blaze.base.model.primitives.WorkspacePath.validate(WorkspacePath.java:70)
	at com.google.idea.blaze.base.model.primitives.WorkspacePath.validate(WorkspacePath.java:65)
	at com.google.idea.blaze.base.model.primitives.WorkspacePath.<init>(WorkspacePath.java:54)
	at com.google.idea.blaze.java.sync.source.SourceDirectoryCalculator.sourceRootForJavaSource(SourceDirectoryCalculator.java:468)
	at com.google.idea.blaze.java.sync.source.SourceDirectoryCalculator.lambda$calculateJavaSourceDirectories$5(SourceDirectoryCalculator.java:242)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:61)
	at com.google.idea.blaze.java.sync.source.SourceDirectoryCalculator.calculateJavaSourceDirectories(SourceDirectoryCalculator.java:240)
	... 30 more
```

</details>

Moving `X.java` into a subdirectory fixes the problem.

**Comment by brendandouglas** [comment]
Thanks for the excellent steps to reproduce!

This is fixed for the next release and/or code drop.

**Comment by brendandouglas** [comment]
More specifically, it will be in v2017.02.13+, which we'll likely upload to JetBrains' repository around 2-3 weeks after that date.
