### ISSUE TITLE
Intellij hangs when right-clicking on top level directory

### ISSUE THREAD

**Issue by brownry1986** [bazelbuild/intellij#491]
Right-clicking on the top level directory in the project hangs and eventually crashes for large projects.

**Environment Information:**
IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018

JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

Bazel Plugin: v2018.12.03.0.2

I am working on a mac but I have others working on Linux that are seeing the same issue.

**Details**
A stack dump points to MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory as the culprit. Adding logging to the plugin further solidifies this theory. It appears that this call stack is attempting to recursively traverse the entire directory structure under the folder that was right-clicked upon in an apparent attempt to discover all test classes (unclear what it is doing with the results). The recursive traversal includes the bazel-* symlinked directories along with directories in .bazelignore and directories that are excluded in .bazelproject. The traversal is also occurring in the gui thread which freezes the entire IDE.

I have recreated this issue in a sample project here: https://github.com/brownry1986/BazelIssues

This is a very small project, so the hanging only lasts approximately 1 second and it only occurs the first time you right-click on the project root after opening the project, however as the size of the project grows the hanging lasts longer and longer and in especially large/deep projects we start seeing memory errors and the Intellij hangs until it is killed.

**Workaround**
We were able to resolve this with a workaround but it is not ideal. Including '.' in the .bazelproject causes the root directory to be considered a part of the project and therefore right-clicking on the root directory initiates the recursive traversal. By not including '.' in the .bazelproject the traversal will only occur on selected directories that are a part of the project. Since '.' is not a part of the project, the traversal does not occur when right-clicking on the root. Right-clicking on a directory that is a part of the project will traverse only that directory. This can still cause the IDE to hang, but the hang time is relative to the size of the chosen directory.

This is not ideal for the following reasons:
1. We have to whitelist all directories that we want included in our project; if a new directory is added, it needs to be added to the .bazelproject
2. Any files in the root directory are not considered a part of the project; e.g. WORKSPACE

**Requests**
1. Exclude known bazel directories from the traversal and/or respect the .bazelignore and .bazelproject exclusions when deciding what to traverse.
2. Provide the ability to list wildcards in the .bazelproject; I would like to include '*' in my .bazelproject instead of '.'. This would allow me to include everything under the project root but not treat the project root as part of the project.
3. Avoid long operations in the GUI thread; preferably the traversal could occur on sync or on project load and not when the user right-clicks on a directory.

**Stack Dump**
```
"AWT-EventQueue-0" #29 prio=6 os_prio=0 tid=0x00007f01148d1000 nid=0x448f runnable [0x00007f00e75f6000]
   java.lang.Thread.State: RUNNABLE
	at com.intellij.psi.impl.source.JavaLightStubBuilder.skipChildProcessingWhenBuildingStubs(JavaLightStubBuilder.java:70)
	at com.intellij.psi.stubs.LightStubBuilder.skipNode(LightStubBuilder.java:162)
	at com.intellij.psi.stubs.LightStubBuilder.buildStubTree(LightStubBuilder.java:132)
	at com.intellij.psi.stubs.LightStubBuilder.buildStubTree(LightStubBuilder.java:66)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:84)
	- locked <0x00000006d0c73890> (a com.intellij.util.indexing.FileContentImpl)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.lambda$readOrBuild$0(StubTreeLoaderImpl.java:69)
	at com.intellij.psi.stubs.StubTreeLoaderImpl$$Lambda$2062/640764616.compute(Unknown Source)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:98)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:53)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:69)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:605)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:928)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStub(PsiFileImpl.java:581)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.getClasses(PsiJavaFileBaseImpl.java:61)
	at com.intellij.core.CoreJavaDirectoryService.getPsiClasses(CoreJavaDirectoryService.java:70)
	at com.intellij.core.CoreJavaDirectoryService.getClasses(CoreJavaDirectoryService.java:55)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:187)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.addClassesInDirectory(MultipleJavaClassesTestConfigurationProducer.java:189)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.getTestTargetIfUnique(MultipleJavaClassesTestConfigurationProducer.java:182)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.getTestLocation(MultipleJavaClassesTestConfigurationProducer.java:138)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.doIsConfigFromContext(MultipleJavaClassesTestConfigurationProducer.java:115)
	at com.google.idea.blaze.java.run.producers.MultipleJavaClassesTestConfigurationProducer.doIsConfigFromContext(MultipleJavaClassesTestConfigurationProducer.java:62)
	at com.google.idea.blaze.base.run.producers.BlazeRunConfigurationProducer.isConfigurationFromContext(BlazeRunConfigurationProducer.java:71)
	at com.intellij.execution.actions.RunConfigurationProducer.findExistingConfiguration(RunConfigurationProducer.java:200)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:238)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:190)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:171)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:151)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:177)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:177)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:177)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:177)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:295)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:109)
	at com.intellij.ui.PopupHandler$2.invokePopup(PopupHandler.java:88)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:40)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6545)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:409)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by brendandouglas** [comment]
We're actually in the middle of a rewrite of these run configuration producers, moving all expensive PSI and bazel target resolution off the EDT.

In particular, MultipleJavaClassesTestConfigurationProducer no longer checks for blaze package children recursively, so you should see this specific freeze. That fix is already in at head, so closing.

**Comment by brownry1986** [comment]
Thanks @brendandouglas !

That is great that this is fixed, but when you say the fix is already in at head, I assume you mean the internal repo and not the publicly available code on github (I built from head and still see the issue). Will this be included in the next code drop? Any idea when that will be?

Thanks!

**Comment by brendandouglas** [comment]
Ah sorry, I was mixed up with a separate run config producer fix involving recursive directory traversal (the 'AllInPackage' one). This bug is also tracked internally, and something we'll fix up as part of the run config rewrite.

**Comment by or-shachar** [comment]
@brendandouglas  - This hurts our work as well. Any chance for a hotfix?

**Comment by or-shachar** [comment]
cool! thanks!

**Comment by brownry1986** [comment]
Verified fix with the latest version of the plugin.

Thanks!
