### ISSUE TITLE
Failure to sync with  "java.lang.IllegalArgumentException: No such attribute tags..." 

### ISSUE THREAD

**Issue by mattofak** [bazelbuild/intellij#492]
Trying CLion / Bazel integration for the first time.
CLion: 2018.2.7
Bazel Plugin: 2018.12.03.0.2
Bazel: 0.21.0
JDK: OpenJDK 64-Bit Server VM (build 9.0.7.1+1, mixed mode)
OS: Ubuntu 18.04

When attempting to sync (using Bazel->Sync->Sync Project with BUILD Files) I get the following error message:
```
Building IDE info files...
Command: bazel build --tool_tag=ijwb:CLion --keep_going --build_event_binary_file=/tmp/intellij-bep-812942a8-29f3-4c3a-88f0-49c332b4c0c5 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/mwalker/.CLion2018.2/config/plugins/clwb/aspect --output_groups=intellij-info-cpp,intellij-info-generic,intellij-info-py -- //... //allocortech/io/gpio:all //clio:all //allocortech/protocol/uavcan:all //:all //allocortech/time:all //allocortech/io/adc:all //allocortech:all //external:all //allocortech/io:all

INFO: Invocation ID: 774393bc-50bf-4210-92b1-ed2557abbfcb
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//external:all' (requested by nodes '[//..., //allocortech/io/gpio:all, //clio:all, //allocortech/protocol/uavcan:all, //:all, //allocortech/time:all, //allocortech/io/adc:all, //allocortech:all, //external:all, //allocortech/io:all] EXPAND_TEST_SUITES com.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in local_repository rule //external:bazel_tools
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:258)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:66)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
	at com.google.devtools.build.lib.packages.TargetUtils.hasConstraint(TargetUtils.java:219)
	at com.google.devtools.build.lib.packages.TargetUtils.hasManualTag(TargetUtils.java:99)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual.shouldRetain(FilteringPolicies.java:77)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$AndFilteringPolicy.shouldRetain(FilteringPolicies.java:136)
	at com.google.devtools.build.lib.pkgcache.TargetPatternResolverUtil.resolvePackageTargets(TargetPatternResolverUtil.java:46)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.getTargetsInPackage(RecursivePackageProviderBackedTargetPatternResolver.java:133)
	at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsInPackage.eval(TargetPattern.java:478)
	at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:77)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
	... 4 more
```

`//external` is where I keep the BUILD files for 3rd party repositories that are imported via WORKSPACE. This may have some collision effects because it appears the built in `bazel_tools` are also defined to be under `external`?

**Comment by brendandouglas** [comment]
This exception is coming from bazel itself, and doesn't appear to be specific to CLion plugin. Could you open an issue on https://github.com/bazelbuild/bazel?

They should be able to help.

**Comment by mattofak** [comment]
As a breadcrumb for future searching; this issue was caused by having an `external` directory. Moving that directory to one named something different (and adjusting my rules) solved the issue.

**Comment by brendandouglas** [comment]
Ah, that would do it. Bazel is supposed to fail early if an 'external' directory exists in the workspace root, but perhaps that check has since disappeared.
