### ISSUE TITLE
Sync fails on windows

### ISSUE THREAD

**Issue by ShaneEverittM** [bazelbuild/intellij#5019]
### Description of the bug:

An initial load of a helloworld project fails with the following output:
```
Error:Cannot run program "C:\Users\shane\AppData\Local\Temp\xcode_cquery.sh" (in directory "C:\Users\shane\dev\cpp\cpplox"): CreateProcess error=193, %1 is not a valid Win32 application
```
My guess is this is a Python `subprocess` bug where you need to pass `shell=True`. I get this bug a lot trying to write cross-platform Python code.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a project with a single WORKSPACE file, a single package with a BUILD file containing: 
```bazel
cc_binary(
    name = "main",
    srcs = ["main.cpp"],
)
```
and open it in CLion.

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2023.1.3

### What programming languages and tools are you using? Please provide specific versions.

C++

### What Bazel plugin version are you using?

2023.05.30.0.1-api-version-231

### Any other information, logs, or outputs that you want to share?

Tool window logs:
```
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: bazel info --tool_tag=ijwb:CLion --curses=no --color=yes --progress_in_terminal_title=no --
Computing VCS working set...
Running Bazel info...
Command: bazel info --tool_tag=ijwb:CLion --curses=no --color=yes --progress_in_terminal_title=no --
Building 0 Bazel targets...
Build invocation result: success
Parsing build outputs...
Total rules: 0, new/changed: 0, removed: 0
Reading IDE info result...
Reading IDE info result...
Updating target map...
Loaded 0 aspect files, total size 0kB
Target map size: 0
Prefetching output artifacts...
Prefetching files...
Refreshing files...
Computing directory structure...
Initializing project SDKs...
Committing project structure...
Workspace has 0 libraries
Workspace has 2 modules
Updating in-memory state...
Command: C:\Users\shane\AppData\Local\Temp\xcode_cquery.sh
0 unique C configurations, 0 C targets
Sync finished
Sync failed
```

**Comment by ShaneEverittM** [comment]
I also managed to get this stack trace, which I missed before:
```
java.lang.NullPointerException: Cannot invoke "java.util.Optional.equals(Object)" because "this.xcodeProperties" is null
	at com.google.idea.blaze.cpp.BlazeConfigurationResolverResult.isEquivalentConfigurations(BlazeConfigurationResolverResult.java:96)
	at com.google.idea.blaze.cpp.BlazeCWorkspace$1.run(BlazeCWorkspace.java:137)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ShaneEverittM** [comment]
> Thank you for reaching us @ShaneEverittM It's probably fixed in #4976 . Could you check whether it's reproducible in beta channel? cc @blorente

It is in fact fixed on the beta channel.
