### ISSUE TITLE
issues collecting info from c++ compiler

### ISSUE THREAD

**Issue by brownry1986** [bazelbuild/intellij#508]
After opening my project in CLion and syncing I ocassionally get this message:

`issues collecting info from c++ compiler`

Viewing the idea.log I see this stacktrace:

```
Error resolving header include roots

java.util.concurrent.ExecutionException: java.lang.AssertionError
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:526)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:507)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.doCollectHeaderRoots(BlazeConfigurationResolver.java:184)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.lambda$collectHeaderRoots$0(BlazeConfigurationResolver.java:138)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.collectHeaderRoots(BlazeConfigurationResolver.java:131)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.update(BlazeConfigurationResolver.java:101)
	at com.google.idea.blaze.cpp.BlazeCWorkspace.update(BlazeCWorkspace.java:113)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.lambda$updateInMemoryState$0(BlazeCSyncPlugin.java:71)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.updateInMemoryState(BlazeCSyncPlugin.java:65)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$updateInMemoryState$12(BlazeSyncTask.java:973)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:948)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$updateInMemoryState$13(BlazeSyncTask.java:966)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.updateInMemoryState(BlazeSyncTask.java:960)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:264)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:211)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:178)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:76)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:110)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError
	at com.intellij.util.io.Page.<init>(Page.java:67)
	at com.intellij.util.io.PagePool.hitQueues(PagePool.java:135)
	at com.intellij.util.io.PagePool.alloc(PagePool.java:102)
	at com.intellij.util.io.RandomAccessDataFile.get(RandomAccessDataFile.java:95)
	at com.intellij.util.io.RandomAccessDataFile.getInt(RandomAccessDataFile.java:117)
	at com.intellij.openapi.vfs.newvfs.persistent.CompactRecordsTable.getSize(CompactRecordsTable.java:112)
	at com.intellij.util.io.storage.AbstractRecordsTable.scanForFreeRecords(AbstractRecordsTable.java:151)
	at com.intellij.util.io.storage.AbstractRecordsTable.ensureFreeRecordsScanned(AbstractRecordsTable.java:144)
	at com.intellij.util.io.storage.AbstractRecordsTable.deleteRecord(AbstractRecordsTable.java:196)
	at com.intellij.openapi.vfs.newvfs.persistent.CompactRecordsTable.deleteRecord(CompactRecordsTable.java:191)
	at com.intellij.util.io.storage.AbstractStorage.doDeleteRecord(AbstractStorage.java:328)
	at com.intellij.util.io.storage.Storage.deleteRecord(Storage.java:54)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.deleteContentAndAttributes(FSRecords.java:669)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.lambda$createRecord$2(FSRecords.java:580)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeAndHandleErrors(FSRecords.java:939)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.createRecord(FSRecords.java:567)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.createAndFillRecord(PersistentFSImpl.java:1179)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getId(PersistentFSImpl.java:388)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:174)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:95)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:447)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:57)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:54)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath(LocalFileSystemBase.java:44)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByIoFile(LocalFileSystemBase.java:60)
	at com.google.idea.blaze.base.io.VfsUtils.resolveVirtualFile(VfsUtils.java:41)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.lambda$doCollectHeaderRoots$1(BlazeConfigurationResolver.java:162)
	... 6 more
```

A resync usually resolves the issue. This can be painful on a large project to have to sync and load symbols twice. Any ideas?

Operating System: macOS 10.14.2
Bazel Version: 0.22.0-homebrew
CLion Version: 2018.3.4 Build #CL-183.5429.37
Bazel Plugin Version: v2019.01.28.0.2

**Comment by jvoung** [comment]
The Page.java:67 assert looks like an upstream issue: https://youtrack.jetbrains.com/issue/IDEA-179016.  It's not too clear why it happens (some guess about abnormal IDE termination), but if you do notice a pattern it would be nice to figure the root cause. It does seem to happen more often in CLion, though the code is shared with IntelliJ.

The entry point from the bazel plugin to upstream code is LocalFileSystemBase.findFileByIoFile(). I don't think we are misusing that API, so I don't think there's much we can do in the plugin itself.
