### ISSUE TITLE
Bazel plugin throws in CLion on OS X

### ISSUE THREAD

**Issue by david-german-tri** [bazelbuild/intellij#51]
On OS X only, after building the plugin from 4894694348b35c54524563d2e62af974857b82d4, and importing [RobotLocomotion/drake](https://github.com/RobotLocomotion/drake) into CLion 2016.2.3 [as documented here](http://drake.mit.edu/clion.html?highlight=clion#using-clion-with-bazel), I get the following exception from inside the plugin.  

If more details would be useful, please let me know! 

```
Write access is allowed from event dispatch thread only
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@40c8bff8 Current thread: Thread[pool-2-thread-1,5,main] 397385620 SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.2.3#CL-162.2228.26 CLion, eap:false, os:Mac OS X 10.11.6, java-version:JetBrains s.r.o 1.8.0_112-release-287-b2,6,main] 1567327220

java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.b(ApplicationImpl.java:981)
	at com.intellij.openapi.application.impl.ApplicationImpl.d(ApplicationImpl.java:1068)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:896)
	at com.google.idea.blaze.cpp.BlazeCWorkspace.refreshExecRoot(BlazeCWorkspace.java:107)
	at com.google.idea.blaze.cpp.BlazeCWorkspace.update(BlazeCWorkspace.java:75)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.lambda$updateInMemoryState$0(BlazeCSyncPlugin.java:63)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:56)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.updateInMemoryState(BlazeCSyncPlugin.java:55)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$null$12(BlazeSyncTask.java:771)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$updateInMemoryState$13(BlazeSyncTask.java:764)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:56)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.updateInMemoryState(BlazeSyncTask.java:758)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:190)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:160)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:56)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:48)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:138)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:108)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:105)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by david-german-tri** [comment]
This happens on every sync.  I can reproduce it with a minimal workspace:

* empty `WORKSPACE` file
* `main.cc` with a no-op `main` function
* `BUILD` file with a `cc_binary` rule `my_main`

**Comment by brendandouglas** [comment]
Thank you for letting us know. This is actually fixed upstream, we just haven't had a code drop for a while.

I'll look into making another code drop in the next few days.

**Comment by david-german-tri** [comment]
Thanks!  We are eagerly anticipating that drop.

**Comment by brendandouglas** [comment]
Should be fixed with the latest code drop -- please reopen if not.
