### ISSUE TITLE
Issues with crosstool and per_object_debug_info_file

### ISSUE THREAD

**Issue by tadeegan** [bazelbuild/intellij#511]
It seems as though not all crosstool build flags are supported by the plugin aspect.
https://docs.bazel.build/versions/master/crosstool-reference.html#crosstool-build-variables

In particular, I have this feature in my CROSSTOOL.tpl

```
  feature {
    name: 'per_object_debug_info'
    flag_set {
      action: 'assemble'
      action: 'preprocess-assemble'
      action: 'c-compile'
      action: 'c++-compile'
      action: 'c++-module-codegen'
      flag_group {
        flag: '-MJ'
        flag: '%{per_object_debug_info_file}'
      }
    }
  }
```

And when I build, I get this error:

```
ERROR: /home/thomas/.cache/bazel/_bazel_thomas/925d2bb91b60f375fce428dfba68c0e1/external/sysroot_toolchain/BUILD:17:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on cc_toolchain rule @sysroot_toolchain//:cc-compiler-local: 
Traceback (most recent call last):
	File "/home/thomas/.cache/bazel/_bazel_thomas/925d2bb91b60f375fce428dfba68c0e1/external/sysroot_toolchain/BUILD", line 17
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/home/thomas/.cache/bazel/_bazel_thomas/925d2bb91b60f375fce428dfba68c0e1/external/intellij_aspect/intellij_info_bundled.bzl", line 53, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/home/thomas/.cache/bazel/_bazel_thomas/925d2bb91b60f375fce428dfba68c0e1/external/intellij_aspect/intellij_info_impl.bzl", line 788, in intellij_info_aspect_impl
		collect_c_toolchain_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File "/home/thomas/.cache/bazel/_bazel_thomas/925d2bb91b60f375fce428dfba68c0e1/external/intellij_aspect/intellij_info_impl.bzl", line 386, in collect_c_toolchain_info
		cc_common.get_memory_inefficient_command_line(feature_configuration = feature_..., <2 more arguments>)
Invalid toolchain configuration: Cannot find variable named 'per_object_debug_info_file'.
```

Seems like maybe this emulation of the toolchain is causing the issue? Any ideas for a quick workaround or patch I can add?

https://github.com/bazelbuild/intellij/blob/f522564c2c9040be9418e49949cc85d12a89daa9/aspect/intellij_info_impl.bzl#L342

**Comment by tadeegan** [comment]
Btw, my bazel version is `Build label: 0.19.2`

**Comment by hlopko** [comment]
You probably want to add expand_if_all_available: 'per_object_debug_info_file' into the flag_group, so the build doesn't fail when intellij doesn't pass it. Now if you insist of having dwo file generated, that will be a different and a little bit more complicated question :)

**Comment by tadeegan** [comment]
```diff
--- a/tools/toolchain/CROSSTOOL.tpl
+++ b/tools/toolchain/CROSSTOOL.tpl
@@ -238,6 +238,7 @@ toolchain {
       flag_group {
         flag: '-MJ'
         flag: '%{per_object_debug_info_file}'
+        expand_if_all_available: 'per_object_debug_info_file'
       }
     }
   }

```

This worked!!!
