### ISSUE TITLE
com.intellij.diagnostic.PluginException: No display name is specified for configurable - IDEA 2032.2

### ISSUE THREAD

**Issue by ilanKeshet** [bazelbuild/intellij#5190]
### Description of the bug:

The ide keeps complaining for missing display name in configuration 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

install bazel plugin in IDEA 2023.2 

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2023.2 (Ultimate Edition) Build #IU-232.8660.185, built on July 26, 2023 

### What Bazel plugin version are you using?

2023.07.21.0.2-api-version-232

### Have you found anything relevant by searching the web?

looks to be quite similar to https://github.com/aws/aws-toolkit-jetbrains/pull/3753/files 

### Any other information, logs, or outputs that you want to share?

Stack trace
```
com.intellij.diagnostic.PluginException: No display name is specified for configurable com.google.idea.blaze.base.settings.ui.BlazeUserSettingsCompositeConfigurable in xml file;
specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: com.google.idea.bazel.ijwb]
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)
	at com.intellij.openapi.options.ex.Weighted.lambda$static$0(Weighted.java:26)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at com.intellij.openapi.options.ex.SortedConfigurableGroup.buildConfigurables(SortedConfigurableGroup.java:41)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:75)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:148)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.access$collect(EpBasedConfigurableGroup.kt:1)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:110)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:119)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$Companion.getConfigurableGroups(ShowSettingsUtilImpl.kt:48)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.kt)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.initMacApplication$lambda$2$lambda$1(MacOSApplicationProvider.kt:71)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.submit$lambda$6(MacOSApplicationProvider.kt:170)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

IDE info:
```
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Licensed to ....
Subscription is active until ....
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 6072M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.8660.205)
    org.ermadan.kafkalytic (0.10.5)
    org.intellij.plugins.hcl (232.8660.88)
    com.ultrahob.zerolength.plugin (0.95)
    com.github.copilot (1.2.16.2847)
    org.jetbrains.plugins.go-template (232.8660.88)
    idea.goyacc (0.1.0)
    name.kropp.intellij.makefile (232.8660.88)
    com.eversql.plugins.jetbrains (1.3.1)
    ir.msdehghan.plugins.ansible (0.92)
    artsiomch.meson.syntax (203.1.0)
    org.jetbrains.plugins.go (232.8660.142)
    com.tabnine.TabNine (1.0.39)
    org.jetbrains.plugins.ruby (232.8660.185)
    com.intellij.kubernetes (232.8660.158)
    com.intellij.grazie.pro (0.3.239)
    Pythonid (232.8660.185)
    org.tonybaloney.security.pycharm-security (1.28.0)
    uk.co.ben-gibson.remote.repository.mapper (4.3.5)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    izhangzhihao.rainbow.brackets.lite (1.0.1)
    org.intellij.scala (2023.2.17)
    org.jetbrains.plugins.docker.gateway (232.8660.202)
    com.google.idea.bazel.ijwb (2023.07.21.0.2-api-version-232)
    aws.toolkit (1.74-232)

Kotlin: 232-1.9.0-IJ8660.185
```

**Comment by Pavank1992** [comment]
Hi @ilanKeshet, Could please help us to reproduce the issue with minimal steps? I tried to generate the error for plugin : 2023.07.21.0.2-api-version-232, for Build #IU-232.8660.185, built on July 26, 2023 but could not see the error.

**Comment by ilanKeshet** [comment]
> It happens when you open settings page, addresed in #5196

Thank you @tpasternak , @Pavank1992
