### ISSUE TITLE
$(location //:target) doesn't expand from plugin

### ISSUE THREAD

**Issue by tadeegan** [bazelbuild/intellij#522]
My intellij log shows:

```
2019-02-28 14:16:52,310 [17223181]   WARN - idea.blaze.cpp.BlazeCWorkspace - Issues collecting info from C++ compiler. Showing first few out of 2:
[Compiler exited with error code 1: /tmp/blaze_compiler2.sh -xc++ -nostdinc -isystem external/com_ubuntu_sysroot/opt/libcxx/include/c++/v1 -idirafter external/com_ubuntu_sysroot/usr/include -idirafter external/com_ubuntu_sysroot/usr/include/x86_64-linux-gnu -idirafter external/clang/lib/clang/6.0.0/include

[.... eradicated ...]

(location\ //tools/cruise_tidy:CruiseTidy.so) -Xclang -add-plugin -Xclang cruise-tidy -Xclang -plugin-arg-cruise-tidy -Xclang -packages-file -Xclang -plugin-arg-cruise-tidy -Xclang autogenerated/list_cruise_pkgs.bzl -include $(location\ //tools/cruise_tidy:cruise_tidy_dependency_hack.h) -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DROSCONSOLE_BACKEND=log4cxx -DPYTHON_BAZEL_HACK -DTIXML_USE_STL -DROSPACK_API_BACKCOMPAT_V1 -DYAML_CPP_NO_CONTRIB -DEIGEN_MPL2_ONLY -DOPENCV_TINY_GPU_MODULE -DHAVE_NEW_YAMLCPP -DSQLITE_OMIT_DEPRECATED -fpch-preprocess -v -dD -E
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/tdeegan/.cache/bazel/_bazel_tdeegan/a8696b2acbcb6442362edeb92dd13e97/external/clang/bin
Found CUDA installation: /usr/local/cuda-9.0, version 9.0
clang: [0;1;31merror: [0mno such file or directory: '//tools/cruise_tidy:CruiseTidy.so)'[0m
clang: [0;1;31merror: [0mno such file or directory: '//tools/cruise_tidy:cruise_tidy_dependency_hack.h)'[0m
```

I've added the following copts to my cc_library:

```
[
    "-Xclang",
    "$(location //tools/cruise_tidy:CruiseTidy.so)",
]
```

It seems as though the command line invocation created by the plugin does not expand the `$(location //tools/cruise_tidy:CruiseTidy.so)` things from skylark... Any ideas how to overcome this?

**Comment by jvoung** [comment]
This is a bit like https://github.com/bazelbuild/intellij/issues/406, in that the `copts` we get from a target are the unexpanded strings and need a way to expand (somewhere around https://github.com/bazelbuild/intellij/blob/e76fdadb0bdabbe2be913cba03d9014eb2366374/aspect/intellij_info_impl.bzl#L309).

Not yet sure if there is a better way than going through `ctx.expand_location` (vs say, `cc_common.get_memory_inefficient_command_line`)

**Comment by jvoung** [comment]
Also, is it possible to have a bit more context about the cc_library in question?
Namely, when you have `$(location //tools/cruise_tidy:CruiseTidy.so)`, is `//tools/cruise_tidy:CruiseTidy.so` under `deps` or `data` or something else?
It must be in some prerequisite, but just wanted to check which, in case the optional `targets` parameter in `ctx.expand_location` would come into play, etc.

**Comment by tadeegan** [comment]
Yes. I believe its the same issue although it looks like they have taken steps to fix this at HEAD.

I tried making this change:

```diff
diff --git a/aspect/make_variables.bzl b/aspect/make_variables.bzl
index e66bbcae..6d831a84 100644
--- a/aspect/make_variables.bzl
+++ b/aspect/make_variables.bzl
@@ -39,6 +39,9 @@ def expand_make_variables(attr_name, expression, ctx, additional_subs = {}):
     if "$" not in expression:
         return expression
 
+    if "location" in expression:
+        return ctx.expand_location(expression)
+
     current_offset = 0
     rv = ""
     substitutions = {}
```

But got an error about it not being able to expand the target:

```
ERROR: /home/tdeegan/dev/xxx/BUILD:1:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on cc_library rule //xxx:headers: label '//tools/cruise_tidy:CruiseTidy.so' in $(location) expression is not a declared prerequisite of this rule.
```

**Comment by tadeegan** [comment]
Note that I've also added the target to the 'data' deps for my cc_library

**Comment by tadeegan** [comment]
Yea. It seems they have fixed #406 at head.  I can now use $(BINDIR) instead of $(location xxx) successfully.

**Comment by tadeegan** [comment]
Do you have any recommendations for how to dig into this and fix?  I'm happy to make a contribution to resolve this problem but need a little guidance.

**Comment by sambatyon** [comment]
We are dealing with a similar issue were a test fails because its data relies on $(location) substitutions:

```py
filegroup(
  name = "resources",
   srcs = ["resource.json"],
   data = []
)

cc_test(
   name = 'example_test',
   # ...
   copts = [
      "-DRESOURCES=\\\"$(location :resources)\\\""
   ],
   data = [
      ":resources"
   ]
)
```

Building the test produces the following trace:
```
 $ bz build \
    --tool_tag=ijwb:CLion \
    --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect \
    --override_repository=intellij_aspect=$HOME/.CLion2019.1/config/plugins/clwb/aspect \
    --output_groups=intellij-info-cpp,intellij-info-generic,intellij-resolve-cpp \
   -- //path/to/target:example_test

Analyzing: target //path/to/target:example_test (1 packages loaded, 0 targets configured)
ERROR: /home/username/Workspace/test_project/path/to/target/BUILD:30:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on cc_test rule //path/to/target:example_test: 
Traceback (most recent call last):
        File "/home/username/Workspace/test_project/path/to/target/BUILD", line 30
                @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
        File "/home/username/.cache/bazel/_bazel_username/603aa82a335ea12682f7dc09eb601924/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
                intellij_info_aspect_impl(target, ctx, semantics)
        File "/home/username/.cache/bazel/_bazel_username/603aa82a335ea12682f7dc09eb601924/external/intellij_aspect/intellij_info_impl.bzl", line 890, in intellij_info_aspect_impl
                collect_cpp_info(target, ctx, semantics, ide_info, <2 more arguments>)
        File "/home/username/.cache/bazel/_bazel_username/603aa82a335ea12682f7dc09eb601924/external/intellij_aspect/intellij_info_impl.bzl", line 397, in collect_cpp_info
                expand_make_variables("copt", copt, ctx)
        File "/home/username/.cache/bazel/_bazel_username/603aa82a335ea12682f7dc09eb601924/external/intellij_aspect/make_variables.bzl", line 92, in expand_make_variables
                fail(("expand_make_variables: $(%s) i...), ...)
attribute copt: expand_make_variables: $(location :resources) invalid name
```

CLion version is 2019.1.4 and plugin version v2019.08.19.0.5

**Comment by sambatyon** [comment]
This patch will solve this issue:

```diff
diff --git a/aspect/make_variables.bzl b/aspect/make_variables.bzl
index e66bbcae..f55571c3 100644
--- a/aspect/make_variables.bzl
+++ b/aspect/make_variables.bzl
@@ -87,6 +87,11 @@ def expand_make_variables(attr_name, expression, ctx, additional_subs = {}):
         # odd number of '$', but integer division will provide correct count
         rv = rv + "$" * ((end_dollars - begin_dollars) // 2)
         varname = expression[end_dollars + 1:end_parens]
+
+        # Handle $(location) expansion
+        if varname.startswith("location"):
+            varname = varname[len("location"):].strip()
+            return ctx.expand_location(varname)
         if not _is_valid_make_var(varname):
             # invalid make variable name
             fail("expand_make_variables: $(%s) invalid name" % varname, attr_name)
```

**Comment by gyakushev** [comment]
+1, have the same problem as @sambatyon

**Comment by pvcnt** [comment]
Hello, I'm hitting the exact same issue since upgrading PyCharm (weirdly?), is there any intention to have this fixed?
