### ISSUE TITLE
Unable to open project using Import and create new workspace option.

### ISSUE THREAD

**Issue by ashutoshraina** [bazelbuild/intellij#5419]
### Description of the bug:

The bazel for intellij plugin crashes when trying to Import a project and selecting create from scratch option.

Diagnostic information available on crash.

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 2920,4,main] 1103582109 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1421902459
	at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1078)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1066)
	at com.intellij.openapi.application.impl.LaterInvocator.getCurrentModalityState(LaterInvocator.java:288)
	at com.intellij.openapi.application.impl.ModalityKt.inModalContext(modality.kt:9)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport.runWithModalProgressBlockingInternal(PlatformTaskSupport.kt:135)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport.access$runWithModalProgressBlockingInternal(PlatformTaskSupport.kt:41)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$1.invoke(PlatformTaskSupport.kt:123)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$1.invoke(PlatformTaskSupport.kt:119)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext$lambda$5(context.kt:124)
	at com.intellij.openapi.progress.impl.CoreProgressManager.silenceGlobalIndicator(CoreProgressManager.java:963)
	at com.intellij.openapi.progress.ContextKt.prepareIndicatorThreadContext(context.kt:122)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:86)
	at com.intellij.openapi.progress.impl.PlatformTaskSupport.runWithModalProgressBlockingInternal(PlatformTaskSupport.kt:119)
	at com.intellij.openapi.progress.TasksKt.runBlockingModalWithRawProgressReporter(tasks.kt:285)
	at com.intellij.openapi.progress.TasksKt.runBlockingModalWithRawProgressReporter$default(tasks.kt:279)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.createProject(ProjectManagerImpl.kt:519)
	at com.intellij.ide.util.projectWizard.ProjectBuilder.createProject(ProjectBuilder.java:46)
	at com.google.idea.blaze.base.wizard2.BlazeProjectImportBuilder.createProject(BlazeProjectImportBuilder.java:85)
	at com.google.idea.blaze.base.wizard2.BlazeProjectCreator.createProject(BlazeProjectCreator.java:108)
	at com.google.idea.blaze.base.wizard2.BlazeProjectCreator.doCreate(BlazeProjectCreator.java:85)
	at com.google.idea.blaze.base.wizard2.BlazeImportProjectAction$2.compute(BlazeImportProjectAction.java:69)
	at com.google.idea.blaze.base.wizard2.BlazeImportProjectAction$2.compute(BlazeImportProjectAction.java:66)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:512)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:87)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I am able to consistently repro this but sharing a minimal the codebase isn't posible.

### Which Intellij IDE are you using? Please provide the specific version.

Intellij ( IntelliJ IDEA 2023.2.2 (Ultimate Edition) )

### What programming languages and tools are you using? Please provide specific versions.

Java 11

### What Bazel plugin version are you using?

9999-3-sfdc-api-version-232

### Have you found anything relevant by searching the web?

Found this issue in the Intellij forums but this is something that the plugin authors would find easier to understand. 

https://intellij-support.jetbrains.com/hc/en-us/community/posts/7602780460306-Access-is-allowed-from-event-dispatch-thread-only

**Comment by sgowroji** [comment]
Hi @ashutoshraina, Could you please provide complete steps to reproduce this issue?

**Comment by ashutoshraina** [comment]
@sgowroji I can't share the project source code. But it is consistently reproducible. Is there any other way I can help ?
The steps are File -> Import New Project -> Choose the Top level directory with the workspace file -> Create From Scratch -> Failure

( thread dump is here : https://gist.github.com/ashutoshraina/264eb4e9bc1ce78001156c683825eb9d )
