### ISSUE TITLE
base:unit_tests are failing with Bazel@HEAD in CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#5483]
Android Studio Plugin Google: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3391#018b3b61-bbd5-464e-a239-01f3f141d9e5

Clion : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3391#018b3b61-d2e9-4398-ad8c-e2b6a2742139

IntelliJ Plugin Google : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3391#_

IntelliJ Plugin Aspect Google : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3391#018b3b61-d76b-4363-b4b4-dc3ae28a2a7a

Platform : Ubuntu

Logs:
```
java.io.FileNotFoundException: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/cad4910cbfe93a004f41fa4558f36929/sandbox/linux-sandbox/999/execroot/_main/bazel-out/k8-fastbuild/bin/base/unit_tests.runfiles/intellij_with_bazel/querysync/javatests/com/google/idea/blaze/qsync/testdata/java_library_nested_package (No such file or directory)
--
  | at java.base/java.io.FileInputStream.open0(Native Method)
  | at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
  | at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
  | at com.google.idea.blaze.qsync.query.QuerySummary.create(QuerySummary.java:218)
  | at com.google.idea.blaze.qsync.QuerySyncTestUtils.getQuerySummary(QuerySyncTestUtils.java:49)
  | at com.google.idea.blaze.qsync.TestDataSyncRunner.sync(TestDataSyncRunner.java:57)
  | at com.google.idea.blaze.base.qsync.DependencyTrackerImplTest.computeRequestedTargets_buildFile_nested(DependencyTrackerImplTest.java:90)
  |  
  | FAILURES!!!
  | Tests run: 451,  Failures: 4

//base:unit_tests                                                        FAILED

```

Steps:
```
git clone -v https://github.com/bazelbuild/intellij.git
git reset f4793aebf1e62d487ba64f04f4ef455f95846675 --hard
export USE_BAZEL_VERSION=2ddacab80af1dca3c04e74809827c47ec4bc8498
bazel test --define=ij_product=android-studio-latest --test_output=errors //:aswb_tests

```

CC Greenteam @fweikert

**Comment by meteorcloudy** [comment]
We also need to disable Bzlmod in the google branch, I'm sending a CL internally.

**Comment by sgowroji** [comment]
Thanks for fixing. CI is green now.
