### ISSUE TITLE
Can't debug Go projects in either GoLand or IntelliJ + Go Plugin

### ISSUE THREAD

**Issue by leepa** [bazelbuild/intellij#5504]
### Description of the bug:

When I import a project - I can run binaries/build etc. just fine but debugging doesn't work at all:

```
Error running 'Bazel run cmd:cmd': myExecutionScope is not initialized
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Grab any project like https://github.com/Shulammite-Aso/bazel-demo-app (although any fresh gazelle project will do) and try and debug main().

### Which Intellij IDE are you using? Please provide the specific version.

Build #GO-232.10072.27, built on October 11, 2023

### What programming languages and tools are you using? Please provide specific versions.

Go 1.21.3

### What Bazel plugin version are you using?

2023.09.26.0.1-api-version-232

**Comment by wcork** [comment]
I also had this issue. Had to revert to an older version of Intellij for the time being.

**Comment by kf-jb** [comment]
Relevant stack trace:

```
java.lang.IllegalStateException: myExecutionScope is not initialized
	at com.goide.execution.GoRunningState.getSearchScope(GoRunningState.java:498)
	at com.goide.execution.GoRunningState.execute(GoRunningState.java:134)
	at com.goide.execution.application.GoApplicationRunningState.execute(GoApplicationRunningState.java:83)
	at com.goide.execution.GoRunningState.execute(GoRunningState.java:122)
	at com.google.idea.blaze.golang.run.BlazeGoDebugRunner.doExecute(BlazeGoDebugRunner.java:85)
	at com.google.idea.blaze.golang.run.BlazeGoDebugRunner.execute(BlazeGoDebugRunner.java:77)
	at com.intellij.execution.runners.AsyncProgramRunner$execute$1.invoke(GenericProgramRunner.kt:48)
	at com.intellij.execution.runners.AsyncProgramRunner$execute$1.invoke(GenericProgramRunner.kt:47)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:207)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:205)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile$lambda$2(ExecutionManagerImpl.kt:269)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by vietage** [comment]
The method `GoApplicationRunningState.prepareStateInBGT()` should be called in a background thread somewhere in `BlazeGoDebugRunner` in order to initialise this variable and fix the problem.

**Comment by ujohnny** [comment]
This is a regression caused by GoLand 2023.2.3 update. As a workaround so far I can only recommend rolling back to 2023.2.2 released version.

**Comment by Trevor-L** [comment]
> This is a regression caused by GoLand 2023.2.3 update. As a workaround so far I can only recommend rolling back to 2023.2.2 released version.

This also occurs with IntelliJ/GoLand 2023.2.4.  Downgrading as stated above works as a fix.
