### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.google.idea.blaze.base.toolwindow.ConsoleView.getContent()" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by ujohnny** [bazelbuild/intellij#5559]
### Description of the bug:

Sometimes when `Sync` operation is invoked the following exception might occur. I checked briefly and it's caused by a race condition when event to select console in task tree arrives before the console is added to `consolesOfTasks` map. 

```
java.lang.NullPointerException: Cannot invoke "com.google.idea.blaze.base.toolwindow.ConsoleView.getContent()" because the return value of "java.util.Map.get(Object)" is null
	at com.google.idea.blaze.base.toolwindow.TasksTreeConsoleView.treeSelectionChanged(TasksTreeConsoleView.java:95)
	at com.google.idea.common.ui.properties.Property.triggerChangeListeners(Property.java:97)
	at com.google.idea.common.ui.properties.Property.setValue(Property.java:80)
	at com.google.idea.blaze.base.toolwindow.TasksTreeView$TaskNodeAutoExpandingListener.treeNodesInserted(TasksTreeView.java:387)
	at com.intellij.util.ui.tree.TreeModelListenerList.treeNodesInserted(TreeModelListenerList.java:85)
	at com.intellij.ui.tree.AsyncTreeModel.treeNodesInserted(AsyncTreeModel.java:364)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.setNode(AsyncTreeModel.java:663)
	at com.intellij.ui.tree.AsyncTreeModel$Command.accept(AsyncTreeModel.java:475)
	at com.intellij.ui.tree.AsyncTreeModel.lambda$submit$12(AsyncTreeModel.java:293)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:329)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:320)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:306)
...stripped
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Invoke sync operation. Not 100% reproducible

### Which Intellij IDE are you using? Please provide the specific version.

CLion-233.9802.5

### What Bazel plugin version are you using?

2a027bddc5105978ec45e98d04292c3482e1bc53

**Comment by iancha1992** [comment]
@ujohnny Could you please provide sample code to reproduce this issue? Thanks.

**Comment by ujohnny** [comment]
@iancha1992 sample code is not required. Any project from examples can be used to reproduce the issue.
