### ISSUE TITLE
Exception from bazel plugin while opening CMake project

### ISSUE THREAD

**Issue by ujohnny** [bazelbuild/intellij#5655]
### Description of the bug:

```
com.intellij.diagnostic.PluginException: Non-blaze project is provided [Plugin: com.google.idea.bazel.clwb]
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1.invokeSuspend(EditorNotificationsImpl.kt:251)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.IllegalStateException: Non-blaze project is provided
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	at com.google.idea.blaze.base.sync.data.DelegatingBlazeProjectDataManager.lambda$new$0(DelegatingBlazeProjectDataManager.java:39)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at com.google.idea.blaze.base.sync.data.DelegatingBlazeProjectDataManager.getBlazeProjectData(DelegatingBlazeProjectDataManager.java:50)
	at com.google.idea.blaze.base.lang.AdditionalLanguagesHelper.createNotificationPanel(AdditionalLanguagesHelper.java:109)
	at com.google.idea.blaze.base.lang.AdditionalLanguagesHelper.createNotificationPanel(AdditionalLanguagesHelper.java:57)
...
```

caused by 0ec12bf5e79bc5d6ac68f004997f060d2a2d070d

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In CLion `File -> New -> Project`

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2023.3

### What Bazel plugin version are you using?

 v2023.11.07-rc-1

**Comment by ujohnny** [comment]
@mai93 this should also happen for AS if non-bazel project is opened in AS like gradle one. Don't you already have a fix for it?

**Comment by ujohnny** [comment]
Ok this is really severe, with bazel plugin enabled it's even impossible to set a breakpoint in non-bazel project

```java.lang.IllegalStateException: Non-blaze project is provided
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	at com.google.idea.blaze.base.sync.data.DelegatingBlazeProjectDataManager.lambda$new$0(DelegatingBlazeProjectDataManager.java:39)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at com.google.idea.blaze.base.sync.data.DelegatingBlazeProjectDataManager.getBlazeProjectData(DelegatingBlazeProjectDataManager.java:50)
	at com.google.idea.blaze.skylark.debugger.SkylarkDebuggingUtils.debuggingEnabled(SkylarkDebuggingUtils.java:44)
	at com.google.idea.blaze.skylark.debugger.impl.SkylarkLineBreakpointType.canPutAt(SkylarkLineBreakpointType.java:43)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointUtil.getAvailableLineBreakpointInfo(XBreakpointUtil.java:203)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointUtil.toggleLineBreakpoint(XBreakpointUtil.java:134)
	at com.intellij.xdebugger.impl.actions.handlers.XToggleLineBreakpointActionHandler.perform(XToggleLineBreakpointActionHandler.java:74)
	at com.intellij.xdebugger.impl.actions.XDebuggerActionBase.perform(XDebuggerActionBase.java:78)
```
