### ISSUE TITLE
Fast test @[unknown repo 'intellij_aspect'

### ISSUE THREAD

**Issue by hakonph** [bazelbuild/intellij#5693]
### Description of the bug:

fails running fast tests.
Normal test works

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

clone [bazel examples](https://github.com/bazelbuild/examples/)
open java maven.
Try to run fast tests on java_test 

### Which Intellij IDE are you using? Please provide the specific version.

Build #IU-232.10227.8, built on November 9, 2023

### What Bazel plugin version are you using?

2023.10.24.0.2-api-version-232

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/intellij/issues/4067

### Any other information, logs, or outputs that you want to share?

ERROR: Unable to find package for @[unknown repo 'intellij_aspect' requested from @]//:fast_build_info_bundled.bzl: The repository '@[unknown repo 'intellij_aspect' requested from @]' could not be resolved: No repository visible as '@intellij_aspect' from main repository.
ERROR: Analysis of aspects '[@[unknown repo 'intellij_aspect' requested from @]//:fast_build_info_bundled.bzl%fast_build_info_aspect] with parameters {} on //:tests_deploy.jar' failed; build aborted: Unable to find package for @[unknown repo 'intellij_aspect' requested from @]//:fast_build_info_bundled.bzl: The repository '@[unknown repo 'intellij_aspect' requested from @]' could not be resolved: No repository visible as '@intellij_aspect' from main repository.

**Comment by mai93** [comment]
This should be fixed with ce6dd7efbdee5089ae1ec1cae2492bc425eb70ed and e03236aa51757caa3305c0df7de73315f5708399

**Comment by hakonph** [comment]
When i try the new version it works the first time (when it builds with bazel) and continues to work if i run it again without changing anything.
when i change anything it i get 
![CleanShot 2023-11-23 at 13 13 23@2x](https://github.com/bazelbuild/intellij/assets/29750038/7234aebe-72cf-4822-9807-a4e2b9c2d79f)

and in the intelij building the extention i get:
 ```
cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x48dd0189
	at com.google.idea.blaze.java.fastbuild.FastBuildJavacImpl.compile(FastBuildJavacImpl.java:53)
```

this happens when i run it in dev mode or build the extension with `bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-oss-latest-stable` and loads it


i am using:
```
build_flags:
  --define=ij_product=intellij-ue-latest
```

ful stack trace:
```
023-11-23 13:19:29,370 [  39203]   WARN - #c.i.o.a.ActionStub - ActionGroup should be registered using <group> tag: id="RunProfileGroup" class="com.intellij.profiler.ultimate.welcome.actions.RunProfileGroup"
2023-11-23 13:19:55,280 [  65113]   WARN - #com.google.idea.blaze.java.run.fastbuild.FastBuildConfigurationRunner - java.lang.reflect.UndeclaredThrowableException
java.util.concurrent.ExecutionException: java.lang.reflect.UndeclaredThrowableException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.google.idea.blaze.java.run.fastbuild.FastBuildConfigurationRunner.executeBeforeRunTask(FastBuildConfigurationRunner.java:148)
	at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:118)
	at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:38)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun$lambda$5(ExecutionManagerImpl.kt:434)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.google.idea.blaze.java.fastbuild.$Proxy246.compile(Unknown Source)
	at com.google.idea.blaze.java.fastbuild.FastBuildCompilerFactoryImpl.lambda$createCompiler$1(FastBuildCompilerFactoryImpl.java:163)
	at com.google.idea.blaze.java.fastbuild.FastBuildCompilerFactoryImpl$JavacRunner.compile(FastBuildCompilerFactoryImpl.java:267)
	at com.google.idea.blaze.java.fastbuild.FastBuildIncrementalCompilerImpl.lambda$compile$0(FastBuildIncrementalCompilerImpl.java:86)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.idea.blaze.java.fastbuild.FastBuildCompilerFactoryImpl$MatchingMethodInvocationHandler.invoke(FastBuildCompilerFactoryImpl.java:348)
	... 15 more
Caused by: java.lang.IllegalAccessError: class com.google.idea.blaze.java.fastbuild.FastBuildJavacImpl (in unnamed module @0x48dd0189) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x48dd0189
	at com.google.idea.blaze.java.fastbuild.FastBuildJavacImpl.compile(FastBuildJavacImpl.java:53)
	... 20 more
2023-11-23 13:19:55,283 [  65116]   WARN - #c.i.e.r.ExecutionUtil - Execution error without description
com.intellij.execution.ExecutionException
	at com.google.idea.blaze.java.run.fastbuild.FastBuildConfigurationRunner.executeBeforeRunTask(FastBuildConfigurationRunner.java:177)
	at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:118)
	at com.google.idea.blaze.base.run.BlazeBeforeRunTaskProvider.executeTask(BlazeBeforeRunTaskProvider.java:38)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun$lambda$5(ExecutionManagerImpl.kt:434)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.google.idea.blaze.java.fastbuild.$Proxy246.compile(Unknown Source)
	at com.google.idea.blaze.java.fastbuild.FastBuildCompilerFactoryImpl.lambda$createCompiler$1(FastBuildCompilerFactoryImpl.java:163)
	at com.google.idea.blaze.java.fastbuild.FastBuildCompilerFactoryImpl$JavacRunner.compile(FastBuildCompilerFactoryImpl.java:267)
	at com.google.idea.blaze.java.fastbuild.FastBuildIncrementalCompilerImpl.lambda$compile$0(FastBuildIncrementalCompilerImpl.java:86)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.idea.blaze.java.fastbuild.FastBuildCompilerFactoryImpl$MatchingMethodInvocationHandler.invoke(FastBuildCompilerFactoryImpl.java:348)
	... 15 more
Caused by: java.lang.IllegalAccessError: class com.google.idea.blaze.java.fastbuild.FastBuildJavacImpl (in unnamed module @0x48dd0189) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x48dd0189
	at com.google.idea.blaze.java.fastbuild.FastBuildJavacImpl.compile(FastBuildJavacImpl.java:53)
	... 20 more

```

**Comment by mai93** [comment]
maybe you need to add these flags to the VM Options to open the required modules for using javac directly in fast builds. You can add these flags from (Help -> Edit Custom VM Options):

```
--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
```

**Comment by hakonph** [comment]
Thanks.
I added them to the run config then it worked.
