### ISSUE TITLE
Android Studio Plugin built on top of `master` branch instantly crashes IDE

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/intellij#5712]
### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-2022.3` on top of the latest master branch commit https://github.com/bazelbuild/intellij/commit/4ff725a18978f3235615278538985f020a9d3a43 , apply the generated plugin to AS 2022.3. IDE will crash upon opening project

### Which Intellij IDE are you using? Please provide the specific version.

AS 2022.3

### Any other information, logs, or outputs that you want to share?
```
2023-11-17 11:27:00,215 [ 122936] SEVERE - #c.i.o.p.i.ProjectManagerImpl - Fatal error initializing 'com.google.idea.blaze.cpp.BlazeCWorkspace' [Plugin: com.google.idea.bazel.aswb]
com.intellij.diagnostic.PluginException: Fatal error initializing 'com.google.idea.blaze.cpp.BlazeCWorkspace' [Plugin: com.google.idea.bazel.aswb]
	at com.intellij.serviceContainer.ComponentManagerImpl.handleInitComponentError$intellij_platform_serviceContainer(ComponentManagerImpl.kt:571)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:59)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:19)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:181)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponentsNonBlocking(ComponentManagerImpl.kt:428)
	at com.intellij.serviceContainer.ComponentManagerImpl$createComponentsNonBlocking$1.invokeSuspend(ComponentManagerImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.NoClassDefFoundError: com/jetbrains/cidr/lang/OCLanguageKind
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.base/java.lang.Class.getDeclaredConstructors(Unknown Source)
	at com.intellij.serviceContainer.ConstructorInjectionKt.getSortedMatchingConstructors(constructorInjection.kt:196)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:29)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:996)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:36)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.jetbrains.cidr.lang.OCLanguageKind PluginClassLoader(plugin=PluginDescriptor(name=Bazel for Android Studio, id=com.google.idea.bazel.aswb, descriptorPath=plugin.xml, path=~/Library/Application Support/Google/AndroidStudio2022.3/plugins/aswb, version=9999-api-version-223, package=null, isBundled=false), packagePrefix=null, instanceId=102, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:217)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 27 more
2023-11-17 11:27:00,218 [ 122939] SEVERE - #c.i.o.p.i.ProjectManagerImpl - Android Studio Giraffe | 2022.3.1 Patch 3  Build #AI-223.8836.35.2231.11005911
2023-11-17 11:27:00,218 [ 122939] SEVERE - #c.i.o.p.i.ProjectManagerImpl - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-11-17 11:27:00,219 [ 122940] SEVERE - #c.i.o.p.i.ProjectManagerImpl - OS: Mac OS X
2023-11-17 11:27:00,219 [ 122940] SEVERE - #c.i.o.p.i.ProjectManagerImpl - Plugin to blame: Bazel for Android Studio version: 9999-api-version-223
```

**Comment by sgowroji** [comment]
Hi @ThomasCJY, Could you please provide complete steps to reproduce this issue?

**Comment by mai93** [comment]
thanks @ThomasCJY for reporting this! I tried to reproduce the problem and I got the error reported in https://github.com/bazelbuild/intellij/issues/5695. If this is the same error you get, there is a pending fix for it in https://github.com/bazelbuild/intellij/pull/5714. If you are getting a different error, can you please share it?

**Comment by ThomasCJY** [comment]
@mai93 Do you know where I can find the crash stacktrace? The IDE crashes immediately after I clicking the project name from the project selection page.

**Comment by mai93** [comment]
For me the error shows up in a (IDE Internal Failure) notification, but maybe you can check the logs from (Help -> Show Log in Files)

**Comment by ThomasCJY** [comment]
OK looks like a different issue. I rebuilt the plugin based on [this commit](https://github.com/bazelbuild/intellij/commit/72dc1e853f3852390903909d140d9bc1446722e9) and still hit the crash. The log shows

```
2023-11-17 11:27:00,215 [ 122936] SEVERE - #c.i.o.p.i.ProjectManagerImpl - Fatal error initializing 'com.google.idea.blaze.cpp.BlazeCWorkspace' [Plugin: com.google.idea.bazel.aswb]
com.intellij.diagnostic.PluginException: Fatal error initializing 'com.google.idea.blaze.cpp.BlazeCWorkspace' [Plugin: com.google.idea.bazel.aswb]
	at com.intellij.serviceContainer.ComponentManagerImpl.handleInitComponentError$intellij_platform_serviceContainer(ComponentManagerImpl.kt:571)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:59)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:19)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:181)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponentsNonBlocking(ComponentManagerImpl.kt:428)
	at com.intellij.serviceContainer.ComponentManagerImpl$createComponentsNonBlocking$1.invokeSuspend(ComponentManagerImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.NoClassDefFoundError: com/jetbrains/cidr/lang/OCLanguageKind
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.base/java.lang.Class.getDeclaredConstructors(Unknown Source)
	at com.intellij.serviceContainer.ConstructorInjectionKt.getSortedMatchingConstructors(constructorInjection.kt:196)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:29)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:996)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:36)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.jetbrains.cidr.lang.OCLanguageKind PluginClassLoader(plugin=PluginDescriptor(name=Bazel for Android Studio, id=com.google.idea.bazel.aswb, descriptorPath=plugin.xml, path=~/Library/Application Support/Google/AndroidStudio2022.3/plugins/aswb, version=9999-api-version-223, package=null, isBundled=false), packagePrefix=null, instanceId=102, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:217)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 27 more
2023-11-17 11:27:00,218 [ 122939] SEVERE - #c.i.o.p.i.ProjectManagerImpl - Android Studio Giraffe | 2022.3.1 Patch 3  Build #AI-223.8836.35.2231.11005911
2023-11-17 11:27:00,218 [ 122939] SEVERE - #c.i.o.p.i.ProjectManagerImpl - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-11-17 11:27:00,219 [ 122940] SEVERE - #c.i.o.p.i.ProjectManagerImpl - OS: Mac OS X
2023-11-17 11:27:00,219 [ 122940] SEVERE - #c.i.o.p.i.ProjectManagerImpl - Plugin to blame: Bazel for Android Studio version: 9999-api-version-223
```

**Comment by mai93** [comment]
I do not see this error in the logs. This is the AS version I'm using (Build #AI-223.8836.35.2231.11090377, built on November 13, 2023) and I'm using a project based on (https://github.com/bazelbuild/examples/tree/main/android/tutorial) , I'm not sure if it will make a difference but can you try building the plugin from the [google branch](https://github.com/bazelbuild/intellij/tree/google) and see if it causes a similar failure?

**Comment by ThomasCJY** [comment]
The log is from `idea.log`, google branch works fine

**Comment by mai93** [comment]
Please take a look @ujohnny, because if it cannot be fixed we need to clearly communicate this to the users.

**Comment by ThomasCJY** [comment]
@ujohnny any update?

**Comment by ThomasCJY** [comment]
@mai93 @ujohnny any update?
