### ISSUE TITLE
Android Studio UI Freezing while editing bazel build scripts

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/intellij#5719]
### Description of the bug:

We received a lot of UI freeze reports from our android studio users. The issue happens while trying to edit the bazel build script. The UI freeze usually lasts for a few minutes, and then will stop happening for a while until the next time developer reopen the project.

System info:
AI-223.8836.35.2231.11005911, JRE 17.0.6+0-17.0.6b829.9-10027231x64 JetBrains s.r.o., OS Mac OS X(aarch64) v13.5.2, screens 2560.0x1440.0

AS: Giraffe | 2022.3.1 Patch 3
Kotlin plugin: 223-1.9.0-release-358-AS8836.35.2231.11005911
Android Gradle Plugin: (plugin information not found)
Gradle: (gradle version information not found)
Gradle JDK: JetBrains Runtime version 17.0.6
NDK: from local.properties: (not specified), latest from SDK: (not found)
CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)
Bazel Plugin: v2023.10.24 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
#com.android.tools.idea.diagnostics.DiagnosticReportIdePerformanceListener - uiFreezeStarted
2023-11-16 10:42:21,001 [ 107256]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1367 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getFocusOwner(Unknown Source)
...

AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on com.intellij.openapi.application.impl.ReadMostlyRWLock@27144084
	at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.6/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.writeLock(ReadMostlyRWLock.java:236)
	at com.intellij.openapi.application.impl.ApplicationImpl.startWrite(ApplicationImpl.java:1173)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:978)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler.execute(DefaultRawTypedHandler.java:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$MyRawTypedHandler.execute(EditorFactoryImpl.java:295)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$2(TypedAction.java:200)
	at com.intellij.openapi.editor.actionSystem.TypedAction$$Lambda$4915/0x000000080261fc98.run(Unknown Source)
...

DefaultDispatcher-worker-10" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on java.lang.Class@6a957f40 owned by "DefaultDispatcher-worker-17" Id=28
	at com.google.idea.blaze.base.sync.workspace.WorkspaceHelper.getExternalWorkspaceRoots(WorkspaceHelper.java:161)
	at com.google.idea.blaze.base.sync.workspace.WorkspaceHelper.resolveBlazePackage(WorkspaceHelper.java:67)
	at com.google.idea.blaze.base.lang.buildfile.references.BuildReferenceManager.resolveLabel(BuildReferenceManager.java:69)
	at com.google.idea.blaze.base.lang.buildfile.references.BuildReferenceManager.resolveLabel(BuildReferenceManager.java:63)
	at com.google.idea.blaze.base.lang.buildfile.references.LabelReference.resolveTarget(LabelReference.java:70)
	at com.google.idea.blaze.
```

### Which Intellij IDE are you using? Please provide the specific version.

AS 2022.3

### What programming languages and tools are you using? Please provide specific versions.

android

### What Bazel plugin version are you using?

v2023.10.24

### Any other information, logs, or outputs that you want to share?

[threadDumps-freeze-20231117-113455-AI-223.8836.35.2231.11005911-108sec.zip](https://github.com/bazelbuild/intellij/files/13396553/threadDumps-freeze-20231117-113455-AI-223.8836.35.2231.11005911-108sec.zip)
[threadDumps-freeze-20231116-104127-AI-223.8836.35.2231.11005911-172sec.zip](https://github.com/bazelbuild/intellij/files/13396556/threadDumps-freeze-20231116-104127-AI-223.8836.35.2231.11005911-172sec.zip)

**Comment by ThomasCJY** [comment]
@sgowroji did you get a chance to take a look?

**Comment by mai93** [comment]
The issue is given P3 which means, the issue only affects 3P users and AS team is willing to review PRs fixing it

**Comment by mai93** [comment]
insights from the internal team that can help while working on a fix : 

> It looks like the IDE is ultimately blocked because it's enumerating the contents of the `<bazel-output-base>/external` directory. That could explain the slowness.

**Comment by nkorostelev-sc** [comment]
Just found this related bug https://github.com/bazelbuild/rules_jvm_external/issues/559

**Comment by ThomasCJY** [comment]
@mai93 can we include this fix https://github.com/bazelbuild/intellij/pull/6530 into google branch?
