### ISSUE TITLE
2024.1: com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/intellij#5993]
### Description of the bug:

When using the plugin, this exception is thrown frequently (not only for `BlazeMenuGroup`)
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.google.idea.blaze.base.actions.BlazeMenuGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.google.idea.bazel.ijwb]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:198)
```

### Which Intellij IDE are you using? Please provide the specific version.
IntelliJ 2024.1

_No response_

**Comment by ujohnny** [comment]
fixed by #6101
