### ISSUE TITLE
Unable to connect to Dev Environment with Gateway after plugin installation

### ISSUE THREAD

**Issue by LeFrosch** [bazelbuild/intellij#6129]
### Description of the bug:

After installing the plugin on the host machine and restarting I am no longer able to connect to it using gateway. The environment is also marked as `unhealthy`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a new Dev Environment in Space. Connect to it using CLion and install the plugin.

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2023.3.4 and Gateway 2023.3.4

### Any other information, logs, or outputs that you want to share?

I found this exception in the logs after installing the plugin:
```
[10:10:25]	Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Graphics.setClip(java.awt.Shape)" because "g" is null
[10:10:25]		at java.desktop/javax.swing.JViewport.setViewPosition(JViewport.java:1216)
[10:10:25]		at com.intellij.ui.components.JBViewport.setViewPosition(JBViewport.java:106)
[10:10:25]		at java.desktop/javax.swing.JViewport.scrollRectToVisible(JViewport.java:445)
[10:10:25]		at com.intellij.ui.components.JBViewport.scrollRectToVisible(JBViewport.java:278)
[10:10:25]		at java.desktop/javax.swing.JComponent.scrollRectToVisible(JComponent.java:3176)
[10:10:25]		at java.desktop/javax.swing.JComponent.scrollRectToVisible(JComponent.java:3176)
[10:10:25]		at com.intellij.ide.navbar.ui.NewNavBarPanel.rebuild(NewNavBarPanel.kt:153)
[10:10:25]		at com.intellij.ide.navbar.ui.NewNavBarPanel.access$rebuild(NewNavBarPanel.kt:54)
[10:10:25]		at com.intellij.ide.navbar.ui.NewNavBarPanel$rebuild$1.invokeSuspend(NewNavBarPanel.kt)
[10:10:25]		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[10:10:25]		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
[10:10:25]		at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
[10:10:25]		at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
[10:10:25]		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
[10:10:25]		at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
[10:10:25]		at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[10:10:25]		at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[10:10:25]		at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
[10:10:25]		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
[10:10:25]		at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
[10:10:25]		at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
[10:10:25]		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
[10:10:25]		at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
[10:10:25]		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
[10:10:25]		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
[10:10:25]		at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
[10:10:25]		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
[10:10:25]		at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
[10:10:25]		at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
[10:10:25]		at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
[10:10:25]		at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
[10:10:25]		at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
[10:10:25]		at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
[10:10:25]		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
[10:10:25]		at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
[10:10:25]		at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
[10:10:25]		at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
[10:10:25]		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
[10:10:25]		at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
[10:10:25]		at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
[10:10:25]		Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2716e8bb, Dispatchers.EDT]
```

**Comment by sgowroji** [comment]
Hi @LeFrosch, Can you provide complete steps to reproduce the issue. Thanks!

**Comment by LeFrosch** [comment]
This is what I did:

1. Create a new dev environment in the space based on [this](https://github.com/LeFrosch/bazel-cpp-stage1) repo.
<img width="500" alt="Screenshot 2024-02-22 at 12 20 03 PM" src="https://github.com/bazelbuild/intellij/assets/44034965/68978587-41b5-4d16-866b-53730ce88630">

2. Connect to this environment using gateway
3. In the settings install the `Bazel for CLion` plugin
<img width="500" alt="Screenshot 2024-02-22 at 12 22 57 PM" src="https://github.com/bazelbuild/intellij/assets/44034965/81947a80-9d6f-477f-83da-41aea006957a">

4. Click the restart button

Afterwards I was no longer able to connect to the environment. However, I just tired it again to retrace my steps and this time it worked. This was my fourth try.

**Comment by LeFrosch** [comment]
@tpasternak I was able to connect successfully using your instructions after some tries:

1. Open the project, so it's imported incorrectly
2. Install Bazel plugin
3. close the project
4. remove .idea
5. open the project again with bazel plugin installed 

Once the project was setup in gateway I had no problems connecting.
