### ISSUE TITLE
[Bazel CI] Error: 'struct' value has no field or method 'to_json'


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#6304]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3740#018e5f2f-9612-417e-a7e4-4d8966fbd9db

 Platform: Ubuntu

 Logs: 
```
 ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/787f4f46ed8306be338b0f8a082a0178/external/io_bazel_rules_scala/third_party/dependency_analyzer/src/main/BUILD:3:9: in scala_library_for_plugin_bootstrapping rule @@io_bazel_rules_scala//third_party/dependency_analyzer/src/main:scala_version:
Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/787f4f46ed8306be338b0f8a082a0178/external/io_bazel_rules_scala/scala/private/rules/scala_library.bzl", line 144, column 22, in _scala_library_for_plugin_bootstrapping_impl
		return run_phases(
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/787f4f46ed8306be338b0f8a082a0178/external/io_bazel_rules_scala/scala/private/phases/api.bzl", line 45, column 23, in run_phases
		return _run_phases(ctx, builtin_customizable_phases, target = None)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/787f4f46ed8306be338b0f8a082a0178/external/io_bazel_rules_scala/scala/private/phases/api.bzl", line 77, column 32, in _run_phases
		new_provider = function(ctx, current_provider)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/787f4f46ed8306be338b0f8a082a0178/external/io_bazel_rules_scala/scala/private/phases/phase_default_info.bzl", line 20, column 23, in phase_default_info
		phase_names.remove("to_json")
Error in remove: item "to_json" not found in list
``` 
 Culprit: https://github.com/bazelbuild/bazel/commit/8f18d362c852377740cb032b02c42d78b9a44ad0

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/intellij
git reset 0a1dcd43300efbee1d120be7527be32096936531  --hard
export USE_BAZEL_VERSION=b100e4f1631da2d7c78621c040e88b7644985cd8
bazel test //aspect/testing/... 
 ``` 
 CC Greenteam @salmasamy

**Comment by sgowroji** [comment]
CC [@c-mita](https://github.com/c-mita)

**Comment by mai93** [comment]
Fixed with https://github.com/bazelbuild/intellij/commit/7f32fc1404cad8989299fa7916a2a3c208b3e01f
