### ISSUE TITLE
facing issue with kt_jvm_library 

### ISSUE THREAD

**Issue by ChaitanyaDuse** [bazelbuild/intellij#6446]
### Description of the bug:

All builds fail with "Error in kt_jvm_library"

Error log -

ERROR: /project/dagger/java/dagger/spi/model/BUILD:36:15: in kt_jvm_library rule //java/dagger/spi/model:model: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_cd/f202618f9a0c0f8e33bf23f70a8036c4/external/io_bazel_rules_kotlin/kotlin/internal/jvm/impl.bzl", line 221, column 36, in kt_jvm_library_impl
                _kt_jvm_produce_jar_actions(ctx, "kt_jvm_library") if ctx.attr.srcs or ctx.attr.resources else export_only_providers(
        File "/private/var/tmp/_bazel_cd/f202618f9a0c0f8e33bf23f70a8036c4/external/io_bazel_rules_kotlin/kotlin/internal/jvm/compile.bzl", line 535, column 50, in kt_jvm_produce_jar_actions
                outputs_struct = _run_kt_java_builder_actions(
        File "/private/var/tmp/_bazel_cd/f202618f9a0c0f8e33bf23f70a8036c4/external/io_bazel_rules_kotlin/kotlin/internal/jvm/compile.bzl", line 794, column 36, in _run_kt_java_builder_actions
                _run_merge_jdeps_action(
        File "/private/var/tmp/_bazel_cd/f202618f9a0c0f8e33bf23f70a8036c4/external/io_bazel_rules_kotlin/kotlin/internal/jvm/compile.bzl", line 264, column 70, in _run_merge_jdeps_action
                inputs = depset(jdeps, transitive = [depset([], transitive = [dep.transitive_deps for dep in deps])])
Error: 'JavaInfo' value has no field or method 'transitive_deps'
Available attributes: _compile_time_java_dependencies, _constraints, _neverlink, _transitive_full_compile_time_jars, annotation_processing, api_generating_plugins, compilation_info, compile_jars, full_compile_jars, java_outputs, module_flags_info, outputs, plugins, runtime_output_jars, source_jars, transitive_compile_time_jars, transitive_native_libraries, transitive_runtime_jars, transitive_source_jars
ERROR: /Users/cd/project/dagger/java/dagger/spi/model/BUILD:36:15: Analysis of target '//java/dagger/spi/model:model' failed
ERROR: Analysis of target '//java/dagger/spi:spi' failed; build aborted: Analysis failed
INFO: Elapsed time: 124.500s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
checkout dagger latest tag .https://github.com/google/dagger/releases/tag/dagger-2.51.1

_No response_

### Which Intellij IDE are you using? Please provide the specific version.
Android Studio Giraffe 2022.3.1 Patch 4

_No response_

### What Bazel plugin version are you using?
2024.01.16-aswb.0.1-api-version-223
Bazel version istalled from homebrew 7.1.2 

_No response_

**Comment by mai93** [comment]
I think this is not related to the plugin and it is similar to https://github.com/bazelbuild/rules_jvm_external/issues/946 which is fixed by upgrading `rules_kotlin` version https://github.com/bazelbuild/rules_jvm_external/pull/999
