### ISSUE TITLE
[Bazel CI] Unit tests failed in build


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#6607]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4026#01910c21-7919-4709-b5e8-675f6fba3766

 Platform: Ubuntu

 Logs: 
```
//base:unit_tests FAILED 

1) getPendingExternalDeps_followJavaDeps_allBuilt(com.google.idea.blaze.base.qsync.DependencyTrackerImplTest)
value of: getPendingExternalDeps(...)
expected to be empty
but was : [@@rules_jvm_external++maven+com_google_guava_guava//jar:jar]
	at com.google.idea.blaze.base.qsync.DependencyTrackerImplTest.getPendingExternalDeps_followJavaDeps_allBuilt(DependencyTrackerImplTest.java:91)
2) getPendingExternalDeps_followJavaDeps_noneBuilt(com.google.idea.blaze.base.qsync.DependencyTrackerImplTest)
value of       : getPendingExternalDeps(...)
missing (1)    : @@com_google_guava_guava//jar:jar
unexpected (1) : [@@rules_jvm_external++maven+com_google_guava_guava//jar:jar]
---
expected       : [@@com_google_guava_guava//jar:jar]
testing whether: actual element is repository-mapped equal to expected element
but was        : [@@rules_jvm_external++maven+com_google_guava_guava//jar:jar]
	at com.google.idea.blaze.base.qsync.DependencyTrackerImplTest.getPendingExternalDeps_followJavaDeps_noneBuilt(DependencyTrackerImplTest.java:76)
FAILURES!!!
Tests run: 459,  Failures: 2
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/intellij
git reset d4fcd51e0c7dcb94e22154f1d0a50d241b2eb6d3  --hard
export USE_BAZEL_VERSION=a7264d99e2d14463cb683a4091d5ad0e08431205
bazel test --define=ij_product=android-studio-latest //:aswb_tests 
 ``` 
 CC Greenteam @fweikert

**Comment by sgowroji** [comment]
Also seen in 

Clion [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4026#01910c21-6ced-4872-b8e5-44414a605cf9](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4026#01910c21-6ced-4872-b8e5-44414a605cf9)

Intellij : [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4026#01910c21-70db-4bfc-9468-b6e1a31b6c79](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4026#01910c21-70db-4bfc-9468-b6e1a31b6c79)

IntelliJ Aspect : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4026#01910c21-722e-4aa5-9b72-5c0ba3161d06
