### ISSUE TITLE
Exception when doing sync

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/intellij#6721]
### Description of the bug:

comit 4acdddd9a9

```
Could not save cache data file to disk.

java.lang.NullPointerException
	at com.google.devtools.intellij.model.ProjectData$ExternalWorkspace$Builder.setRepoName(ProjectData.java:35490)
	at com.google.idea.blaze.base.model.primitives.ExternalWorkspace.toProto(ExternalWorkspace.java:31)
	at com.google.idea.blaze.base.model.ExternalWorkspaceData.toProto(ExternalWorkspaceData.java:38)
	at com.google.idea.blaze.base.model.AspectSyncProjectData.toProto(AspectSyncProjectData.java:119)
	at com.google.idea.blaze.base.model.AspectSyncProjectData.saveToDisk(AspectSyncProjectData.java:218)
	at com.google.idea.blaze.base.sync.data.AspectSyncProjectDataManager.lambda$saveProject$0(AspectSyncProjectDataManager.java:103)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:83)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:131)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:131)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by tpasternak** [comment]
![Screenshot 2024-09-04 at 09 34 14](https://github.com/user-attachments/assets/a9041929-62b6-40d9-b3a1-88efdf588aa7)

**Comment by tpasternak** [comment]
cc @mtoader

**Comment by mtoader** [comment]
These proto wrappers are going to be the death of me :). I can put the fix in the pending PR or open another one. What do you prefer ?

**Comment by tpasternak** [comment]
no hurry, please open another one

**Comment by mtoader** [comment]
Opened
