### ISSUE TITLE
java.lang.NullPointerException: Null workingSet

### ISSUE THREAD

**Issue by dgarzon** [bazelbuild/intellij#682]
Hi,

Today I updated to the latest version of the Bazel Plugin on IntelliJ 2018.3, and I keep getting the following when syncing my project:

```
java.lang.NullPointerException: Null workingSet
	at com.google.idea.blaze.base.sync.AutoValue_BlazeSyncBuildResult$Builder.setWorkingSet(AutoValue_BlazeSyncBuildResult.java:249)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.runBuildPhase(BlazeSyncTask.java:507)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:292)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:237)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:196)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:163)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:76)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$2(ProgressiveTaskWithProgressIndicator.java:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$3(ProgressiveTaskWithProgressIndicator.java:110)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Any ideas what it means? I am able to build my project from the terminal, but it fails every single time on IntelliJ. I tried cleaning up the caches, etc, to no success!

**Comment by dgarzon** [comment]
For future reference, running: `bazel clean --expunge` outside IntelliJ made it work. Thanks!

**Comment by dgarzon** [comment]
Actually, it did not. After it built everything, it threw the exception:
```
INFO: Elapsed time: 50.640s, Critical Path: 3.18s
INFO: 8 processes: 4 darwin-sandbox, 4 worker.
blaze build result: success
Total rules: 286, new/changed: 11, removed: 0
Reading IDE info result...
Loaded 11 aspect files, total size 42kB
build invocation result: success
Target map size: 191

==== TIMING REPORT ====

Sync: 51.2s
    BazelInfo: 378ms
    WorkingSet: 0ms
    BlazeBuild: 50.7s
        ExecuteBlazeCommand: 50.7s
        CombinedBlazeBuild: 28ms
        FetchAspectOutput: 1ms
        UpdateTargetMap: 5ms
        GenfilesPrefetchBuildArtifacts: 0ms
    UpdateRemoteOutputsCache: 0ms

Timing summary:

BlazeInvocation: 51.1s
Prefetching: 1ms
Other: 33ms
Sync failed
```

**Comment by chaoren** [comment]
Hi, this has been fixed. You can build the bazel plugin at HEAD if you want the fix immediately or wait until next week when we push the latest plugin to the repository.
