### ISSUE TITLE
plugin crashes and makes other IDE features unavailable

### ISSUE THREAD

**Issue by jdn-kvantify** [bazelbuild/intellij#6832]
### Description of the bug:

When installing and enabling the plugin, navigation and inspection stops working (for python sources at least). The error:
```
java.lang.IllegalArgumentException: Components of QualifiedName cannot contain dots inside them, but got: python3.11
	at com.intellij.psi.util.QualifiedName.assertNoDots(QualifiedName.java:195)
	at com.intellij.psi.util.QualifiedName.fromComponents(QualifiedName.java:35)
	at com.google.idea.blaze.python.resolve.provider.AbstractPyImportResolverStrategy.assembleImportRoots(AbstractPyImportResolverStrategy.java:244)
	at com.google.idea.blaze.python.resolve.provider.AbstractPyImportResolverStrategy.buildSourcesIndex(AbstractPyImportResolverStrategy.java:127)
	at com.google.idea.blaze.base.sync.SyncCache.get(SyncCache.java:61)
	at com.google.idea.blaze.python.resolve.provider.AbstractPyImportResolverStrategy.getSourcesIndex(AbstractPyImportResolverStrategy.java:117)
	at com.google.idea.blaze.python.resolve.provider.AbstractPyImportResolverStrategy.resolveFromSyncData(AbstractPyImportResolverStrategy.java:79)
	at com.google.idea.blaze.python.resolve.PyDynamicImportResolverInitializer.lambda$registerImportResolvers$0(PyDynamicImportResolverInitializer.java:51)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt:205)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil$foreignResults$1.invoke(PyResolveImportUtil.kt:203)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil.foreignResults(PyResolveImportUtil.kt:209)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil.resolveQualifiedName(PyResolveImportUtil.kt:78)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.getSkeletonFile(PyBuiltinCache.java:161)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.getBuiltinsForSdk(PyBuiltinCache.java:140)
	at com.jetbrains.python.psi.resolve.PythonSdkPathCache.getBuiltins(PythonSdkPathCache.java:112)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.getInstance(PyBuiltinCache.java:88)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.isInBuiltins(PyBuiltinCache.java:402)
	at com.jetbrains.python.validation.PyBuiltinAnnotator.visitPyReferenceExpression(PyBuiltinAnnotator.java:39)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.acceptPyVisitor(PyReferenceExpressionImpl.java:86)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:58)
	at com.jetbrains.python.validation.PyAnnotator.annotateElement(PyAnnotator.java:46)
	at com.jetbrains.python.validation.PyAnnotatorBase.runAnnotators(PyAnnotatorBase.java:23)
	at com.jetbrains.python.validation.PyAnnotatingVisitor.annotate(PyAnnotatingVisitor.java:52)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.runAnnotatorWithContext(AnnotationHolderImpl.java:216)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotator$2(AnnotatorRunner.java:129)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotator(AnnotatorRunner.java:119)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$0(AnnotatorRunner.java:66)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:279)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$1(AnnotatorRunner.java:66)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:196)
	at com.intellij.concurrency.ApplierCompleter.execAll(ApplierCompleter.java:166)
	at com.intellij.concurrency.ApplierCompleter.lambda$exec$0(ApplierCompleter.java:105)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapAndRun$1(ApplierCompleter.java:140)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:140)
	at com.intellij.concurrency.ApplierCompleter.exec(ApplierCompleter.java:108)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)```

### Which category does this issue belong to?

Intellij

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.


install plugin, go to some source and put the cursor on an element that you could navigate from with e.g. ctrl-b (e.g. class name) and the error is reported by IDE

### Which Intellij IDE are you using? Please provide the specific version.


IntelliJ IDEA 2024.2.3 (Community Edition) Build #IC-242.23339.11, built on September 25, 2024 Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9) VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Toolkit: sun.awt.X11.XToolkit Linux 6.5.0-1025-oem GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation Memory: 8000M Cores: 16 Registry:   ide.experimental.ui=true   i18n.locale= Non-Bundled Plugins:   com.redhat.devtools.lsp4ij (0.6.0)   PythonCore (242.23339.11)   com.maaxgr.intellij.jsonviewer (1.0.19)   org.jetbrains.plugins.hocon (2024.2.0)   aws.toolkit.core (3.30-242)   com.google.idea.bazel.ijwb (2024.09.10.0.1-api-version-242)   aws.toolkit (3.30-242) Kotlin: 242.23339.11-IJ Current Desktop: ubuntu:GNOME

### What programming languages and tools are you using? Please provide specific versions.


python 

### What Bazel plugin version are you using?


2024.09.10.0.1-api-version-242

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

**Comment by agluszak** [comment]
Can you please share a minimal reproducible example? What you described seems to be possible only in a very specific scenario. Is there something special in your python setup? Can you reproduce it with a hermetic python toolchain?

**Comment by jdn-kvantify** [comment]
> Can you please share a minimal reproducible example? What you described seems to be possible only in a very specific scenario. Is there something special in your python setup? Can you reproduce it with a hermetic python toolchain?

@agluszak yes, will look into creating a minimal example. However, I am not sure it is related to my python setup, as it used to work with the same python setting I have now where I use a conda enviroment as project interpreter (we are using a hermetic python toolchain for  bazel).

For now my workaround is downgrading the plugin to 2024.07.16.0.1-api-version-242 and everything works for me with no other change. If you wish we can close the issue for now and I will test future stable releases.

**Comment by 97jake** [comment]
Any updates on this? I'm getting the same issue right now with 

- Intellij build `Build #IU-243.23654.189` 
- Bazel plugin `2025.01.07.0.1-api-version-243`
- Python 3.11.10

**Comment by leaqigaie** [comment]
I have same problem too. In my case, this is caused by directory name with dots (`.`). 
Current implementation seemed to do not allow such directory, I don't know this is a bug or specification.

This is minimal reproducible example.
https://github.com/leaqigaie/bazel-intellij-issue6832

If you click `from .lib1 import Lib1` in `package1.lib/src/package1_lib1/__init__.py` file (to jump reference), reported error is occurred.
If you rename `package1.lib` to `package1_lib`, no problems.

I checked following environment.
```
PyCharm: 2024.3.2 Build #PY-243.23654.177
Bazel plugin: 2025.01.21.0.2-api-version-243
```

**Comment by nikhil-marathe-skydio** [comment]
I am hitting the same issue.
Unfortunately, I can't share the code.

```
2025-02-11 13:11:40,038 [ 431946] SEVERE - #c.i.c.d.i.PassExecutorService - CLion 2024.3.2  Build #CL-243.23654.114
2025-02-11 13:11:40,038 [ 431946] SEVERE - #c.i.c.d.i.PassExecutorService - JDK: 21.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2025-02-11 13:11:40,038 [ 431946] SEVERE - #c.i.c.d.i.PassExecutorService - OS: Linux
2025-02-11 13:11:40,039 [ 431947] SEVERE - #c.i.c.d.i.PassExecutorService - Plugin to blame: Bazel for CLion version: 2025.01.21.0.2-api-version-243
2025-02-11 13:11:40,317 [ 432225]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.jetbrains.python.psi.impl.PythonLanguageLevelPusher$MyDumbModeTask@6e2b37c3
```

**Comment by nikhil-marathe-skydio** [comment]
In the next release of the plugin, is it possible for the exception to at least report the full path/import name of the thing that is failing so it is possible to understand which package/file is causing the issue?

**Comment by nikhil-marathe-skydio** [comment]
My error message is slightly different

```
2025-02-13 10:20:54,991 [ 388906] SEVERE - #c.i.c.d.i.PassExecutorService - Components of QualifiedName cannot contain dots inside them, but got: ..
java.lang.IllegalArgumentException: Components of QualifiedName cannot contain dots inside them, but got: ..
	at com.intellij.psi.util.QualifiedName.assertNoDots(QualifiedName.java:195)
	at com.intellij.psi.util.QualifiedName.fromComponents(QualifiedName.java:35)
	at com.google.idea.blaze.python.resolve.provider.AbstractPyImportResolverStrategy.assembleImportRoots(AbstractPyImportResolverStrategy.java:407)
	at com.google.idea.blaze.python.resolve.provider.AbstractPyImportResolverStrategy.buildSourcesIndex(AbstractPyImportResolverStrategy.java:150)
	at com.google.idea.blaze.base.sync.SyncCache.get(SyncCache.java:61)
	at com.google.idea.blaze.python.resolve.provider.AbstractPyImportResolverStrategy.getSourcesIndex(AbstractPyImportResolverStrategy.java:140)
	at com.google.idea.blaze.python.resolve.provider.AbstractPyImportResolverStrategy.resolveFromSyncData(AbstractPyImportResolverStrategy.java:102)
	at com.google.idea.blaze.python.resolve.PyDynamicImportResolverInitializer.lambda$registerImportResolvers$0(PyDynamicImportResolverInitializer.java:51)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil.foreignResults$lambda$10(PyResolveImportUtil.kt:206)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:813)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil.foreignResults(PyResolveImportUtil.kt:210)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil.resolveQualifiedName(PyResolveImportUtil.kt:79)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.lambda$calculateResolveModule$1(ResolveImportUtil.java:185)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:29)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.calculateResolveModule(ResolveImportUtil.java:177)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:629)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:607)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.resolveModule(ResolveImportUtil.java:166)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.resolveFromImportStatementSource(ResolveImportUtil.java:147)
	at com.jetbrains.python.psi.impl.PyFromImportStatementImpl.resolveImportSourceCandidates(PyFromImportStatementImpl.java:210)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.resolveNameInFromImport(ResolveImportUtil.java:125)
	at com.jetbrains.python.psi.resolve.ResolveImportUtil.multiResolveImportElement(ResolveImportUtil.java:104)
	at com.jetbrains.python.psi.impl.PyImportElementImpl.multiResolve(PyImportElementImpl.java:215)
	at com.jetbrains.python.psi.impl.PyImportElementImpl.getElementsNamed(PyImportElementImpl.java:196)
	at com.jetbrains.python.psi.impl.PyImportElementImpl.multiResolveName(PyImportElementImpl.java:167)
	at com.jetbrains.python.psi.resolve.PyResolveProcessor.resolveInImportedNameDefiner(PyResolveProcessor.java:96)
	at com.jetbrains.python.psi.resolve.PyResolveProcessor.execute(PyResolveProcessor.java:48)
	at com.jetbrains.python.psi.resolve.PyResolveUtil.scopeCrawlUp(PyResolveUtil.java:128)
	at com.jetbrains.python.psi.resolve.PyResolveUtil.scopeCrawlUp(PyResolveUtil.java:97)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl.resolveInner(PyReferenceImpl.java:227)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl.multiResolveInner(PyReferenceImpl.java:107)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl$CachingResolver.resolve(PyReferenceImpl.java:775)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl$CachingResolver.resolve(PyReferenceImpl.java:770)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:167)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:242)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:29)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:220)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:148)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl.multiResolve(PyReferenceImpl.java:94)
	at com.jetbrains.python.psi.PyUtil.multiResolveTopPriority(PyUtil.java:470)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.tryResolvingWithAliases(PyTypingTypeProvider.java:2049)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.tryResolving(PyTypingTypeProvider.java:2038)
	at com.jetbrains.python.codeInsight.typing.PyTypingTypeProvider.resolveToQualifiedNames(PyTypingTypeProvider.java:2140)
	at com.jetbrains.python.codeInsight.typing.PyTypedDictTypeProvider$Companion.isTypedDict(PyTypedDictTypeProvider.kt:49)
	at com.jetbrains.python.codeInsight.typing.PyTypedDictTypeProvider$Companion.getTypedDictTypeForCallee(PyTypedDictTypeProvider.kt:118)
	at com.jetbrains.python.codeInsight.typing.PyTypedDictTypeProvider$Companion.access$getTypedDictTypeForCallee(PyTypedDictTypeProvider.kt:40)
	at com.jetbrains.python.codeInsight.typing.PyTypedDictTypeProvider.getReferenceExpressionType(PyTypedDictTypeProvider.kt:29)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getTypeFromProviders(PyReferenceExpressionImpl.java:336)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getType(PyReferenceExpressionImpl.java:189)
	at com.jetbrains.python.psi.types.TypeEvalContext.lambda$getType$0(TypeEvalContext.java:181)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:29)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:170)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.getExplicitResolveResults(PyCallExpressionHelper.java:190)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.lambda$multiResolveCallee$1(PyCallExpressionHelper.java:162)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:629)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:607)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.multiResolveCallee(PyCallExpressionHelper.java:158)
	at com.jetbrains.python.psi.impl.PyCallExpressionImpl.multiResolveCallee(PyCallExpressionImpl.java:32)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.multiResolveCalleeFunction(PyCallExpressionHelper.java:834)
	at com.jetbrains.python.psi.impl.PyCallExpressionHelper.mapArguments(PyCallExpressionHelper.java:827)
	at com.jetbrains.python.psi.impl.PyCallExpressionImpl.multiMapArguments(PyCallExpressionImpl.java:38)
	at com.jetbrains.python.inlayHints.PythonInlayParameterHintsProvider.getInlayInfoForArgumentList(PythonInlayParameterHintsProvider.kt:44)
	at com.jetbrains.python.inlayHints.PythonInlayParameterHintsProvider.getParameterHints(PythonInlayParameterHintsProvider.kt:145)
	at com.intellij.codeInsight.hints.ParameterHintsPass.process(ParameterHintsPass.java:113)
	at com.intellij.codeInsight.hints.ParameterHintsPass.lambda$doCollectInformation$2(ParameterHintsPass.java:105)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:105)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:427)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:30)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:972)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:413)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:412)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:388)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:822)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:388)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:544)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:176)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:386)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:266)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by rajukrishnamurthy** [comment]
Anyone figure out the root cause of this problems, I can't seem to find any directories (other than non-source directories like `.git` etc.) but we do have some relative imports `from ..lib import foo` could that be the cause?

**Comment by andersdyhrnorlov** [comment]
I have exact same issue with:

java.lang.IllegalArgumentException: Components of QualifiedName cannot contain dots inside them, but got: python3.11

**Comment by odisseus** [comment]
If I understand correctly, the [example project](https://github.com/leaqigaie/bazel-intellij-issue6832) violates Python rules about module naming. There is likely an issue of similar narure with the OP's environment.

However, I agree that the plugin shouldn't fail even when the environment is not entirely correct.
