### ISSUE TITLE
Sync fails without --enable_workspace

### ISSUE THREAD

**Issue by mai93** [bazelbuild/intellij#6984]
### Description of the bug:

For a bzlmod project that uses Bazel 8 where WORKSPACE approach is disabled by default, the build invocation of the plugin sync operation can fail if `--enable_workspace` is not specified. 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

You can import the python example project from this branch https://github.com/bazelbuild/intellij/tree/bazel-8/examples/python (modified to use Bazel 8 rc). The initial sync will fail with:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Evaluation of SkyKey failed and no dependencies were requested: KeyForBuild{label=@@intellij_aspect//:intellij_info_bundled.bzl, isBuildPrelude=false} IncrementalInMemoryNodeEntry{key=KeyForBuild{label=@@intellij_aspect//:intellij_info_bundled.bzl, isBuildPrelude=false}, value=null, dirtyBuildingState=InitialBuildingState{state=REBUILDING, signaledDeps=6, externalDeps=0, dirtyDirectDepIndex=0}, version=com.google.devtools.build.skyframe.Version$MinimalVersion@4e5f9c78, directDeps=GroupedDeps{size=6, elements=[PRECOMPUTED:autoload_symbols, Starlark @_builtins, CONTAINING_PACKAGE_LOOKUP:@@intellij_aspect//, FILE:[/usr/local/google/home/messa/.cache/bazel/_bazel_messa/33693a4fea7b855dcfbe5494050fe249/external/intellij_aspect]/[intellij_info_bundled.bzl], PRECOMPUTED:starlark_semantics, Key{repoName=@@intellij_aspect, rootModuleShouldSeeWorkspaceRepos=true}]}, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=[BuildTopLevelAspectsDetailsKey{topLevelAspectsClasses=[@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect], topLevelAspectsParameters={}}]}}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:838)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:697)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

The error is gone when `--enable_workspace` is added. Do we have plans to address this by passing `--enable_workapce` by default for now or some other way?

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/22691#issuecomment-2371654429

**Comment by mai93** [comment]
@tpasternak what are the plans for this one?
