### ISSUE TITLE
Exception in the new QuerySyncNotificationProvider

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/intellij#7009]
### Description of the bug:

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.iterator()" because "packagePath" is null
	at com.google.idea.blaze.common.TargetTree.get(TargetTree.java:54)
	at com.google.idea.blaze.qsync.project.BuildGraphData.getProjectTargets(BuildGraphData.java:412)
	at com.google.idea.blaze.base.qsync.QuerySyncProject.lambda$getProjectTargets$0(QuerySyncProject.java:307)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.google.idea.blaze.base.qsync.QuerySyncProject.getProjectTargets(QuerySyncProject.java:307)
	at com.google.idea.blaze.base.qsync.QuerySyncManager.getTargetsToBuild(QuerySyncManager.java:413)
	at com.google.idea.blaze.base.qsync.QuerySyncManager.getTargetsToBuild(QuerySyncManager.java:405)
	at com.google.idea.blaze.base.qsync.action.BuildDependenciesHelper.getTargetsToEnableAnalysisFor(BuildDependenciesHelper.java:80)
	at com.google.idea.blaze.base.qsync.QuerySyncNotificationProvider.lambda$collectNotificationData$0(QuerySyncNotificationProvider.java:50)
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1$2.invokeSuspend$lambda$0(EditorNotificationsImpl.kt:258)
	at com.intellij.openapi.application.CoroutinesKt.writeIntentReadAction$lambda$1$lambda$0(coroutines.kt:329)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.CoroutinesKt.writeIntentReadAction$lambda$1(coroutines.kt:329)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:341)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:233)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:232)
	at com.intellij.openapi.application.CoroutinesKt.writeIntentReadAction(coroutines.kt:328)
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1$2.invokeSuspend(EditorNotificationsImpl.kt:253)
	... 217 more% 
```

**Comment by ujohnny** [comment]
probably this is no longer revelant, consider closing
