### ISSUE TITLE
NPE in BlazeXmlSchema#getErrorContent

### ISSUE THREAD

**Issue by artspb** [bazelbuild/intellij#732]
This exception is reported by one of the IntelliJ IDEA users (build 183.6156.11).

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy24.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$4.run(ProcessHandler.java:180)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:256)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:161)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:157)
	at com.intellij.execution.process.KillableProcessHandler.notifyProcessTerminated(KillableProcessHandler.java:138)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:112)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:102)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:87)
	at com.intellij.execution.process.ProcessWaitFor$1$1.run(ProcessWaitFor.java:65)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlSchema.getErrorContent(BlazeXmlSchema.java:164)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.getTestFailedEvent(BlazeXmlToTestEventsConverter.java:384)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processTestCase(BlazeXmlToTestEventsConverter.java:366)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processTestSuite(BlazeXmlToTestEventsConverter.java:264)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processTestSuite(BlazeXmlToTestEventsConverter.java:258)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processParsedTestResults(BlazeXmlToTestEventsConverter.java:179)
	at java.util.ArrayList.forEach(ArrayList.java:1251)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.processAllTestResults(BlazeXmlToTestEventsConverter.java:114)
	at com.google.idea.blaze.base.run.smrunner.BlazeXmlToTestEventsConverter.flushBufferOnProcessTermination(BlazeXmlToTestEventsConverter.java:97)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.processTerminated(SMTestRunnerConnectionUtil.java:201)
	... 22 more
```

**Comment by jin** [comment]
Do you have a repro?

**Comment by artspb** [comment]
As I said, the issue was reported by a user. The only thing I have is this stack trace.

**Comment by hmemcpy** [comment]
Just hit this too - it happens if the test runner returned an error, but there was no actual error content to be parsed, e.g.:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="com.MyTest" tests="1" failures="0" errors="1">
    <testcase name="test1" status="run" duration="55" time="55"><error message="exited with error code 1"></error></testcase>
   <system-out>
      ...
   </system-out>
  </testcases>
</testsuites>

This causes an NPE in `getErrorContent`, which tries to read `err.content` list, which happens to be `null` here. The only thing that's available on the `err` object is the `message` ("exited with error code 1").

I made a quick fix, checking `if (err.content == null) return err.message`. If you like, @jin, I can send a PR.
