### ISSUE TITLE
Error in syncing project in Windows

### ISSUE THREAD

**Issue by abhijith-gururaj** [bazelbuild/intellij#733]
I am trying to setup the bazel java-tutorial example as an intellij project. After setting up the required config, I am facing an issue while doing a bazel-sync on the project.
Am I missing something?
Please check the log below:

```
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: C:\bazel\bazel.exe info --tool_tag=ijwb:IDEA:community --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --

Computing VCS working set...
Sync targets from project view:
  //...

Building IDE info files...
Command: C:\bazel\bazel.exe build --tool_tag=ijwb:IDEA:community --keep_going --build_event_binary_file=C:\Users\abgurura\AppData\Local\Temp\intellij-bep-35dbe6e7-ae97-4b0f-8484-00a5495355b7 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=C:\Users\abgurura\.IdeaIC2018.2\config\plugins\ijwb\aspect --output_groups=intellij-info-generic,intellij-info-java,intellij-info-py -- //...

INFO: Loading complete.  Analyzing...
ERROR: C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/local_config_cc/BUILD:31:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on cc_toolchain_suite rule @local_config_cc//:toolchain: 
Traceback (most recent call last):
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/local_config_cc/BUILD", line 31
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/intellij_aspect/intellij_info_bundled.bzl", line 38, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/intellij_aspect/intellij_info_impl.bzl", line 788, in intellij_info_aspect_impl
		collect_c_toolchain_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/intellij_aspect/intellij_info_impl.bzl", line 364, in collect_c_toolchain_info
		cc_common.create_compile_variables(feature_configuration = feature_..., <2 more arguments>)
Passing depset into user flags is deprecated (see --incompatible_disable_depset_in_cc_user_flags), use list instead.
INFO: Found 3 targets...
INFO: Building...
Aspect @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect of //:greeter up-to-date:
  C:/users/abgurura/_bazel_abgurura/rjn7xqtq/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/external/bazel_tools/tools/jdk/remote_toolchain-1176928112.intellij-info.txt
  C:/users/abgurura/_bazel_abgurura/rjn7xqtq/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/external/bazel_tools/tools/jdk/current_java_toolchain--1286701614.intellij-info.txt
  C:/users/abgurura/_bazel_abgurura/rjn7xqtq/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/greeter.java-manifest
  C:/users/abgurura/_bazel_abgurura/rjn7xqtq/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/greeter-283721078.intellij-info.txt
ERROR: command succeeded, but not all targets were analyzed.
INFO: Elapsed time: 0.573s, Critical Path: 0.01s
INFO: 0 processes.
ide-info result: build_error
Total rules: 3, new/changed: 0, removed: 0
Reading IDE info result...
Loaded 0 aspect files, total size 0kB
ide-query result: build_error
Target map size: 2
Building IDE resolve files...
Command: C:\bazel\bazel.exe build --tool_tag=ijwb:IDEA:community --keep_going --build_event_binary_file=C:\Users\abgurura\AppData\Local\Temp\intellij-bep-a984a322-9926-4d4b-b357-306e81d422c3 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=C:\Users\abgurura\.IdeaIC2018.2\config\plugins\ijwb\aspect --output_groups=intellij-resolve-java,intellij-resolve-py -- //...

INFO: Loading complete.  Analyzing...
ERROR: C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/local_config_cc/BUILD:31:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on cc_toolchain_suite rule @local_config_cc//:toolchain: 
Traceback (most recent call last):
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/local_config_cc/BUILD", line 31
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/intellij_aspect/intellij_info_bundled.bzl", line 38, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/intellij_aspect/intellij_info_impl.bzl", line 788, in intellij_info_aspect_impl
		collect_c_toolchain_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File "C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/intellij_aspect/intellij_info_impl.bzl", line 364, in collect_c_toolchain_info
		cc_common.create_compile_variables(feature_configuration = feature_..., <2 more arguments>)
Passing depset into user flags is deprecated (see --incompatible_disable_depset_in_cc_user_flags), use list instead.
INFO: Found 3 targets...
[0 / 1] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/users/abgurura/_bazel_abgurura/rjn7xqtq/external/bazel_tools/tools/jdk/BUILD:299:1: Couldn't build file external/bazel_tools/tools/jdk/platformclasspath.jar: SkylarkAction external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1).
Exception in thread "main" java.lang.IllegalArgumentException: external\local_jdk
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.main.Option.process(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(Unknown Source)
	at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Aspect @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect of //:greeter failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.748s, Critical Path: 0.35s
INFO: 0 processes.
Prefetching genfiles...
Reading jdeps files...
Loaded 0 jdeps files, total size 0kB
Reading package manifests...
Java content entry count: 2
Updating Jar Cache...
Prefetching files...
Computing directory structure...
Committing project structure...
Workspace has 0 libraries
Workspace has 2 modules
Sync was successful, but there were BUILD file errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Blaze > Sync > Expand Sync to Working Set' and try again.
Updating in-memory state...

==== TIMING REPORT ====

Sync: 1.9s
    BazelInfo: 349ms
    WorkingSet: 0ms
    IdeQuery: 672ms
        ExecuteBlazeCommand: 656ms
        IdeInfoBuildArtifacts: 0ms
        FetchAspectOutput: 0ms
        UpdateTargetMap: 0ms
    BazelBuild: 859ms
        ExecuteBlazeCommand: 859ms
        GenfilesPrefetchBuildArtifacts: 0ms
        PrefetchGenfiles: 0ms
    UpdateSyncState: 0ms
        LoadJdepsFiles: 0ms
            FetchJdeps: 0ms
        JavaWorkspaceImporter: 0ms
            ReadPackageManifests: 0ms
                FetchPackageManifests: 0ms
            CalculateSourceDirectories: 0ms
    Jar Cache: 0ms
    PrefetchFiles: 0ms
    RefreshVirtualFileSystem: 16ms
    DirectoryStructure: 0ms
    UpdateProjectStructure: 47ms
    UpdateInMemoryState: 0ms

Timing summary:

BlazeInvocation: 1.9s
Other: 63ms
```

**Comment by chaoren** [comment]
We don't support windows at the moment.

**Comment by abhijith-gururaj** [comment]
Thanks for the reply. Is there a plan to support windows anytime in the near future?

**Comment by jin** [comment]
This looks like an incompatible change issue, not a Windows issue. What are the versions of Bazel and plugin here?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
