### ISSUE TITLE
CLion 2019.1 Sync fails on error while reading clang-tidy actions

### ISSUE THREAD

**Issue by aariyaratne** [bazelbuild/intellij#824]
Hi,

I am trying to use CLion Bazel plugin to sync our repo, and I am getting error thrown by the plugin from what I undertand is trying to read our clang-tidy rules.

```
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect BuildConfigurationValue.Key[587852f4dfb047b5718970209d863cfe] //:clang_tidy_action BuildConfigurationValue.Key[587852f4dfb047b5718970209d863cfe] false {}' (requested by nodes 'com.google.devtools.build.lib.skyframe.AspectValue$SkylarkAspectLoadingKey@98fd8b3c')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:530)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on extra_action attribute tools produces more than one prerequisite
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisiteConfiguredTargetAndData(RuleContext.java:912)
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisite(RuleContext.java:898)
	at com.google.devtools.build.lib.analysis.RuleContext.getExecutablePrerequisite(RuleContext.java:1104)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkAttributesCollection$Builder.addAttribute(SkylarkAttributesCollection.java:173)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleContext.<init>(SkylarkRuleContext.java:250)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:69)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:515)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:628)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:470)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:453)
	... 7 more

INFO: (05-20 14:46:25.676) Elapsed time: 13.415s
INFO: (05-20 14:46:25.676) 0 processes.
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect BuildConfigurationValue.Key[587852f4dfb047b5718970209d863cfe] //:clang_tidy_action BuildConfigurationValue.Key[587852f4dfb047b5718970209d863cfe] false {}' (requested by nodes 'com.google.devtools.build.lib.skyframe.AspectValue$SkylarkAspectLoadingKey@98fd8b3c')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:530)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on extra_action attribute tools produces more than one prerequisite
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisiteConfiguredTargetAndData(RuleContext.java:912)
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisite(RuleContext.java:898)
	at com.google.devtools.build.lib.analysis.RuleContext.getExecutablePrerequisite(RuleContext.java:1104)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkAttributesCollection$Builder.addAttribute(SkylarkAttributesCollection.java:173)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleContext.<init>(SkylarkRuleContext.java:250)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:69)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:515)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:628)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:470)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:453)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect BuildConfigurationValue.Key[587852f4dfb047b5718970209d863cfe] //:clang_tidy_action BuildConfigurationValue.Key[587852f4dfb047b5718970209d863cfe] false {}' (requested by nodes 'com.google.devtools.build.lib.skyframe.AspectValue$SkylarkAspectLoadingKey@98fd8b3c')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:530)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on extra_action attribute tools produces more than one prerequisite
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisiteConfiguredTargetAndData(RuleContext.java:912)
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisite(RuleContext.java:898)
	at com.google.devtools.build.lib.analysis.RuleContext.getExecutablePrerequisite(RuleContext.java:1104)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkAttributesCollection$Builder.addAttribute(SkylarkAttributesCollection.java:173)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleContext.<init>(SkylarkRuleContext.java:250)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:69)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:515)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:628)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:470)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:453)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect BuildConfigurationValue.Key[587852f4dfb047b5718970209d863cfe] //:clang_tidy_action BuildConfigurationValue.Key[587852f4dfb047b5718970209d863cfe] false {}' (requested by nodes 'com.google.devtools.build.lib.skyframe.AspectValue$SkylarkAspectLoadingKey@98fd8b3c')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:530)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on extra_action attribute tools produces more than one prerequisite
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisiteConfiguredTargetAndData(RuleContext.java:912)
	at com.google.devtools.build.lib.analysis.RuleContext.getPrerequisite(RuleContext.java:898)
	at com.google.devtools.build.lib.analysis.RuleContext.getExecutablePrerequisite(RuleContext.java:1104)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkAttributesCollection$Builder.addAttribute(SkylarkAttributesCollection.java:173)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleContext.<init>(SkylarkRuleContext.java:250)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:69)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:515)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:628)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:470)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:453)
	... 7 more

```

Our clang-tidy tooling is similar to https://pixorblog.wordpress.com/2017/06/26/bazel-and-compile-commands/

I have to fully comment out clang-tidy action_listener and extra_action to get this project to sync. Bazel have no problem building or running clang-tidy when invoked externally.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
