### ISSUE TITLE
IJWB on Windows hangs after each "bazel" command execution

### ISSUE THREAD

**Issue by philwo** [bazelbuild/intellij#84]
Hi,

I'm working on Bazel's Windows port and I'd love to get IJWB working. Actually: It mostly does! There's just one little thing left to fix, which I'm happy to dig in myself, but wanted to check if you have an idea out of your head:

When IJWB runs a Bazel command, it seems to forever wait for it to finish, even though it already did (as can be seen in "Process Explorer" and also by going into the directory and running "bazel info" myself, which would block if the Bazel server were still busy).

**Update: Interestingly, killing the entire Bazel server process (java.exe) let's the plug-in continue! If you kill it everytime the plug-in starts hanging, it will eventually successfully complete. :)**

How to reproduce:
- Install [Bazel 0.5rc2](https://storage.googleapis.com/bazel/0.5/rc2/bazel-msvc-0.5rc2-without-jdk-windows-msvc-x86_64.exe) on Windows (sorry... it's [a rather complex process](https://bazel.build/versions/master/docs/windows.html) at the moment).
- Install IntelliJ 2017.1.2 and the IJWB plug-in.
- Install [Git for Windows](https://git-scm.com/download/win) and check out Bazel's code from GitHub.
- Import Bazel's project into IJWB.

The log of the IJWB plug-in is:
```
Syncing project...
Updating VCS...
Running Bazel info...
Command: C:\Users\philwo\bin\bazel-msvc-0.5rc2-windows-msvc-x86_64.exe info --tool_tag=ijwb:IDEA:ultimate --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --


.
____Loading package: @bazel_tools//tools/jdk
____Loading package: @local_config_xcode//
____Loading package: @local_config_cc//
____Loading package: @local_jdk//
```

Here's a stack dump of IntelliJ - one can see that the IJWB plug-in still seems to be busy with `FileInputStream.readBytes` even though the Bazel client process it started to run a command has already exited:
```
2017-05-05 17:24:35
Full thread dump OpenJDK 64-Bit Server VM (25.112-b16 mixed mode):

"ApplicationImpl pooled thread 8" #74 prio=4 os_prio=-1 tid=0x0000000022131800 nid=0x23f4 waiting on condition [0x0000000028b4f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e17eb428> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"ApplicationImpl pooled thread 7" #73 prio=4 os_prio=-1 tid=0x0000000022138000 nid=0x1f34 waiting on condition [0x0000000028a4f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e17eb428> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Thread-11" #58 prio=5 os_prio=0 tid=0x0000000022135000 nid=0x1e0c runnable [0x0000000027e4f000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:233)
	at com.google.idea.blaze.base.async.process.ProcessUtil$1.run(ProcessUtil.java:40)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Thread-10" #57 prio=5 os_prio=0 tid=0x0000000022130000 nid=0x620 runnable [0x0000000027d4f000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000000e4de3888> (a java.io.BufferedInputStream)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.google.idea.blaze.base.async.process.ProcessUtil$1.run(ProcessUtil.java:40)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"pool-3-thread-3" #52 prio=5 os_prio=0 tid=0x0000000022134800 nid=0x1c80 waiting on condition [0x0000000027a4f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e3ca8b80> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"pool-3-thread-2" #51 prio=5 os_prio=0 tid=0x0000000022133800 nid=0x199c in Object.wait() [0x000000002794e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1249)
	- locked <0x00000000e1de5f48> (a java.lang.Thread)
	at java.lang.Thread.join(Thread.java:1323)
	at com.google.idea.blaze.base.async.process.ExternalTask.invokeCommand(ExternalTask.java:233)
	at com.google.idea.blaze.base.async.process.ExternalTask.lambda$run$0(ExternalTask.java:180)
	at com.google.idea.blaze.base.async.process.ExternalTask$$Lambda$736/1826623662.execute(Unknown Source)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.async.process.ExternalTask.run(ExternalTask.java:173)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.runBlazeInfo(BlazeInfoRunnerImpl.java:103)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl.lambda$runBlazeInfo$2(BlazeInfoRunnerImpl.java:75)
	at com.google.idea.blaze.base.command.info.BlazeInfoRunnerImpl$$Lambda$750/1915198988.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000e171d128> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-3-thread-1" #46 prio=5 os_prio=0 tid=0x000000002212f000 nid=0x150c waiting on condition [0x000000002754e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e1f89a20> (a com.google.common.util.concurrent.TrustedListenableFutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:445)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.lambda$run$0(FutureUtil.java:93)
	at com.google.idea.blaze.base.async.FutureUtil$Builder$$Lambda$752/1084425117.execute(Unknown Source)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.base.async.FutureUtil$Builder.run(FutureUtil.java:83)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:260)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:191)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:158)
	at com.google.idea.blaze.base.sync.BlazeSyncTask$$Lambda$696/495507846.execute(Unknown Source)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:139)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$97/416161993.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:108)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:105)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000e30a9708> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"TimerQueue" #32 daemon prio=5 os_prio=0 tid=0x000000001b9d2000 nid=0x1888 waiting on condition [0x000000001fbff000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e413cb98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.DelayQueue.take(DelayQueue.java:223)
	at javax.swing.TimerQueue.run(TimerQueue.java:174)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000e48efe38> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"Netty Builtin Server 2" #31 prio=4 os_prio=-1 tid=0x000000001b9d1000 nid=0x1ea4 runnable [0x000000001f8ff000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000e17f0d00> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000000e17f1c38> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000e109f808> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"BaseDataReader: error stream of fsnotifier64.exe" #27 prio=4 os_prio=-1 tid=0x000000001b9cf000 nid=0x1368 runnable [0x000000001df2e000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000000e348ce28> (a com.intellij.util.io.BaseInputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:137)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:84)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:162)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000e3bc5f28> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"BaseDataReader: output stream of fsnotifier64.exe" #26 prio=4 os_prio=-1 tid=0x000000001b9ce000 nid=0x1e14 runnable [0x000000001de2f000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000000e3c05cb8> (a java.io.BufferedInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000000e3b1ca10> (a com.intellij.util.io.BaseInputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:137)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:84)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:162)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000e38dddd0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"ProcessWaitFor: fsnotifier64.exe" #25 prio=4 os_prio=-1 tid=0x000000001b9cc000 nid=0x7dc runnable [0x000000001dd2f000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ProcessImpl.waitForInterruptibly(Native Method)
	at java.lang.ProcessImpl.waitFor(ProcessImpl.java:449)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000e3c28200> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"AWT-EventQueue-0 2017.1.2#IU-171.4249.39 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_112-release-736-b16" #24 prio=6 os_prio=0 tid=0x000000001974f800 nid=0x278 waiting on condition [0x000000001cb5f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e1419cc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.awt.EventQueue.getNextEvent(EventQueue.java:560)
	at com.intellij.ide.IdeEventQueue.getNextEvent(IdeEventQueue.java:401)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:170)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

   Locked ownable synchronizers:
	- None

"AWT-Shutdown" #23 prio=5 os_prio=0 tid=0x000000001b567800 nid=0x1f70 in Object.wait() [0x000000001c85f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
	- locked <0x00000000e2cd3438> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Periodic tasks thread" #22 prio=5 os_prio=0 tid=0x000000001b566800 nid=0x1f5c runnable [0x000000001c75f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e2a057c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.DelayQueue.take(DelayQueue.java:223)
	at com.intellij.util.concurrency.AppDelayQueue$1.run(AppDelayQueue.java:42)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Netty Builtin Server 1" #17 prio=5 os_prio=0 tid=0x0000000018eb1800 nid=0x860 runnable [0x000000001abae000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000e1e9ad08> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000000e1e9a570> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000e2375f00> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"AWT-Windows" #14 daemon prio=6 os_prio=0 tid=0x0000000018981800 nid=0x1ecc runnable [0x000000001a26f000]
   java.lang.Thread.State: RUNNABLE
	at sun.awt.windows.WToolkit.eventLoop(Native Method)
	at sun.awt.windows.WToolkit.run(WToolkit.java:306)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Java2D Disposer" #12 daemon prio=10 os_prio=2 tid=0x0000000018980000 nid=0x1ef8 in Object.wait() [0x000000001a06f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000000e2cd3450> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"Service Thread" #11 daemon prio=9 os_prio=0 tid=0x0000000016fee000 nid=0x162c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread3" #10 daemon prio=9 os_prio=2 tid=0x0000000016f95800 nid=0x18d0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread2" #9 daemon prio=9 os_prio=2 tid=0x0000000016f95000 nid=0x1cd8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread1" #8 daemon prio=9 os_prio=2 tid=0x0000000016f92000 nid=0x1cd4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #7 daemon prio=9 os_prio=2 tid=0x0000000016f8f000 nid=0x1f4c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Attach Listener" #6 daemon prio=5 os_prio=2 tid=0x0000000016f8e000 nid=0x1ce0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #5 daemon prio=9 os_prio=2 tid=0x0000000016f8d000 nid=0x1508 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Surrogate Locker Thread (Concurrent GC)" #4 daemon prio=9 os_prio=0 tid=0x0000000016f8c800 nid=0x1414 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x0000000016f74000 nid=0x1f3c in Object.wait() [0x00000000175af000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000000e0da9170> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x0000000016f4b800 nid=0x1cec in Object.wait() [0x00000000174af000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000000e0d9dd50> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
	- None

"main" #1 prio=5 os_prio=0 tid=0x00000000021ee000 nid=0x1f2c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=2 tid=0x0000000016f3d000 nid=0x2e4 runnable 

"Gang worker#0 (Parallel GC Threads)" os_prio=2 tid=0x0000000002222800 nid=0x134c runnable 

"Gang worker#1 (Parallel GC Threads)" os_prio=2 tid=0x0000000002224000 nid=0x19dc runnable 

"Gang worker#2 (Parallel GC Threads)" os_prio=2 tid=0x0000000002225800 nid=0x1abc runnable 

"Gang worker#3 (Parallel GC Threads)" os_prio=2 tid=0x0000000002228000 nid=0x338 runnable 

"Gang worker#4 (Parallel GC Threads)" os_prio=2 tid=0x000000000222a800 nid=0x1784 runnable 

"Gang worker#5 (Parallel GC Threads)" os_prio=2 tid=0x000000000222d800 nid=0x18c0 runnable 

"Gang worker#6 (Parallel GC Threads)" os_prio=2 tid=0x0000000002233800 nid=0x1f8c runnable 

"Gang worker#7 (Parallel GC Threads)" os_prio=2 tid=0x0000000002234000 nid=0x494 runnable 

"Gang worker#8 (Parallel GC Threads)" os_prio=2 tid=0x0000000002234800 nid=0x1fd0 runnable 

"Gang worker#9 (Parallel GC Threads)" os_prio=2 tid=0x0000000002235000 nid=0x1408 runnable 

"Concurrent Mark-Sweep GC Thread" os_prio=2 tid=0x00000000022c0800 nid=0x189c runnable 

"Gang worker#0 (Parallel CMS Threads)" os_prio=2 tid=0x00000000022b5800 nid=0x1f60 runnable 

"Gang worker#1 (Parallel CMS Threads)" os_prio=2 tid=0x00000000022b8000 nid=0x145c runnable 

"Gang worker#2 (Parallel CMS Threads)" os_prio=2 tid=0x00000000022be000 nid=0x1f98 runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x0000000017022000 nid=0x974 waiting on condition 

JNI global references: 4533
```

**Comment by brendandouglas** [comment]
The 'blaze info' process' stdout stream never appears to close (ProcessUtil#forwardAsync is waiting for the InputStream#read to return -1).

I don't have any immediate insights, sorry. Unfortunately, we don't really have the bandwidth to work on Windows support at the moment. I'd be shocked if this was the only problem, and expect that fixing this will expose dozens of other Windows-specific issues.

We have a Q2 OKR for supporting macs, but I don't expect we'll get around to windows support until Q4 or later.

**Comment by philwo** [comment]
Thanks a lot, this is already very helpful!

> We have a Q2 OKR for supporting macs

I... I've been using the plug-in on my Mac for months already and it works beautifully with no problem at all. Let's hope the code never notices that it isn't supposed to work yet ;)

**Comment by brendandouglas** [comment]
Haha, we do have a few Bazel mac users already. It basically works, though there are a couple of Mac-specific issues. Mostly, 'mac support' consists of adding integration tests.

> Can you assign this issue to me

Absolutely -- thank you!

**Comment by philwo** [comment]
First success: IntelliJ 2017.1.3, IJWB 2017.05.08.1 and Bazel 0.5.0 (release) do a "sync" fine for me if I enable batch mode by putting "startup --batch" into my home directory ("C:\Users\philwo" on Windows).

Opening Bazel's own project file with IJWB works, Sync succeeds and Ctrl-F9 from the IDE works fine to build the project.

However, when opening one of our own classes (e.g. WorkerSpawnStrategy.java), IntelliJ cannot resolve some "import" statements and Java symbols that come from third_party libs (e.g. Guava):

```
import com.google.common.collect.Multimap;
           ^^^^^^
Cannot resolve symbol 'common'.
```
 I tried to reproduce this in a small example project, but there it works fine.

**Comment by brendandouglas** [comment]
My first guess would be that external libraries aren't being picked up due to incorrect file separators in the file paths.

Second possibility is that it's a windows-specific problem with external bazel workspaces.

Do you have any external libraries added to your project after sync? (they should show up in View > Tool Windows > Project)

**Comment by philwo** [comment]
macOS (works):
[...]

Windows (broken):
![image](https://cloud.githubusercontent.com/assets/504652/26583224/a83fc4f4-4544-11e7-90b9-c5bb876be630.png)

**Comment by philwo** [comment]
> Do you have any external libraries added to your project after sync? (they should show up in View > Tool Windows > Project)

I added two screenshots - all the third party libraries are missing on Windows, but they're present on macOS.

**Comment by philwo** [comment]
I can no longer reproduce this with recent Bazel and plug-in versions :)
