### ISSUE TITLE
Clion 2017.1.1 NoClassFoundException

### ISSUE THREAD

**Issue by GregBowyer** [bazelbuild/intellij#86]
```
Could not build C compiler settings map: java.lang.NoClassDefFoundError: com/jetbrains/cidr/lang/toolchains/CidrSwitchBuilder$Format
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/jetbrains/cidr/lang/toolchains/CidrSwitchBuilder$Format
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.buildCompilerSettingsMap(BlazeConfigurationResolver.java:329)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.update(BlazeConfigurationResolver.java:100)
	at com.google.idea.blaze.cpp.BlazeCWorkspace.update(BlazeCWorkspace.java:51)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.lambda$updateInMemoryState$0(BlazeCSyncPlugin.java:71)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.updateInMemoryState(BlazeCSyncPlugin.java:63)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$updateInMemoryState$15(BlazeSyncTask.java:826)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$updateInMemoryState$16(BlazeSyncTask.java:819)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.updateInMemoryState(BlazeSyncTask.java:813)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:199)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:158)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:139)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:108)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:105)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/jetbrains/cidr/lang/toolchains/CidrSwitchBuilder$Format
	at com.google.idea.sdkcompat.cidr.CidrSwitchBuilderAdapter.addAllRaw(CidrSwitchBuilderAdapter.java:21)
	at com.google.idea.blaze.cpp.BlazeCompilerSettings.getCompilerSwitches(BlazeCompilerSettings.java:97)
	at com.google.idea.blaze.cpp.BlazeCompilerSettings.<init>(BlazeCompilerSettings.java:51)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.createBlazeCompilerSettings(BlazeConfigurationResolver.java:364)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.lambda$buildCompilerSettingsMap$4(BlazeConfigurationResolver.java:318)
	... 6 more


java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/jetbrains/cidr/lang/toolchains/CidrSwitchBuilder$Format
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.buildCompilerSettingsMap(BlazeConfigurationResolver.java:329)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.update(BlazeConfigurationResolver.java:100)
	at com.google.idea.blaze.cpp.BlazeCWorkspace.update(BlazeCWorkspace.java:51)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.lambda$updateInMemoryState$0(BlazeCSyncPlugin.java:71)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.cpp.BlazeCSyncPlugin.updateInMemoryState(BlazeCSyncPlugin.java:63)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$updateInMemoryState$15(BlazeSyncTask.java:826)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$updateInMemoryState$16(BlazeSyncTask.java:819)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.updateInMemoryState(BlazeSyncTask.java:813)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:199)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:158)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:139)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:108)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$3.call(BlazeExecutor.java:105)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/jetbrains/cidr/lang/toolchains/CidrSwitchBuilder$Format
	at com.google.idea.sdkcompat.cidr.CidrSwitchBuilderAdapter.addAllRaw(CidrSwitchBuilderAdapter.java:21)
	at com.google.idea.blaze.cpp.BlazeCompilerSettings.getCompilerSwitches(BlazeCompilerSettings.java:97)
	at com.google.idea.blaze.cpp.BlazeCompilerSettings.<init>(BlazeCompilerSettings.java:51)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.createBlazeCompilerSettings(BlazeConfigurationResolver.java:364)
	at com.google.idea.blaze.cpp.BlazeConfigurationResolver.lambda$buildCompilerSettingsMap$4(BlazeConfigurationResolver.java:318)
	... 6 more
```

**Comment by brendandouglas** [comment]
We don't yet support 2017.1 (it's coming in the next plugin release). Also see #69
