### ISSUE TITLE
IllegalStateException: No SyncPlugin present which provides a default workspace type during import of bazel project

### ISSUE THREAD

**Issue by matawed** [bazelbuild/intellij#948]
I cannot import a bazel workspace into CLion on one specific PC. On another PC with exactly the same setup bazel workspace (same revision), same CLION version, same bazel plugin it works, same .bazelrc (is checked in workspace).

### Steps to reproduce the issue:

1. import bazel project via
![image](https://user-images.githubusercontent.com/30142056/60187258-8bec9a00-982d-11e9-8491-57e4a78cc569.png)

2. select bazel workspace
![image](https://user-images.githubusercontent.com/30142056/60187854-a07d6200-982e-11e9-83df-8d0716acb69f.png)

3. select project view via "Generate from build file"
![image](https://user-images.githubusercontent.com/30142056/60187916-bb4fd680-982e-11e9-9c20-ac8763080809.png)

Nothing happens if I click on "Next" button, the workflow is **not** continued, instead the following exception (IDE internal error occured) is raised and logged in CLion main window. 

```
java.lang.IllegalStateException: No SyncPlugin present which provides a default workspace type.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.idea.blaze.base.sync.projectview.LanguageSupport.getDefaultWorkspaceType(LanguageSupport.java:48)
	at com.google.idea.blaze.base.projectview.section.sections.AdditionalLanguagesSection$AdditionalLanguagesDefaultValueProvider.availableAdditionalLanguages(AdditionalLanguagesSection.java:105)
	at com.google.idea.blaze.base.projectview.section.sections.AdditionalLanguagesSection$AdditionalLanguagesDefaultValueProvider.addProjectViewDefaultValue(AdditionalLanguagesSection.java:81)
	at com.google.idea.blaze.base.wizard2.ui.BlazeEditProjectViewControl.modifyInitialProjectView(BlazeEditProjectViewControl.java:262)
	at com.google.idea.blaze.base.wizard2.ui.BlazeEditProjectViewControl.init(BlazeEditProjectViewControl.java:275)
	at com.google.idea.blaze.base.wizard2.ui.BlazeEditProjectViewControl.update(BlazeEditProjectViewControl.java:229)
	at com.google.idea.blaze.base.wizard2.ui.BlazeEditProjectViewControl.<init>(BlazeEditProjectViewControl.java:134)
	at com.google.idea.blaze.base.wizard2.BlazeEditProjectViewImportWizardStep.init(BlazeEditProjectViewImportWizardStep.java:54)
	at com.google.idea.blaze.base.wizard2.BlazeEditProjectViewImportWizardStep.updateStep(BlazeEditProjectViewImportWizardStep.java:46)
	at com.google.idea.blaze.base.wizard2.BlazeNewProjectWizard.updateStep(BlazeNewProjectWizard.java:88)
	at com.intellij.ide.wizard.AbstractWizard.updateStep(AbstractWizard.java:387)
	at com.intellij.ide.wizard.AbstractWizard.doNextAction(AbstractWizard.java:411)
	at com.google.idea.blaze.base.wizard2.BlazeNewProjectWizard.doNextAction(BlazeNewProjectWizard.java:160)
	at com.intellij.ide.wizard.AbstractWizard$5.actionPerformed(AbstractWizard.java:208)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:706)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1646)
	at com.google.idea.blaze.base.wizard2.BlazeImportProjectAction.actionPerformed(BlazeImportProjectAction.java:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:403)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:388)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:60)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:69)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:330)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Because the issue only happens on one PC, I haven't add any bazel configuration 

### My setup: 
CLion 2019.1.4
bazel plugin v2019.06.03.0.1

### What I tried so far:
- remove CLion via rm -rf and also rm -rf ~/.CLion2019.1, issue still persists on that machine.

What can I do to debug this issue?

**Comment by brendandouglas** [comment]
It sounds like either a bad plugin build or a broken CLion installation. Did you install the bazel plugin from JetBrains' plugin repo (or directly from the IDE)?

**Comment by matawed** [comment]
Directly from IDE, in both CLion installations on different machines. My assumption is that both have the same version of the plugin installed, since both report v2019.06.03.0.1 as their version.

**Comment by alice-ks** [comment]
I'm closing this issue as the report sounds like an issue specific to a certain setup and there hasn't been any comments in more than a year.
