### ISSUE TITLE
ASwBazel build errors with Bazel 0.28

### ISSUE THREAD

**Issue by jin** [bazelbuild/intellij#976]
Usage of `android_common` without `--experimental_google_legacy_api`.

```
$ bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-latest
INFO: Build option --define has changed, discarding analysis cache.
ERROR: /Users/jingwen/code/intellij/aspect/intellij_info_impl.bzl:105:25: android_common is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_google_legacy_api
ERROR: /Users/jingwen/code/intellij/aswb/BUILD:212:1: error loading package 'aspect': Extension 'aspect/intellij_info_impl.bzl' has errors and referenced by '//aswb:aspect_directory'
ERROR: Analysis of target '//aswb:aswb_bazel_zip' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.470s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 19 targets configured)
    currently loading: java ... (2 packages)
    Fetching @local_config_sh; Restarting.
```

Running `zip_plugin_files.py` with host Python 3:

```
$ bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-latest --experimental_google_legacy_api
INFO: Analyzed target //aswb:aswb_bazel_zip (62 packages loaded, 2243 targets configured).
INFO: Found 1 target...
ERROR: /Users/jingwen/code/intellij/aswb/BUILD:234:1: Creating final plugin zip archive failed (Exit 1) zip_plugin_files failed: error executing command bazel-out/host/bin/build_defs/zip_plugin_files --output bazel-out/darwin-fastbuild/bin/aswb/aswb_bazel.zip aspect/WORKSPACE aswb/aspect/WORKSPACE aspect/artifacts.bzl aswb/aspect/artifacts.bzl ... (remaining 20 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jingwen/a7f9cfb321ff8f053a43633ca4d90cc9/sandbox/darwin-sandbox/379/execroot/intellij_with_bazel/bazel-out/host/bin/build_defs/zip_plugin_files.runfiles/intellij_with_bazel/build_defs/zip_plugin_files.py", line 38, in <module>
    main()
  File "/private/var/tmp/_bazel_jingwen/a7f9cfb321ff8f053a43633ca4d90cc9/sandbox/darwin-sandbox/379/execroot/intellij_with_bazel/bazel-out/host/bin/build_defs/zip_plugin_files.runfiles/intellij_with_bazel/build_defs/zip_plugin_files.py", line 35, in main
    outfile.writestr(zipinfo, input_file.read(), zipfile.ZIP_DEFLATED)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfe in position 39: ordinal not in range(128)
----------------
Note: The failure of target //build_defs:zip_plugin_files (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //aswb:aswb_bazel_zip failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 347.553s, Critical Path: 91.50s
INFO: 370 processes: 348 darwin-sandbox, 22 worker.
FAILED: Build did NOT complete successfully
```

**Comment by jin** [comment]
This error does not show up with Bazel 0.27.x.

**Comment by jin** [comment]
Reported in https://github.com/bazelbuild/bazel/issues/8571#issuecomment-510366705

**Comment by jin** [comment]
Keeping this open until the patch release is out.

**Comment by cgruber** [comment]
Once you get through this, I'm getting a lot of --incompatible_depset_is_not_iterable=false problems, as the intellij starlark stuff apparently tries to iterate over depsets.

**Comment by jin** [comment]
@cgruber all the instances of that issue have been resolved on master. What's the version of the your plugin?

**Comment by neakor** [comment]
We are experiencing this issue as well. When will the 0.28 patch version be released?

**Comment by jin** [comment]
@neakor 0.28.1rc1 is available. I've requested for rc1 to be promoted to a release: https://github.com/bazelbuild/bazel/issues/8571#issuecomment-511777685

**Comment by jin** [comment]
0.28.1 is now available. If you're running into `--experimental_google_legacy_api` issues, please update to 0.28.1 and not 0.28.0.

**Comment by neakor** [comment]
Thank you!
