### ISSUE TITLE
bazel 9999: ClassNotFoundException: com.google.idea.blaze.google3.sync.CleanProjectTargetsSyncAction

### ISSUE THREAD

**Issue by natros** [bazelbuild/intellij#994]
Hi, 

The bazel plugin compiled from master complains about a missing class:

```
com.intellij.diagnostic.PluginException: com.google.idea.blaze.google3.sync.CleanProjectTargetsSyncAction PluginClassLoader[com.google.idea.bazel.ijwb, 9999] com.intellij.ide.plugins.cl.PluginClassLoader@63ff812 [Plugin: com.google.idea.bazel.ijwb]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:471)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:459)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1266)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:63)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.idea.blaze.google3.sync.CleanProjectTargetsSyncAction PluginClassLoader[com.google.idea.bazel.ijwb, 9999] com.intellij.ide.plugins.cl.PluginClassLoader@63ff812
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:146)
	... 19 more
```

```
$ bazel info
Starting local Bazel server and connecting to it...
bazel-bin: /private/var/tmp/_bazel_fsousa/b402c6ebcaa153a20bf24d0347c93aa1/execroot/intellij_with_bazel/bazel-out/darwin-fastbuild/bin
bazel-genfiles: /private/var/tmp/_bazel_fsousa/b402c6ebcaa153a20bf24d0347c93aa1/execroot/intellij_with_bazel/bazel-out/darwin-fastbuild/bin
bazel-testlogs: /private/var/tmp/_bazel_fsousa/b402c6ebcaa153a20bf24d0347c93aa1/execroot/intellij_with_bazel/bazel-out/darwin-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /private/var/tmp/_bazel_fsousa/b402c6ebcaa153a20bf24d0347c93aa1/command.log
committed-heap-size: 253MB
execution_root: /private/var/tmp/_bazel_fsousa/b402c6ebcaa153a20bf24d0347c93aa1/execroot/intellij_with_bazel
gc-count: 7
gc-time: 102ms
install_base: /var/tmp/_bazel_fsousa/install/ce6f4f2448eb9c8cbd7a3124ff3ed8a3
java-home: /private/var/tmp/_bazel_fsousa/install/ce6f4f2448eb9c8cbd7a3124ff3ed8a3/_embedded_binaries/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 11.0.2+7-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.2+7-LTS, mixed mode) by Azul Systems, Inc.
max-heap-size: 3817MB
output_base: /private/var/tmp/_bazel_fsousa/b402c6ebcaa153a20bf24d0347c93aa1
output_path: /private/var/tmp/_bazel_fsousa/b402c6ebcaa153a20bf24d0347c93aa1/execroot/intellij_with_bazel/bazel-out
package_path: %workspace%
release: release 0.28.0
repository_cache: /var/tmp/_bazel_fsousa/cache/repos/v1
server_log: /private/var/tmp/_bazel_fsousa/b402c6ebcaa153a20bf24d0347c93aa1/java.log.nostradamus.fsousa.log.java.20190715-203853.22503
server_pid: 22503
used-heap-size: 40MB
workspace: /Users/fsousa/Projects/code/bazel-intellij
```

```
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
Licensed to Filipe Sousa
Subscription is active until December 27, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
```

**Comment by brendandouglas** [comment]
Thanks, I'll fix this upstream
